### ISSUE TITLE
Possible feature request: Minimum and maximum decimal places

### ISSUE THREAD

**Issue by ragulka** [autoNumeric/autoNumeric#24]
I am working on a project where I need to enable the user to enter a price. The price field should always have at least 2 decimal places, but could contain many more (if dealing with extra-specific and extra-precise prices). The field should always be padded with 2 decimal places, but not more.

The idea is that the user can, if needed, enter more than 2 decimal places, but if they do not, then only 2 decimal places are show.

Is it somehow possible already or if not, perhaps this could be considered as a possible future feature?

**Comment by ragulka** [comment]
@BobKnothe based on your suggestion, I've come up with the following: http://jsfiddle.net/vmo1m7em/, however, it breaks when you enter an integer with no decimals. Ideally, it would be nice if the `aPad` option could receive a numeric value as input, and this would control how many decimal places will be padded:

* `mDec: 5, aPad: false` - no padding at all
* `mDec: 5, aPad: true` - pads 5 decimal places
* `mDec: 5, aPad: 2` - pads 2 decimal places
* `mDec: 5, aPad: 7` - pads 5 decimal places, since mDec sets the maximum to 5

**Comment by ragulka** [comment]
Just realized this is already implemented :)

**Comment by burzum619** [comment]
@ragulka I see that you mentioned this feature is already implemented in the autoNumeric library - but I do not see any reference to min/max decimal places/"0" padding in the current docs. Any chance you can refer me to how to use this feature? I'm trying to accomplish the behavior @BobKnothe spelled out: 

MIN: 2, MAX: 3

22 => 22.00
22.1 => 22.10
22.12 => 22.12
22.123 => 22.123

**Comment by AlexandreBonneau** [comment]
@burzum619 you can only define a fixed number of decimals for a given AutoNumeric element.
It's not possible to have a different number of decimals shown based on the element value.
You can either decide to show the padding with `allowDecimalPadding` or not (check the examples on http://autonumeric.org/#/guide).

You can however define different numbers of decimals to be shown on blur (`decimalPlacesShownOnBlur`) and on focus (`decimalPlacesShownOnFocus`) if that could help you.

**Comment by burzum619** [comment]
@AlexandreBonneau Thanks for the quick response. Unfortunately I'm sure that is quite what I'm looking for. Perhaps I'll have add some custom code in my component to address this after autoNumeric has formatted the input value. Looks like I'll have to listen in on the `autoNumeric:formatted` event and edit the value there.

**Comment by tomas-net** [comment]
@burzum619 Do you have any code / autoNumeric extension / patch which will enable above described feature?

I need something very similar:
**22 => 22**
22.1 => 22.10
22.12 => 22.12
22.123 => 22.123

**Comment by AlexandreBonneau** [comment]
@tomas-net what you are trying to do can be achieved by using the `{ allowDecimalPadding : 'floats' }` option (see the [official example](http://autonumeric.org/guide#allowDecimalPadding)).

**Comment by tomas-net** [comment]
@AlexandreBonneau Maybe I am doing something wrong. I have

```
{
allowDecimalPadding : 'floats',
decimalPlaces : 2
}
```

And for value in input I get this:
22 => 22 - OK
22.1 => 22.10 - OK
22.12 => 22.12 - OK
**22.123 => 22.12 - **NOT OK****

To be more precise, I can't even enter 22.123, I can enter only two decimal places. If I generate ```<input type="text" value="22.123" />``` on server I get 22.12 which is not OK. What I need is: user can enter number with up to 2 decimal places but server-generated data can contain more than 2 decimal places and I must be able to show them to users. So what I am doing wrong?

**Comment by AlexandreBonneau** [comment]
What you are asking here is a use case we never encountered before, ie. wanting : 
- a specific number of decimal places which should be padded with `0` *if* there is a decimal part
- no decimal points nor decimal places nor `0` padding with there is no decimal part (so far this is what the `allowDecimalPadding` set to `'floats'` does)
- and being able to add as many additional decimal places.

This is not possible with AutoNumeric.
You can specify a fixed number of decimals for the `rawValue`, shown on blur and shown on focus.

If you want this feature, we would consider a PR ;)

About you last question ; you want the server to be able to keep more decimals than your user can enter, is this really what you want?
If this is really your use case, you could use `decimalPlacesShownOnBlur` set to `4` for instance, and `decimalPlacesShownOnFocus` set to `2`.

**Comment by ragulka** [comment]
@AlexandreBonneau I was planning to upgrade to v4, but noticed that the `allowDecimalPadding` option n o longer accepts a number. The equivalent option [`aPad` in v1.9 did support providing a number](https://github.com/autoNumeric/autoNumeric/blob/1.9.x/autoNumeric.js#L1470). 

I didn't notice anything in the upgrade guide or changelog about removing this functionality, which is essentialy a breaking change.

I wonder what was the reasoning to remove this and whether there's an alternative I'm not aware of?

**Comment by AlexandreBonneau** [comment]
@ragulka please create a new issue if you encounter a new problem
`allowDecimalPadding` (or `aPad`) before has been changed so that you can either choose when you want AutoNumeric to pad the decimals (see the [documentation](http://autonumeric.org/guide#allowDecimalPadding)).

The [upgrade guide](https://github.com/autoNumeric/autoNumeric/blob/next/doc/HowToUpgradeToV4.md#configuration) do mention how decimals are set now.

If you want to be able to define the number of decimals, you need to checkout the [decimalPlaces](http://autonumeric.org/guide#decimalPlaces) option.
This has been done to make options more consistent with one option `allowDecimalPadding` to decide if and how to pad the decimals, and `decimalPlaces` (and its variants) to define how many decimal places you want.

**Comment by dion96** [comment]
@tomas-net Did you solve it? 

@AlexandreBonneau Did you solve the issue of tomas? If so could you share with me on how I could accomplish this issue?

I want it to be possible that if I set the value programmatically that it formats to 4 decimals. But whenever you type it should be allowed to set more than 4 decimals. Looking forward to your reply!

**Comment by tomas-net** [comment]
@dion96 I came up with the following solution. I am not happy about it but it seems to work if I remember correctly.

    $(document).on('autoNumeric:formatted', function(e) {
      var anElement = e.originalEvent.detail.aNElement;
      var oldValue = e.originalEvent.detail.oldValue;
      var newValue = e.originalEvent.detail.newValue;

      if(oldValue === undefined)
        return;

      var oldValueDecimalPointIndex = oldValue.indexOf(autonumericOptions.decimalCharacter);

      if(oldValueDecimalPointIndex === -1)
        oldValueDecimalPointIndex = oldValue.indexOf(autonumericOptions.decimalCharacterAlternative);

      var newValueDecimalPointIndex = newValue.indexOf(autonumericOptions.decimalCharacter);

      if(newValueDecimalPointIndex === -1)
        newValueDecimalPointIndex = newValue.indexOf(autonumericOptions.decimalCharacterAlternative);

      if(oldValueDecimalPointIndex === -1 && newValueDecimalPointIndex === -1)
        return;

      var oldValueDecimalPart = oldValueDecimalPointIndex !== -1 ? oldValue.slice(oldValueDecimalPointIndex + 1) : '';

      if(oldValueDecimalPart.length > autonumericOptions.minimumDecimalPlaces) {
        try {
          anElement.setUnformatted(newValue.slice(0, newValueDecimalPointIndex) + autonumericOptions.decimalCharacter + oldValueDecimalPart.slice(0, autonumericOptions.maximumDecimalPlaces));
        }
        catch (e) { }
      }
    });
