### ISSUE TITLE
plugin ignore settings.

### ISSUE THREAD

**Issue by prainho** [autoNumeric/autoNumeric#36]
I'm doing this:

$('#someID1').val("1.456");
$('#someID1').autoNumeric('init', {aSep: '.', aDec: ',', vMax: 99999.999}); 

the result is: 1,456, this value is wrong it' should be 1.456 because the group separator is '.' and decimal separator is ','

$('#someID2').val("1.456");
$('#someID2').autoNumeric('init', {aSep: ',', aDec: '.', vMax: 99999.999});

the result is: 1.456, this value is correct because the decimal separator is '.'

$('#someID1').val("1456");
$('#someID1').autoNumeric('init', {aSep: '.', aDec: ',', vMax: 99999.999}); 
the result is: 1.456,000, this value is correct

I've looked to the code and you are in lots of places ignoring the settings and just assume that group separator is ',' and decimal separator is '.' and this is wrong.

Is it possible to fix this in the following days?

**Comment by ssathishkumar540** [comment]
I also using the following code,
      $('.com1').val("99999.99");
	$('.com1').autoNumeric('init', {aSep: ',', aDec: '.', vMax: 99999.99});

It is always showing the same value 99999.99 only. I want to display the manually entered value. I will try the following way also, 
        $('.com1').val();
	$('.com1').autoNumeric('init', {aSep: ',', aDec: '.', vMax: 99999.99});

But it is taking only 3 digits before decimal. I cant able to enter more than 3 digits. Please help me, I want to enter in a text box lesser than or equal to "99999.99". How can I do that?

**Comment by BobKnothe** [comment]
Please post an example on jsfiddle


 
Robert (Bob) Knothe

**Comment by Raylehnhoff** [comment]
Call .init() on the textbox, and then use .autoNumeric('set', 9999.99).

Setting values with .val() may not apply formatting as expected.
