### ISSUE TITLE
Create a web page with examples for every autoNumeric options

### ISSUE THREAD

**Issue by AlexandreBonneau** [autoNumeric/autoNumeric#410]
Each examples should show the html + js source, and the result as a live example.

Ideally, those example should be grouped like in the README.

**Comment by BobKnothe** [comment]
Where do you envision this page? Part of the source code on autoNumeric.com(io) or a code pen?

**Comment by AlexandreBonneau** [comment]
I see that as a separate unique html page, that would indeed be part of the upcoming website.

For each example, a codepen snippet would be integrated though, making each example easy to tinker with.

Would that be ok for you?

**Comment by AlexandreBonneau** [comment]
For info, the [options page](http://autonumeric.org/#/guide) already allows any user to tinker with each of those.
The next logical step is display the examples (with more than one option at a time).

**Comment by AlexandreBonneau** [comment]
The current [examples page](http://autonumeric.org/examples) currently is showing the code for pre-defined options, and the [configurator](http://autonumeric.org/configurator) page allows visitors to try any options and directly see its effects.

I guess this issue can be closed as it answers the initial need.

If you have more ideas to improve the example page (or any pages really), please open an issue in the [autonumeric.org repository](https://github.com/autoNumeric/autonumeric.org).
