### ISSUE TITLE
The `minimumValue` and `maximumValue` options are not respected when `emptyInputBehavior` is set to `'zero'`

### ISSUE THREAD

**Issue by idfarm** [autoNumeric/autoNumeric#425]
### Expected behavior
The `minimumValue`/`maximumValue` options should be respected if I use the `emptyInputBehavior` option with value `'zero'` and the allowed range does not include zero.

### Actual behavior
Only the `'zero'` value is set on the input element.

### Steps to reproduce the problem
1. Using autoNumeric `2.0.10` and the browser `Chrome` version `56.0.2924.87` on `Windows 10 Pro`,
2. I used the options:
```
{
  emptyInputBehavior: 'zero',
  minimumValue: '1',
  maximumValue: '100',
}
```
3. Select the input element and use `backspace` or `delete` to remove the value.

### Link to live example
http://codepen.io/anon/pen/PpdZOM?editors=1111

Only Firefox seems to work correctly. I've tested it with Chrome, Firefox, IE, Edge and Safari.

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this @idfarm, we'll get on it as soon as possible!

**Comment by AlexandreBonneau** [comment]
@idfarm how would you see in the case you wrote the value that should be set on focus out?

Either no value since '0' is not in the allowed range, or the closest value to 'zero' (here, `'1'`) ?

@BobKnothe any thoughts on that?

**Comment by AlexandreBonneau** [comment]
..or, during initialization we could add a check and throw an error if `emptyInputBehavior` is set to `zero` while `0` is not included in the `minimumValue`-`maximumValue` range.

Why would you want to have your element value set to `0` when empty if you do not allow such value in the allowed range?

**Comment by AlexandreBonneau** [comment]
We discussed that issue with @BobKnothe, and we agree that we should throw an error if such case is detected, since it's a conflict.

**Comment by idfarm** [comment]
I was looking for a method to make an input element a required numeric field, so if the user tries to clear the input element, either a default value would appear or the user input would be blocked.

I couldn't find a property to set a default value or make the field required other than setting `emptyInputBehavior `to `zero`, so I assumed the combination of `emptyInputBehavior` set to `zero `and a `minimumValue`/`maximumValue `should set the input to the closest value within the range.

User input other than 'empty' that would lead to an invalid value is blocked. Is there a way to have this behaviour for user input that would lead to an empty value?

**Comment by AlexandreBonneau** [comment]
Well, we'd have to weight if this new option should be included in autoNumeric.
Perhaps you could create a PR and we'll take a look from there?
What do you think about that @BobKnothe?

On the other hand, you could listen to the `'autoNumeric:formatted'` event and change the value yourself as needed.

**Comment by BobKnothe** [comment]
@AlexandreBonneau 

Sorry for the late response.

I am inclined to agree with listening for the `'autoNumeric:formatted'` event. IMHO this will be more flexible than defining a option.

Bob

**Comment by idfarm** [comment]
The event `autoNumeric:formatted` does not trigger if the value is empty. 

The `onKeyup` function is returned at line [3473](https://github.com/autoNumeric/autoNumeric/blob/master/src/autoNumeric.js#L3473). So it never triggers the `autoNumeric:formatted` event.

Was there a specific reason not to add a custom value for the `emptyInputBehavior` property? Only allowing `zero` seems limiting.

**Comment by AlexandreBonneau** [comment]
@idfarm good catch, I'll see what I can do about `'autoNumeric:formatted'` not being sent if the value is set to empty.

About the `emptyInputBehavior` option, we could imagine allowing the user to give a value to default to when the element value is emptyied, if @BobKnothe is ok with this idea.
Could you please create another issue with this feature request? Thanks!

**Comment by AlexandreBonneau** [comment]
For info, this [commit](https://github.com/autoNumeric/autoNumeric/commit/8ba34b4a0b3286ceabfc41e1746a6ef2b3377865) fixes the `autoNumeric:formatted` event not being sent in various cases.
