### ISSUE TITLE
Real time imaging problem

### ISSUE THREAD

**Issue by arafsan** [autoNumeric/autoNumeric#441]
Hi,
First of all thank you for the plugin. It really works great. But I have a little problem.
I prepared 2 "jsfiddle" samples to make my problem more comfortable.
The goal is to dynamically add the values of the 2 inputs and display them in a dynamic and instantaneous 3rd input field.
In the first example, I update in each "keyup" operation using the update method, but it comes to the end of the cursor field and it prevents me from writing this option.
In the second example, I removed the "update" method, but this time I can not see the change dynamically and instantly. I have to stop typing and get out of the input area.
Could yu give me a way to instantly see the result as I continue to write?

First Example : https://jsfiddle.net/swLcwf9f/
Second Example : https://jsfiddle.net/swLcwf9f/1/

I hope it was explanatory.
Many thanks again.

**Comment by BobKnothe** [comment]
@arafsan 

Thanks for your interest in autoNumeric.

The "update" method causes the focus to be lost. You will need to capture the caret position prior to the "update" method being called and then reset the caret position after the "update" method call been called.

Rather then using the "update method please try the following:

  
$("#firstField, #secondField").on("keyup", function() {
	var one = parseInt($('#firstField').autoNumeric('get'));
  var two = parseInt($('#secondField').autoNumeric('get'));
  var sum = parseInt(one) + parseInt(two);
	$('#result').autoNumeric('set', sum);
});
 
Hope this helps.

If you find this solves your issue please close the issue

**Comment by AlexandreBonneau** [comment]
Hey @arafsan, if @BobKnothe answer fixed your problem, please close this issue!

Otherwise we'll close it in a few days due to inactivity.

**Comment by AlexandreBonneau** [comment]
Without activity on this issue, we are closing it.
Feel free to reopen it if this is needed.
