### ISSUE TITLE
`AutoNumeric.unformat()` only removes the first instance of `settings.digitGroupSeparator`

### ISSUE THREAD

**Issue by bforsythe** [autoNumeric/autoNumeric#449]
`AutoNumeric.unformat("$1,234,567.00", AutoNumeric.getPredefinedOptions().dollar)` => "1234,567.00"

In `v4.0.0-beta.18`, seems to be happening in `_convertToNumericString()`
```js
    static _convertToNumericString(s, settings) {
        // Remove the currency symbol
        s = s.replace(settings.currencySymbol, '');

        // Remove the grouping separators (thousands separators usually)
        s = s.replace(settings.digitGroupSeparator, '');
        ...
        return s;
    }
```
Looks like replacing:
 `s = s.replace(settings.digitGroupSeparator, '');` 
with `s = s.replace(new RegExp('[' + settings.digitGroupSeparator + ']', 'g'), '')`
does the trick.
Thanks, Brandon

**Comment by AlexandreBonneau** [comment]
Thanks for reporting that @bforsythe, we'll look into it.
Meanwhile, would it be possible to create small codepen that reproduce the problem ; that will help us quite a lot!

Thanks

**Comment by AlexandreBonneau** [comment]
Well, I'm baffled that I could omit such a basic thing like searching for *all* occurrences of the `settings.digitGroupSeparator`!

The weirdest thing is that neither our 223 unit nor our 70 end-to-end tests did catch that!!

:/

Thanks again for finding this one :)

**Comment by AlexandreBonneau** [comment]
The [longest string](https://github.com/autoNumeric/autoNumeric/blob/next/test/unit/autoNumeric.spec.js#L5184) I tested was '$1,234.56', so..good to know ;)

**Comment by bforsythe** [comment]
Hah it happens, thanks again for the quick response, we've used autoNumeric for our money/number fields for a while now, it's been super useful.

BTW here's a codepen if you still want it (I didn't realize it was so easy to use jasmine in one): https://codepen.io/bforsythe/pen/XRLKgE
Ignore the html, I was having a hard time getting an autoNumeric reference to the 4.0.0-beta.18 in there

**Comment by AlexandreBonneau** [comment]
Thanks I did not know either that you could use Jasmine that way ;)

**Comment by AlexandreBonneau** [comment]
Thanks again for your contribution, it's now fixed in `next`!

**Comment by bforsythe** [comment]
Awesome, thanks!
