### ISSUE TITLE
Destroy causes js error on hover

### ISSUE THREAD

**Issue by ducman** [autoNumeric/autoNumeric#451]
### Expected behavior
Input is reverted back to a normal text box after calling destroy.

### Actual behavior
Javascript errors are thrown:
> Uncaught Error: Initializing autoNumeric is required prior to calling the "set" method.

### Steps to reproduce the problem
1. Using autoNumeric `2.0.12` and the browser `Chrome` version `58.0.3029.96` on `Windows 10`,
2. I used the options default, and 
3. Initialized my AutoNumeric object with the call `$('input').autoNumeric();`,
4. Destroy using `$(input).autoNumeric('destroy');`,
5. Hover over the input field and notice js error thrown
6. Type a letter and notice you're not allow to. Input is still "autoNumeric" (most likely due to js error).

### Link to live example
https://codepen.io/anon/pen/ZKgwKg
1. Click "init"
2. Click "destroy"
3. Hover over the input and notice javascript error. 

I'm have a hard time trying to figure out/debug the problem myself to help out some more since the js code is all in 1 line. I'm not sure why it is like that since it's the regular autoNumeric.js file (not min).

**Comment by AlexandreBonneau** [comment]
Hey @ducman, thanks for reporting this.

Would it be possible to try with the `next` version and see if that still do this error?
This is the version `4.0.0` that will be release really soon in a few days.

In this version, event handlers have been rewrote entirely and now they should all be removed correctly on 'destroy' (which has been replaced by `anElement.remove()` (cf. the [documentation](https://github.com/autoNumeric/autoNumeric/tree/next#un-initialize-the-autonumeric-element))

**Comment by ducman** [comment]
Dumb question but how do you construct a new codepen with the new v4.0 code? Do you have a dist js file I can reference?

**Comment by AlexandreBonneau** [comment]
Unfortunately not for now.
When `v4` will be made official in a few days, we'll include the `dist` files in the release.

For now if you need the `dist` file you need to compile them yourself, using:
```sh
git clone -b next https://github.com/autoNumeric/autoNumeric.git && cd autoNumeric && yarn && yarn build
```
then use the resulting `dist/autoNumeric.min.js` file in codepen by pasting it (sic!).

I know that's not perfect, but until browser natively supports the `import` keyword, we are stuck with that :/

**Comment by AlexandreBonneau** [comment]
My bad, the great unpkg website does generate the `dist` files automatically!

Here : https://unpkg.com/autonumeric@4.0.0-beta.20/dist/

**Comment by AlexandreBonneau** [comment]
Without any activity on this, I'm closing the issue.
Feel free to reopen it if you still encounter the problem.
