### ISSUE TITLE
Could not insert 0 char at last position - Android mobile Chrome (v58)

### ISSUE THREAD

**Issue by IRuslan** [autoNumeric/autoNumeric#459]
### Expected behavior
I have a simple mask to format currency like:
$10
On Android mobile Chrome I should be able to input amount ending with 0.

### Actual behavior
In an example, I want to insert '10' amount.
When I'm typing 1 - all is ok.
After, I'm typing 0 - nothing happens, I still have a 1 in the input field.
If I type any other char - everything is ok (e.g. 11 works, but 110 also impossible to type).

### Steps to reproduce the problem
1. Using autoNumeric `v2.0.12` and the browser `Chrome` version `58` on `Android`,
2. I used the options:

>             var options = {
>               aSep: ',',
>               aSign: '$',
>               pSign: 'p',
>               mDec: 0,
>               dGroup: 3
>             }

3. Initialized my AutoNumeric object with the call `$('#my-input').autoNumeric('init', options)`,

**Comment by IRuslan** [comment]
The problem was in my custom JS script. Not relevant for the library.

**Comment by AlexandreBonneau** [comment]
Thanks for closing that issue on your own then :)
