### ISSUE TITLE
don't fill input with default zeros if it is left blank by user

### ISSUE THREAD

**Issue by AlirezaAhmadiRad** [autoNumeric/autoNumeric#462]
### Expected behavior
I want to understand if user has left an input blank or if user has entered zero

### Actual behavior
Input is automatically filled with zero as soon as it is hovered over or focused . I will not understand if user has entered zero or left the field blank

I get results from $('#'+ id).autoNumeric('get');
### Steps to reproduce the problem
Default setup.

Thanks for reporting a bug or giving us great ideas with your feature request!

**Comment by AlexandreBonneau** [comment]
Hey @AlirezaAhmadiRad, that default behavior can be changed using the `emptyInputBehavior` [option](https://github.com/autoNumeric/autoNumeric/tree/next#options), cf. detail [there](https://github.com/autoNumeric/autoNumeric/blob/next/src/AutoNumericOptions.js#L209).

For your case you could use the `'press'` value, or check the new `'null'` value : *When the element is empty, the `rawValue` and the element value/text is set to `null`. This also allows to set the value to `null` using `anElement.set(null)`.*

I hope this answer your question, if so, please close this issue!

**Comment by AlirezaAhmadiRad** [comment]
Hello and thanks for your fast response.
I'm currently using version 2.0.12, released on Apr.07.2017. When I used 'null' option as recommended, I receive this error:

**Comment by AlirezaAhmadiRad** [comment]
And I had time to check element.value option as you mentioned, this gives back those auto-filled zeros. No way to understand if a user has only clicked a control without entering a value. Showing currency sign by default is a good idea, but there needs to be an option not to autofill zeros beside that currncy sign.

**Comment by AlexandreBonneau** [comment]
The new `'null'` option (as with all *new stuff*) is in the `next` branch.
The `next` branch is pretty stable, and we'll release `v4` *soon™*, so it's pretty safe to use now.

Could you try that?

**Comment by AlirezaAhmadiRad** [comment]
All right, I downloaded the "next" branch from this address:
https://github.com/autoNumeric/autoNumeric/tree/next
 * @version      4.0.0-beta.21
 * @date         2017-06-02 UTC 23:30

Then I used the file src\autonumeric.js and replaced the older version with this new file. Is this correct? (Sorry if I'm doing the wrong thing because I'm not very familiar with conventions of this github site)
Or shall I combine all files?

If I have used the correct library , then the results were not satisfactory. I'm getting this error:
Uncaught TypeError: $(...).autoNumeric is not a function

Thanks

**Comment by AlexandreBonneau** [comment]
No problem :)

If you use `autoNumeric.js` directly in the browser, it won't work since most of those do not support the `import` statement.

You need to compile the code then use the `dist/autoNumeric.js` file.
This is detailed [there](https://github.com/autoNumeric/autoNumeric/tree/next#how-to-contribute).

Also, the version in `next` dropped the jQuery dependency so instead of calling:
```js
$('#'+ id).autoNumeric('get');
```
you will need to use:
```js
const yourAnObject = new AutoNumeric('#'+ id, yourOptions);
// Then if you want to 'get' the value, use
yourAnObject.get(); // or better yet yourAnObject.getNumericString();
```

**Comment by AlexandreBonneau** [comment]
Without any activity on this, I'm closing the issue.
Feel free to reopen it if you still encounter the problem.
