### ISSUE TITLE
Let scientific (Exponential) values be entered

### ISSUE THREAD

**Issue by AlirezaAhmadiRad** [autoNumeric/autoNumeric#463]
### Expected behavior
Let scientific (Exponential) values be entered

### Actual behavior
It is not supported.

**Comment by AlexandreBonneau** [comment]
Could you please be more specific, with examples for instance?

Right now I'd say this is out of autoNumeric scope which focus on currencies though.

**Comment by AlirezaAhmadiRad** [comment]
Hello and thanks for your fast response.

This is a sample of how my control is initialized:
$('#SomeID').autoNumeric('init', { digitGroupSeparator : ',',decimalPlacesShownOnFocus : '2',decimalPlacesOverride : '2',decimalPlacesOverride : '2',emptyInputBehavior: 'press' });

It simply doesn't allow me to use 'e' or 'E' characters in input. I'll take care of format conversion by myself. But it does't let me use E character.

**Comment by AlexandreBonneau** [comment]
Yes, this is normal behavior since 'E' is not a number nor a decimal character.
Could you describe exactly how you would expect aN to behave when entering such character?

**Comment by AlirezaAhmadiRad** [comment]
If you have access to Microsoft Excel, please check the behavior there. You can enter e.g. 2.384e-3 and it behaves it like a number.
I suggest it is possible and useful to  accept E or e as a decimal character. 
Rules:
1- E shall be taken only once within one autoNumeric field.
2- E can not be first character.
3- E can not be entered directly after decimal period. at least one digit must be in between.
4- Decimal period can not be entered after E.
5- if Power (after E) is not entered, It means Power=0, It means E can be deleted after control lost focus.

This way you do not need to define extra validation rules. These rules will help accepting number in correct format without need for extra validation.

Hope it helps.

**Comment by AlexandreBonneau** [comment]
Thanks for the detailed spec!

I'm not sure this is in the scope of a currency formatter, any thoughts @BobKnothe ?

**Comment by AlirezaAhmadiRad** [comment]
Sorry for too many explanation ;)
If you ever wanted to think about this feature, this may not be related to currency formatter part. This may be implemented within keyup event by a few lines of if.
By the way thanks for considering

**Comment by AlexandreBonneau** [comment]
Well, after thinking more about this feature request, I deem it out of the scope of AutoNumeric, which is mainly a currency formatter.

Thanks for taking the time to create that issue though, all ideas are welcomed! (even if some do not make it into the codebase)
