### ISSUE TITLE
"Unable to get property 'getData' of undefined or null reference" on paste in IE11

### ISSUE THREAD

**Issue by an-kh** [autoNumeric/autoNumeric#465]
Hello!

I've encountered an error in Internex Explorer 11.

If you try to paste any value into input with autonumeric attached, the value won't change and the error appears in console:
![1](https://user-images.githubusercontent.com/26059661/28159638-0bfb03dc-67d7-11e7-9255-dba44e065364.png)

Simple fiddle:
https://jsfiddle.net/fwxkz2pn/
To test try to paste any numeric value into the field.

Version of the autonumeric used: 2.0.12

The error appears in this line of the library file:
![2](https://user-images.githubusercontent.com/26059661/28159737-60461148-67d7-11e7-96d7-999ca4f19fea.png)

In seems that event argument (which is for some reason is of type DragEvent, possibly some ie bug) IE doesn't have the object "clipboardData".

The solution, that is frequently suggested on the internet is something like this:
https://stackoverflow.com/questions/30125770/paste-event-listener-on-internet-explorer-getting-wrong-arguments

I've seen that this issue is fixed in the similar way in the next branch (4.* version), but can the change also be applied to the older stable jquery version (2.* version)?

**Comment by an-kh** [comment]
Maybe small chack can be added, like here:
https://github.com/froala/wysiwyg-editor/issues/550
or here
https://stackoverflow.com/questions/30125770/paste-event-listener-on-internet-explorer-getting-wrong-arguments

**Comment by an-kh** [comment]
One solution that is often suggested on the internet:
https://stackoverflow.com/questions/30125770/paste-event-listener-on-internet-explorer-getting-wrong-arguments
Maybe, something likt this check should be added.

**Comment by an-kh** [comment]
I've seen that this issue is fixed in the next 4.* branch, but can the change be made for users who want to use older stable jquery version?

**Comment by AlexandreBonneau** [comment]
Hey @an-kh, thank you for reporting this.

I'll see what I can do about that next week. I'll have hopefully more time to merge the pending PR and port the fix from `next` to the current stable in `master`.

**Comment by an-kh** [comment]
@AlexandreBonneau To speed things up a little I've created a pull request: [466](https://github.com/autoNumeric/autoNumeric/pull/466)
This is the same solution, that was applied to in the next branch for the issue [440](https://github.com/autoNumeric/autoNumeric/issues/440).
Unfortunataly, code coverage have fallen a tiny bit, and I don't know how to test this type of IE specific issue. Althouth, there were no tests in the [initial fix](https://github.com/autoNumeric/autoNumeric/commit/d6dab0bbf1a139c5d667cc3c126ac9e5a415a15d) either.
I did not build the project of written any changes to the changelog file, but can do if required.

**Comment by AlexandreBonneau** [comment]
Thanks, I'll merge the PRs 'soon', the rewritting how decimal places were managed is almost done!

**Comment by AlexandreBonneau** [comment]
Thank you again for taking the time to report *and* create the PR to fix this!

**Comment by an-kh** [comment]
No problem. Thank you.
