### ISSUE TITLE
Hide decimals when unfocus input

### ISSUE THREAD

**Issue by Giobbo89** [autoNumeric/autoNumeric#468]
Hi!
I have a little problem with this great plugin.
This is my problem: in my input, I want to insert value with decimals (like "12.345" or "0.2222") but when the input is unfocus, decimals numbers must be hidden.

I have tried with this solution:

`$(".myclass").autoNumeric('init', {
            digitGroupSeparator: "'",
            noSeparatorOnFocus: true,
            decimalCharacter: '.',
            decimalPlacesOverride: '0',
            decimalPlacesShownOnFocus: '3',
            saveValueToSessionStorage: true,
  });`

and it works fine, but not completely; because when change the value and unfocus input, that value is sent to the server for save it, but is sent only the int part of value and not the decimals.
Example:

Insert 12.345 --- unfocus ---> I see 12 (it's right) --- focus ---> 12.345 (it's right again)

Visually, the behavior is correct. But at server is sent only 12, not 12.345. I need to sent even decimals.
It's possible?

**Comment by AlexandreBonneau** [comment]
Hey @Giobbo89, you're in luck, a recent [commit](https://github.com/autoNumeric/autoNumeric/commit/b11b93dded7334dfd736fcd7c323335e0dcd9c8c) in the `next` branch added the new `decimalPlaces*` option feature.
This allows you to explicitely define how many decimal places you want for each object state (focused/unfocused) and the `rawValue` (which keeps an unformatted copy of the current element value).

Now to solve your problem you can just do:
```js
const anElement = new AutoNumeric('.myClass', {
    digitGroupSeparator: "'",
    decimalCharacter: '.',
    showOnlyNumbersOnFocus: true, // Renamed from `noSeparatorOnFocus`
    decimalPlaces: 0,
    decimalPlacesShownOnFocus: 3,
    saveValueToSessionStorage: true,
}
```

That way the number of decimal places for the `rawValue` is still `3`, not `0` which was forced before using the deprecated `decimalPlacesOverride` option.

Is that ok with you?

**Comment by Giobbo89** [comment]
Thanks for your fast answer!
I try this solution, but the compiler show me an error "AutoNumeric is not defined".
Why? I import the plugin using this:

`<script src="https://cdn.jsdelivr.net/autonumeric/2.0.0/autoNumeric.min.js"></script>`

Where is the error?

**Comment by AlexandreBonneau** [comment]
This is because you are using the version from `master`.
This is working with the version in the `next` branch.

**Comment by Giobbo89** [comment]
Sorry, my bad.
Now I have tried with the next branch, import plugin like this:

`<script src="https://cdn.jsdelivr.net/autonumeric/4.0.0/autoNumeric.min.js"></script>`

without any other installation (I use VS and don't have yarn or npm), but there is the same error.
Thank you for your help and patience.

**Comment by AlexandreBonneau** [comment]
No problem :)
Since `v4.0.0` is not released yet, it's not on any CDN.

We do not generate the `dist` files while coding in the `next` branch.
If you want to use the latest version, you need to compile it yourself (do not worry, it's [very easy](https://github.com/autoNumeric/autoNumeric/tree/next#how-to-contribute)).

run:
```sh
git clone -b next https://github.com/autoNumeric/autoNumeric.git && cd autoNumeric && npm install && npm run build
```

Once this is done, you'll find the compiled library in the `./dist` folder.
You can then use the `./dist/autoNumeric.js` file in your html files.

**Comment by AlexandreBonneau** [comment]
Note: you can now use the CDN for the latest `v4.0.1`:
https://unpkg.com/autonumeric@4.0.1/dist/autoNumeric.min.js

**Comment by AlexandreBonneau** [comment]
Without activity seen on this issue, we are closing it.
Feel free to reopen it if you think your problem still persist.
