### ISSUE TITLE
The caret is wrongly placed on Chrome mobile with `v2.0.13`

### ISSUE THREAD

**Issue by estavex** [autoNumeric/autoNumeric#470]
### Expected behavior
Normal format just like on desktop or laptop devices.

### Actual behavior
Selection gets messed up and not being put at the end of string while typing on mobile.

### Steps to reproduce the problem
1. Test this plugin on any mobile device and see for yourself.

It works fine on desktop, but the mobile version is messed up completely. If I type in a desktop version "123456789" then it normally displays as "$ 123,456,789". If I do the same thing on mobile, it displays as "$ 978,645,312" because I noticed that it's not positioning the cursor at the end of string for some reason, I have to manually click on the end of input after every entered character so that it can enter normally which is really annoying.

Hopefully I was clear and this gets fixed.

**Comment by AlexandreBonneau** [comment]
Hello @estavex, what's the AutoNumeric and mobile browser versions?
Also, a codepen that displays the problem would be great.

**Comment by estavex** [comment]
Hi @AlexandreBonneau, there is no need for a codepen example because you can't see the problem on a desktop browser. Even if you go into the mobile mode in chrome on desktop, you won't see the problem. The only way to see it is if you run on a live mobile device. I have tested it on [your live example](http://www.decorplanit.com/plugin/) on mobile and it seems to be working fine. However, in your example, everything is aligned to the right, and I aligned mine to the left. I think that's the problem.

**Comment by AlexandreBonneau** [comment]
The examples on the old site are deprecated, as stated [here](https://github.com/autoNumeric/autoNumeric/#documentation) and [there](https://github.com/autoNumeric/autoNumeric/tree/next#other-documentation).

Still, you can still run codepen on a mobile you know :)
Hence the need for a codepen showing the problem.

**Comment by estavex** [comment]
@AlexandreBonneau interesting. I just included <script src="https://cdn.jsdelivr.net/autonumeric/2.0.0/autoNumeric.min.js"></script> instead of the local downloaded file and it worked fine. So there was a version issue. Seems like it works on v2.0.0 but not on v2.0.13.

Here's your codepen example https://codepen.io/anon/pen/KvdMbM

I tested it from cdn and it works even on codepen. I believe it's a version issue, but test both versions for yourself if you want to, I might be wrong. Thanks for quick response :)

**Comment by AlexandreBonneau** [comment]
Indeed, with `v2.0.13` (using that CDN `"https://unpkg.com/autonumeric@2.0.13/dist/autoNumeric.min.js"`), the caret is wrongly placed when typing `123456789`.
This can be seen [here](https://codepen.io/anon/pen/dzYpow).

**Comment by NotARobit** [comment]
I ran into this too. I was able to roll back to v2.0.11.

**Comment by AlexandreBonneau** [comment]
I just tried and `v2.0.12` is also working correctly under Chrome.
`v2.0.13` introduced that regression.

**Comment by AlexandreBonneau** [comment]
Could you guys please test with the latest version `4.1.0-beta.28` and report here if the bug is still present? Thanks!

**Comment by AlexandreBonneau** [comment]
Due to inactivity, I'm closing this issue considering it resolved.
If that's not the case, feel free to re-open it!
