### ISSUE TITLE
When `formatOnPageLoad` option is set to `false`, neither the `rawValue` nor the element value are set

### ISSUE THREAD

**Issue by DzmVasileusky** [autoNumeric/autoNumeric#493]
### Expected behavior
No console errors

### Actual behavior
Error Cannot read property 'toString' of undefined

### Steps to reproduce the problem
1. Using autoNumeric `4.0.3` and the latest browser `Chrome`,
2. I used the options <{ currencySymbol:'$', formatOnPageLoad: false }>
3. Just moving cursor in and out of field, focusing/bluring getting to the console error.

### Link to live example (ie. [JSFIDDLE](https://jsfiddle.net/only_dimon/2gbx949j/3/))

I think the problem is somewhere in the formatOnPageLoad option functionality.
Also you can fix it by changing comparison from `value === ''` to `!!value`

**Comment by AlexandreBonneau** [comment]
Thanks for reporting the bug @DzmVasileusky.
There is indeed 2 errors on focus/blur when the `formatOnPageLoad` is set to `false`.

The error and working case defined on this [codepen](https://codepen.io/AnotherLinuxUser/pen/jLXgQN?editors=1011).

**Bonus note**:
You do not have to call:
```js
new AutoNumeric(document.getElementById('test'), { options });
```
...when AutoNumeric can find the right DOM element for you directly with:
```js
new AutoNumeric('#test', { options });
```
😄

**Comment by AlexandreBonneau** [comment]
`v4.1.0-beta.5` fixes that error, by not forgetting to set the `rawValue` (and the unformatted initial value, if given), when `formatOnPageLoad` is set to `false`!

**Comment by DzmVasileusky** [comment]
Thanks, great job!
