### ISSUE TITLE
`AutoNumeric.multiple()` fail on IE11 on unknown `Array.from()`

### ISSUE THREAD

**Issue by halius** [autoNumeric/autoNumeric#495]
### Expected behavior
The .multiple() call works fine in all other browsers I've tested except IE 11. 

### Actual behavior
Error in IE 11 console states `"Object doesn't support property or method 'from'." autoNumeric.min.js, Line: 1, Column: 654`

### Steps to reproduce the problem
1. Set up more than one input field with a given class, e.g. "money-input".  
2. Call:
```js
AutoNumeric.multiple('.money-input', {currencySymbol : '$',
    minimumValue: '0',
    decimalPlaces: '0',
    modifyValueOnWheel: false,
    readOnly: true,
    emptyInputBehavior: 'null'}
);
```

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://jsfiddle.net/2vz7kzqf/

**Comment by halius** [comment]
I would also note that a simple workaround is to iterate over the DOM elements with jQuery and initialize each using the new AutoNumeric() syntax, e.g.:

$('.money-input-field').each(function(){
		new AutoNumeric($(this).get(0), {
			currencySymbol : '$',
			minimumValue: '0',
			decimalPlaces: '0',
			modifyValueOnWheel: false,
			emptyInputBehavior: 'null'
		});
	});

**Comment by AlexandreBonneau** [comment]
Thanks for reporting the IE bug @halius!
