### ISSUE TITLE
The upgrade guide to v4 references the `decimalPlacesOverride` option without indicating it's deprecated

### ISSUE THREAD

**Issue by fugafree** [autoNumeric/autoNumeric#496]
The _Configuration_ section of _Upgrade from versions 1.9.\*/2.\* to version 4.\*_ description says:
Change `mDec` to `decimalPlacesOverride`.

But `decimalPlacesOverride` is deprecated (or not used at all as I experienced). It sould be `decimalPlaces`.

Link:
https://github.com/autoNumeric/autoNumeric/blob/master/doc/HowToUpgradeToV4.md#configuration

**Comment by AlexandreBonneau** [comment]
Ah yes good catch.
I'll update the doc explaining `decimalPlacesOverride` has indeed been replaced, thanks!

**Comment by AlexandreBonneau** [comment]
I hope the explanation in clear enough!
