### ISSUE TITLE
AutoNumeric js returns bad result then converting high precision amount

### ISSUE THREAD

**Issue by pspectro** [autoNumeric/autoNumeric#500]
**Expected behavior**
Then input field value 0.000000000000000001 field.autoNumeric has to return 0.000000000000000001. 

**Actual behavior**
Then i am trying to format 0.000000000000000001 autoNumeric returns 0.000000000000000000.

**Steps to reproduce the problem:**
I am using 1.9.30 version of autoNumeric plugin.
AutoNumeric function with parameters:
`field.autoNumeric('init', {altDec: ',', mDec: '18', lZero: 'keep'})`

I am calling this function on load and i keep getting wrong result. Maybe my setup is wrong or something else is wrong? Because then i am using same exact function for  currency with mDec="6" everything seems alright. 

Thanks in advance :)

**Comment by BobKnothe** [comment]
I have located the issue on the checkValue function.

We are not updating 1.9.30 but i can paste a fix here later after some testing.

**Comment by BobKnothe** [comment]
@pspectro please try replacing the checkValue function with the following and let me know if that works.


``
   /**
     * function to handle numbers less than 0 that are stored in Exponential notation ex: .0000001 stored as 1e-7
     */

    function checkValue(inValue, settings) {
        if (inValue) {
            var checkSmall = +inValue;
            if (checkSmall < 0.000001 && checkSmall > -1 && (inValue.indexOf('e') > -1 || inValue.indexOf('E') > -1)) {
                inValue = +inValue;
                if (inValue < 0.000001 && inValue > 0) {
                    inValue = (inValue + 10).toString();
                    inValue = inValue.substring(1);
                }
                if (inValue < 0 && inValue > -1) {
                    inValue = (inValue - 10).toString();
                    inValue = '-' + inValue.substring(2);
                }
                inValue = inValue.toString();
            } else {
                var parts = inValue.split('.');
                if (parts[1] !== undefined) {
                    if (+parts[1] === 0) {
                        inValue = parts[0];
                    } else {
                        parts[1] = parts[1].replace(/0*$/, '');
                        inValue = parts.join('.');
                    }
                }
            }
        }
        return (settings.lZero === 'keep') ? inValue : inValue.replace(/^0*(\d)/, '$1');
    }
``
The version you are using is old and you should consider upgrading the version 4.xx

**Comment by pspectro** [comment]
Thank you very much. :) I would test this fix and let you know.

**Comment by AlexandreBonneau** [comment]
Without activity on this issue, I'm closing it since it should have been resolved with the latest AutoNumeric version.
If you think this has not solved your problem, feel free to reopen it.
