### ISSUE TITLE
Does this plugin support year format?

### ISSUE THREAD

**Issue by gusbemacbe** [autoNumeric/autoNumeric#508]
### Expected behavior
The autoNumeric keeps the year format as if it was a currency or a decimal.

### Actual behavior
I use the lastest version of autoNumeric and jQuery. I built the codes like:

```javascript
new AutoNumeric('.input', 
  AutoNumeric.getPredefinedOptions().float);
```

It gave 1,989.00 instead of 1,989.

When I typed 1989, it gave 1,989.00 and it gave the wrong result.

For example, without autonumeric:
year 1989 - year 1977 = 12 years

With it:
year 1,989.00 - year 1,977 = 1,944 years

### Steps to reproduce the problem
1. autoNumeric `4.1.0` and  `Chrome` version `<61.0>` on `macOS Sierra 10.12.6`,
3. I initialized my AutoNumeric object with the call `new AutoNumeric('.input', 
  AutoNumeric.getPredefinedOptions().float);`,
4. the decimal is kept because it recognises as a currency. 

I have already tried `{aSep: '.', aDec: ',', mDec: '0'}` and `digitGroupSeparator: '.', decimalCharacter : ',', decimalCharacterAlternative: '.', showOnlyNumbersOnFocus: true`.

I want to keep the year format with separator (comma or dot) without currency and decimal, giving the right result.

**Comment by AlexandreBonneau** [comment]
Hi @gusbemacbe , could you provide a codepen that reproduce your problem?

If you want no decimal places, you can force that using the right option, ie. `decimalPlaces` (you can play with it on http://autonumeric.org/#/guide).

Again, a reproducible example is mandatory if you want us to help you, specially with the *right result* here resulting from a subtraction that is out of control of AutoNumeric!

**Comment by gusbemacbe** [comment]
I use PHP, PHP would not work on Codepen.

**Comment by gusbemacbe** [comment]
I tried `integer` and it doesn't work. I'll test `decimalPlaces`. 

If borth do not work, I'll use pure HTML in Codepen.

**Comment by gusbemacbe** [comment]
The `decimalPlaces` doesn't work and doesn't insert comma or dot. Check my pen: https://codepen.io/gusbemacbe/pen/jGKmbP

**Comment by gusbemacbe** [comment]
I fixed it, but it gave the wrong result (it gave 1944 instead of 12, because if then removed the decimals, it kept hidden decimals.

**Comment by gusbemacbe** [comment]
I zipped PHP file. 

You can test it. Type "1989". The true result is 12, but autoNumeric gave the wrong result. 

[teste-autonumeric.zip](https://github.com/autoNumeric/autoNumeric/files/1375302/teste-autonumeric.zip)

**Comment by AlexandreBonneau** [comment]
No need to declare the `decimalPlaces : 0` option if you use the predefined `integer` option.
Just do:
```js
new AutoNumeric('.input', AutoNumeric.getPredefinedOptions().integer);
```
and you are good to go.

About the calculus your are doing in PHP, this is out of scope of AutoNumeric.
Check the data that your server receive from the form, and you'll see that the raw value is correct.
Can you check how you are manipulating that data on the Php side?

I modified your codepen so you can check the `rawValue` that AutoNumeric sets every time you enter data in that input. Check that out [here](https://codepen.io/AnotherLinuxUser/pen/OxExpK?editors=1111).

**Comment by gusbemacbe** [comment]
I updated and it gave still the wrong result (1976 years instead of 12 yars). It seems that PHP and Javascript misunderstood the numbers. 

```
<?php 
          
          if ($_SERVER['REQUEST_METHOD'] === 'POST') 
          {
              $year = (int)$_POST["year"];

              if ($year < 1977) 
              {
                  $final = 1977 - $year;
              } 
              
              elseif ($year == 1977) 
              {
                $final = 1977 - $year;
              } 
              
              else 
              {
                $final = $year - 1977;
              }
              
            echo "<p>" . number_format($final) . "</p>";
              
          }
          
?>
```

I run the console and I didn't get data result.

**Comment by AlexandreBonneau** [comment]
As I said, this is out of AutoNumeric scope and so far all evidences points out in a bug in the Php code.

Have you tried checking the content of `$_POST["year"]` before casting it?
What about `$final`?

**Comment by gusbemacbe** [comment]
Yes, I got.

I wrote:

<?php 
          
          if (isset($_POST["year"])) 
          {
              $year = (int)$_POST["year"];
              
              echo $year;
        }
?>

With autoNumeric, I typed 1989, and the result was 1 from `echo $year`. I can see that it is because of separator. I investigated the results in the calculator, I found the exact result.

```
if ($year < 1977) 
{
   $final = 1977 - $year;
} 
```

It understood 1989 as **1.9**89 and 1.9 as 1, and not as exactly 1989, due to the separator. The case found that 1.9 is less than 1977, then subtracted 1977 by 1 = 1976.

**Comment by gusbemacbe** [comment]
I tested without number_format, it gave 11976. I tried to find the result in the calculator.

**Comment by gusbemacbe** [comment]
I fixed it, it wasn't 1196, because I forgot <br>

![screen shot 2017-10-11 at 17 19 47](https://user-images.githubusercontent.com/2257024/31464577-6bb5fa3a-aea8-11e7-94b5-e6846a3f216d.png)

I concluded that it is because of separator (1,989) and not because of PHP and number_format. They understood 1,989 as decimal of 1 and not as exactly 1989.

**Comment by AlexandreBonneau** [comment]
I'm glad to hear you solved your problem!
