### ISSUE TITLE
`allowDecimalPadding` set to `'floats'` when `decimalPlaces` is different from `0` output a warning

### ISSUE THREAD

**Issue by fugafree** [autoNumeric/autoNumeric#509]
### Expected behavior
Not warning when `allowDecimalPadding` and `decimalPlaces` used together because the `allowDecimalPadding` is not overrides the `decimalPlaces` setting.

### Actual behavior
AutoNumeric warnings:
```
Setting 'allowDecimalPadding' to [floats] will override the current 'decimalPlaces*' settings [1, 1 and 1].
```

### Steps to reproduce the problem
1. Using autoNumeric `4.0.3` and the browser `Chrome` version `61.0.3163.100 (Official Build) (64-bit)` on `Windows 10`,
2. I initialized my AutoNumeric object with the call:
```javascript
new AutoNumeric($field.get(0), {
  allowDecimalPadding: 'floats',
  decimalPlaces: 1
})
```

This warning occurs when the `allowDecimalPadding` is set to `false` too.

**Comment by AlexandreBonneau** [comment]
Fixed in `v4.1.0-beta.14`

**Comment by fugafree** [comment]
Hi! Still getting this warning with 4.1.0-beta.15.

**Comment by AlexandreBonneau** [comment]
@fugafree do you have a link that shows the problem?

**Comment by fugafree** [comment]
@AlexandreBonneau I missed the version, sorry. The warning does not appear in beta15.

**Comment by AlexandreBonneau** [comment]
Yay! 🎉
