### ISSUE TITLE
Pasting values in a [disabled=disabled]  element should not be possible

### ISSUE THREAD

**Issue by renandegrandi** [autoNumeric/autoNumeric#510]
### Expected behavior
When an input or no-input is disabled it should not be possible to paste value

### Actual behavior
When we disable an input or no-input element and use the option of (ctrl + c | ctrl + v) I allow you to paste values.

I imagine this would not be a configuration of the component because we can manipulate the element and disable it at any time.

`$(element).prop('disabled', true)`

### Steps to reproduce the problem
1. Using autoNumeric `2.0.13` and the browser `<Chrome|Firefox>` 

### as requested for @AlexandreBonneau a new Issues.

> I guess we could add a new disabled option that would set the disabled attribute on load on the input element.
However since AutoNumeric allows to be used on contenteditable elements, we would have to add some validation rules to check if the user is trying to set that disabled option on a non-input tag.
> Could  you please perhaps create an issue about that new option if you want to see that happen? Thanks.

Source for more details about that problem : https://github.com/autoNumeric/autoNumeric/issues/505

**Comment by AlexandreBonneau** [comment]
Fixed in `4.1.0-beta.23` !
