### ISSUE TITLE
AutoNumeric serialized data return `0` instead of an empty value on empty inputs

### ISSUE THREAD

**Issue by GHim9182** [autoNumeric/autoNumeric#512]
### Expected behavior
When i create a serialized data with autoNumeric functions, if the inputs are empty, i expect that the result must to be with empty string. (ex. amount0=&amount1=150&amount2=)

### Actual behavior
From version 2.0.13, when you create a serialized data, the result contains 0 instead an empty value. 
(If the input is empty)

(ex. amount0=0&amount1=150&...)

With version 1.9.41 there isn't any problem.

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
1. Correct result: https://codepen.io/anon/pen/wrYYjQ (v. 1.9.41)
2. Wrong result: https://codepen.io/anon/pen/pWxxmv (v. 2.0.13)
3. Wrong result: https://codepen.io/AnotherLinuxUser/pen/mBzvRB (v. 4.1.0-beta.9)

Open issue requested from @AlexandreBonneau 

Thanks.

**Comment by AlexandreBonneau** [comment]
This is now fixed in `v4.1.0-beta.11`!
