### ISSUE TITLE
'Del' key does not work in IE browser

### ISSUE THREAD

**Issue by VoimiX** [autoNumeric/autoNumeric#516]
### Expected behavior
Deleted number should be deleted

### Actual behavior
Deleted number appears again in the textbox after losing focus

### Steps to reproduce the problem
1. Using autoNumeric `4.0.3` and `4.1.0-beta.12`   and the browser `IE` version `11` on `Windows`,

2. Initialized my AutoNumeric object with the call:
```js
  var n = new AutoNumeric(lmnt, {
     decimalCharacterAlternative: '&',
     unformatOnSubmit: true,
     digitGroupSeparator: ' ',
     minimumValue: 0,
     modifyValueOnWheel: false,
   });
```

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://jsfiddle.net/qm01xh6v/23/

**Comment by AlexandreBonneau** [comment]
I managed to reproduce the bug in a vm.
`Backspace` works, but `Delete` does not.
