### ISSUE TITLE
Allow changing the `bubble` and `cancelable` attributes of events sent by AutoNumeric

### ISSUE THREAD

**Issue by bkotrys** [autoNumeric/autoNumeric#524]
### Expected behavior
New property in settings `allowEventsBubbles`, which will set event propagation in `AutoNumericHelper.triggerEvent`

### Actual behavior
Current solution has hardcoded `bubbles` in CustomEvent.
```js
static triggerEvent(eventName, element = document, detail = null) {
    let event;
    if (window.CustomEvent) {
        event = new CustomEvent(eventName, { detail, bubbles: false, cancelable: false });
    } else {
        event = document.createEvent('CustomEvent');
        event.initCustomEvent(eventName, true, true, { detail });
    }

    element.dispatchEvent(event);
}
```

**Comment by AlexandreBonneau** [comment]
That, and the fact that if `CustomEvent` exists, we set `bubbles` to `false` while if it does not, we set it to `true`!?!

😕

**Comment by bkotrys** [comment]
natural behaviour of input propagate event upwards on change. Currently we haven't got possibility to do that

**Comment by AlexandreBonneau** [comment]
This is now possible in `v4.1.0-beta.18`!

**Comment by bkotrys** [comment]
@AlexandreBonneau perfect!
