### ISSUE TITLE
Memory / speed improvement in options

### ISSUE THREAD

**Issue by alexturpin** [autoNumeric/autoNumeric#526]
### Description

Our app makes extensive use of AutoNumeric, and depending on the use case, we can have several hundreds of initialized AutoNumeric fields at once. While profiling our app for initial load speed improvements, we noticed that we were spending a lot of time initializing AutoNumeric fields. Further investigation revealed the `get` in `AutoNumeric.options` to be problematic.

Throughout the code, a lot of references are made to `AutoNumeric.options`. Every single one of those references creates a new object on the heap because of the way `AutoNumeric.options` is implemented:

```js
Object.defineProperty(AutoNumeric, 'options', {
    get() {
        return { // New object created every time
            // ...
        };
    }
});
```

This causes the garbage collector to fire a whole lot and makes initializing several hundred fields quite slow.

### Example benchmark

```js
console.time('Initialize 500 fields');
for(var i = 0; i < 500; i++) {
	var input = document.createElement('input');
	input.type = 'text';
	document.body.appendChild(input);
	new AutoNumeric(input);
}
console.timeEnd('Initialize 500 fields');
```

Running the above code results in average times of 1500ms on my machine with Chrome 62. Running the exact same code with a modified version of the library (outlined below) results in an average of 350ms in the same conditions.

### Potential solution
The solution to the slowness is to not create a new object every time `AutoNumeric.options` is called. Modifying the code to look like this does the trick:

```js
Object.defineProperty(AutoNumeric, 'options', {
    value: { // Always same object reference returned
    }
});
```

(I also apply the same fix to `AutoNumeric.predefinedOptions` and `AutoNumeric.defaultSettings`).

The original code might have been written that way as to ensure immutability of the options, but perhaps there is another way to enforce this without returning a new object every time. Maybe through `Object.freeze`? We would rather not have to maintain our own fork but we understand of course if that's not an acceptable change in the name of performance.

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this @alexturpin, performance is an important subject and should be addressed.

Indeed, the idea behind using `Object.defineProperty()` with a getter was to ensure immutability on those *special* objects.

To improve the current situtation, we'll have to:
- Add a performance benchmark in our tests to check for this kind of behavior
- Find another way to preserve the immutability while getting better timings
  - Using `Object.freeze()` or
  - Reusing the same options object across all the AutoNumeric elements in the same page

Thanks for the current workaround for anybody that needs a quick *fix* for the time being.

**Comment by AlexandreBonneau** [comment]
#### The AutoNumeric tests

For info, using this [basic performance test](https://codepen.io/AnotherLinuxUser/pen/rYNMgR?editors=1011) under Linux on `Firefox 56.0b12 (64-bit)` I get on average:
```
Initialize 500 fields: 453.56ms
Initialize 2500 fields: 1925.97ms
```

while using Chromium `61` I get on average:
```
Initialize 500 fields: 836.181884765625ms
[CodePen]: An infinite loop (or a loop taking too long) was detected, so we stopped its execution. Sorry!
Initialize 2500 fields: 3364.429931640625ms
```

#### The non-AutoNumeric tests
For comparison purpose, I created [another test](https://codepen.io/AnotherLinuxUser/pen/JOjbjo?editors=1011) but without initializing any AutoNumeric objects and that take much less time:
Firefox:
```
Initialize 500 fields: 3.61ms
Initialize 2500 fields: 13.09ms
```

Chrome:
```
Initialize 500 fields: 6.64501953125ms
Initialize 2500 fields: 15.09228515625ms
```

#### Conclusion
While I imagine creating on the *same* page hundredths or thousands of AutoNumeric objects is unlikely, it's still interesting to check how this creation process can hinder that page performance.
Those simple benchmarks do show that the AutoNumeric features we take for granted comes at a price, and we should stay vigilant about it.

##### Side notes
- Firefox has ~750 tabs open while Chrome has ~70 ;x
- Firefox is the clear winner here (and I haven't tested with the Quantum version), who would have thought?!

**Comment by AlexandreBonneau** [comment]
For info, using the [first test](https://codepen.io/AnotherLinuxUser/pen/rYNMgR?editors=1011) with `Firefox 61.0b7 (64-bit)`...with 1170 tabs opened, I now get on average:
```
Initialize 500 fields : 542 ms
Initialize 2500 fields : 2360 ms
```

AutoNumeric has seen some changes since last October so that could be the cause. Ideally we should test again with `56.0b12` to be sure, and with the same tabs/configuration, which is unlikely.
