### ISSUE TITLE
Support for passing USD or EUR

### ISSUE THREAD

**Issue by jrock2004** [autoNumeric/autoNumeric#528]
### Expected behavior
Expect the library to switch on currency name instead of just passing the value

### Actual behavior
Just takes what you put in it

### Steps to reproduce the problem
1. Using autoNumeric `4.0.1` and the browser `Chrome` version `62` on `Windows`,
2. I used the options currencySymbol

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://codepen.io/jrock2004/pen/YEyaEV?editors=1010

Thanks for reporting a bug or giving us great ideas with your feature request!

**Comment by AlexandreBonneau** [comment]
Hey @jrock2004, I'm not sure what you are asking here.
Could you please rephrase your question/problem?

I see no problem with the live example you provided.
You can pass the `'USD '` `currencySymbol` like you did, or update it to 'EUR ' on-the-fly with `aNElement.update({ currencySymbol: 'EUR ' })`.

**Comment by AlexandreBonneau** [comment]
I'll close this for now.
If that did not solve your problem, feel free to reopen it!
