### ISSUE TITLE
When enter "," system converted it to ".", I don't want this functionality. can we ignore "," as we are ignoring alphabet. 

### ISSUE THREAD

**Issue by umeshverma** [autoNumeric/autoNumeric#530]
### Expected behavior
<System should ignore "," as it is ignoring alphabet>

### Actual behavior
<System is showing "." when I press "," key>

### Steps to reproduce the problem
1. Please find all the configuration and option in live example.

### Link to live example (https://codepen.io/umesh-ithands/pen/xPRgmy?editors=1111))

Thanks

**Comment by AlexandreBonneau** [comment]
This is a duplicate of issue #432.
