### ISSUE TITLE
How to use by class name selector?

### ISSUE THREAD

**Issue by imredcat** [autoNumeric/autoNumeric#533]
Use 4.1 version,  IE11
I want to set autoNumeric all element by class name, because I have 100 elemets more...
How can I do?

Not work when use class name selector but first element is work.
My code is...
<input type='text' class='money' id='money1'>
<input type='text' class='money' id='money2'>
<input type='text' class='money' id='money3'>
.... 100 elements
<script>
new AutoNumeric(".money"); // Only first element work
// Anyway multiple usage is work well
// AutoNumeric.multiple(["#money1", "#money2", "#money3" .... "#money100"]); // Work all well
</script>

**Comment by AlexandreBonneau** [comment]
Hey @imredcat , the issue tracker is not meant for questions, but for bugs and feature request.

Please use the chat (see [the documentation chapter](https://github.com/autoNumeric/autoNumeric/tree/next#questions) about that).

**Comment by AlexandreBonneau** [comment]
Also, you have answered your own question; if you want to [initialize multiple elements at once](https://github.com/autoNumeric/autoNumeric/tree/next#initialize-multiple-autonumeric-objects-at-once), use the static `AutoNumeric.multiple('.money', options)` function.

It's all in the docs ;)

**Comment by imredcat** [comment]
Thank you.
But I catch an error in Jquery-3.2.1 "The object does not support the 'from' property or method."

**Comment by AlexandreBonneau** [comment]
Can you please provide a [reproducible case](https://codepen.io/pen/) then?
