### ISSUE TITLE
Deprecated option name

### ISSUE THREAD

**Issue by rustam87** [autoNumeric/autoNumeric#534]
### Expected behavior
Correct working in future without warnings and errors

### Actual behavior
browser said me that **"You are using the deprecated option name"**

### Steps to reproduce the problem
1. Using autoNumeric v4.1.0-beta.16 and the browser Chrome version 55 on Linux,
2. I used the options **data-a-sep=" "** in input, in which i will use autonumeric
3. Initialized my AutoNumeric object with the call` new AutoNumeric.multiple('.js-autonumeric');`
4. Then browser said me that **"You are using the deprecated option name"**

 I didn't find in tutorial how i can use data attributes in html for set autonumeric options.
 For example:

`<input type="text" class="js-autonumeric" data-digitgroupseparator=" ">`

That it is possible at all?

Thanks for reporting a bug or giving us great ideas with your feature request!

**Comment by AlexandreBonneau** [comment]
Hey @rustam87, thanks for your interest in AutoNumeric!

However, it took me less time to write a [very small testcase](https://codepen.io/AnotherLinuxUser/pen/EbMRMy?editors=1010) than it took to read your issue, so please create tests case when posting a new issue, thanks!!

The good news is that yes, using the snake case will work as expected (and as before when you used `a-sep` for `aSep`).

The examples from the test case:
```html
<input type="text">
<input type="text" data-currency-symbol="#">
<input type="text" data-digit-group-separator=" ">
```

**Comment by AlexandreBonneau** [comment]
Note: We do not recommend initializing your element like that.

This way of doing it will clutter your html while using a simple CSS class will give you much more flexibility and is more scalable, just sayin' ;)

**Comment by rustam87** [comment]
Thanks.
Why? i have many  inputs with autonumeric, and every input have different properties.
I initialize autonumeric once. Or i add some classes with differents inputs and initialize autoNumeric many times with different params. What is better? Once or more

**Comment by AlexandreBonneau** [comment]
I would go with having different classes and initializing each 'classes'.
