### ISSUE TITLE
Bug when init autoNumeric to span

### ISSUE THREAD

**Issue by guilherme-santos** [autoNumeric/autoNumeric#54]
Hi All,

I found a bug using the follow line:

```
element.autoNumeric('init', {aSep: '.', aDec: ','});
```

In the first set (when runOnce is false) give me wrong result. For example to `123.45` after call that line, I give `12.345,00`

Thanks

**Comment by KanwardeepS** [comment]
Hello All,
I also faced the similar problem integrating the same for my app. As we have our own validators on components, but I the issue could be resolved be adding below lines for my case:
/** allows locale decimal separator to be a comma */
if ((testValue === $this.attr('value') || testValue === $this.text()) && settings.runOnce === false) {
         // value = value.replace(',', '.');
	 **  value = value.split(settings.aSep).join("");
	   value = value.split(settings.aDec).join(settings.aDec);**
 }
![image](https://cloud.githubusercontent.com/assets/12543533/12784114/96f0f2ce-cac8-11e5-92f1-841367b9f249.png)

The solution is specific and agree with Bob, that should not be part of normal version.
Nice work BobKnothe :) :+1:

**Comment by BobKnothe** [comment]
Thank you for your kind words. 

 
Robert (Bob) Knothe
