### ISSUE TITLE
The value of a read-only field can be changed with a scroll input

### ISSUE THREAD

**Issue by dampfklon** [autoNumeric/autoNumeric#541]
### Expected behavior
Read-only field should not be changeable by user input

### Actual behavior
If you focus a read-only field and turn your mouse wheel you can change its value

### Steps to reproduce the problem
1. Using autoNumeric `v4.1.0-beta.20` and the browser `Firefox` version `57.0.4` on `Ubuntu 17.10`,
2. I used the options
`MoneyOptions = { 
                    currencySymbol : '€',
                    currencySymbolPlacement    : AutoNumeric.options.currencySymbolPlacement.suffix,
                    decimalCharacter: ",",
                    decimalCharacterAlternative: ".",
                    digitGroupSeparator: "",
                    minimumValue: "0"
                };
` 
3. Initialized my AutoNumeric object with the call `new AutoNumeric('#oldSaldo', MoneyOptions);`,
4. focus a read-only input field and scoll

### Link to live example
https://codepen.io/dampfklon/pen/zpjvbb

Could be related to #505

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this @dampfklon, it's indeed related to #505.
There you can see the limitation of your end-to-end tests where mouse actions are not automatically tested :/

**Comment by AlexandreBonneau** [comment]
This is fixed in `4.1.0-beta.21`
