### ISSUE TITLE
Can i change autonumeric value without autonumeric methods

### ISSUE THREAD

**Issue by rustam87** [autoNumeric/autoNumeric#545]
### Expected behavior
<Please describe the expected behavior her

i change value in autonumeric input for example
`$('.autonumeric-input').val('')`
input clear
but autonumeric save old data which i entered before
and when i hover mouse on this input i give old value

### Actual behavior
<Please describe what you actually got instead here>
i want if i change value of input(whithout autonumeric methods) i would get actual value

### Steps to reproduce the problem
1. Using autoNumeric `<vX.X.X>` and the browser `<Chrome|Firefox>` version `<YY>` on `<Linux>`,
2. I used the options <{ zzzz: tttt }>, and 
3. Initialized my AutoNumeric object with the call `<new AutoNumeric(domElement, { options })>`,
4. <Then my computer exploded, for real.>

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
<Providing a live example of your problem that reproduce what you are experiencing usually means we'll be able to fix your issue *much more quickly* than if you don't.>
<Also, when creating an extract of your problem, you are likely to find the cause of it, and fix it yourself, :tada: ;)>

https://jsfiddle.net/1jnpxa2a/

1. Enter value
2. Clear input clicking clear button
3. Move mouse  to input element - you see old value

Thanks for reporting a bug or giving us great ideas with your feature request!

**Comment by AlexandreBonneau** [comment]
@rustam87 which version of AutoNumeric are you using?
Can you try with the latest one?

**Comment by rustam87** [comment]
i used this link for jsfiddle https://cdn.jsdelivr.net/npm/autonumeric@4.0.1

**Comment by rustam87** [comment]
i updated plugin to 4.0.3 - analogy situation

**Comment by AlexandreBonneau** [comment]
This is not the place to ask questions, but to report bugs.
You can get in contact with us on gitter (check the readme).

Lastly, if you want to clear your input, why not using the `clear()` [method](https://github.com/autoNumeric/autoNumeric/tree/next#set-get-format-unformat-and-other-usual-autonumeric-functions) provided by AutoNumeric? :)

See the [corrected fiddle](https://jsfiddle.net/bcejpf06/)
