### ISSUE TITLE
I get an error in Angular 4 when initialising autonumeric

### ISSUE THREAD

**Issue by fuyuko-akiyoshi** [autoNumeric/autoNumeric#548]
### Expected behavior
<Please describe the expected behavior here>
Install autonumeric using npm and import in code with import AutoNumeric from 'AutoNumeric' and instantiate autonumeric to work with input fields.

### Actual behavior
I get an error:
AutoNumeric_1.default is not a constructor

### Steps to reproduce the problem
1. Using autoNumeric `<v4.0.1>` and Chrome on both Mac and Windows,
2. I used the options { currencySymbol: '$' }, and 
3. Initialized my AutoNumeric object with the call new AutoNumeric('.autonumeric', { currencySymbol: '$' });,
4. Got this error: AutoNumeric_1.default is not a constructor

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://plnkr.co/edit/oublYED4HrXfyuzKNiNH?p=preview

Please help, I need this in my work. Cheers!

**Comment by AlexandreBonneau** [comment]
Hey @fuyuko-akiyoshi, I do not see that error is the link you provided.

However I see in your `app.ts` source that you do:
```js
import {AutoNumeric} from 'AutoNumeric';
```
while apart if that's a particular typescript notation, it should be:
```js
import AutoNumeric from 'AutoNumeric';
```

Tell us if that worked for you.

**Comment by fuyuko-akiyoshi** [comment]
Hi, thanks for your reply, ok I did that and the error went away, except I'm now getting another error (see console log):

The selector '.autonumeric' did not select any valid DOM element. Please check on which element you called AutoNumeric

Can you let me know what I'm doing wrong in that code?

**Comment by AlexandreBonneau** [comment]
I'm sorry but I still cannot see any error generated by that plunker, so I'm navigating blind.

If you get that error message, it means that AutoNumeric cannot find the `.autonumeric` element when you are calling the constructor.
I'm not an Angular expert but you should check that your component template is created *before* calling `new AutoNumeric('.autonumeric', { currencySymbol: '$' });`.

**Comment by fuyuko-akiyoshi** [comment]
Of course, I hooked it into Angular's OnInit life cycle event and it's working now on the plunkr. I'm still unable to get it working on my local angular project though... it's still giving me the same original error which must mean that angular is not recognising the autonumeric module. I'll have to manually import it in somehow. Thanks for your help!

**Comment by fuyuko-akiyoshi** [comment]
FYI in Angular 4 you need to import AutoNumeric like this:
import * as AutoNumeric from 'AutoNumeric' otherwise it will throw an error. Cheers.

**Comment by AlexandreBonneau** [comment]
Thanks for the tip @fuyuko-akiyoshi !
