### ISSUE TITLE
How to remove .00 ?

### ISSUE THREAD

**Issue by Sandeepindore** [autoNumeric/autoNumeric#549]
### Expected behavior
<Please describe the expected behavior here>

### Actual behavior
<Please describe what you actually got instead here>

### Steps to reproduce the problem
1. Using autoNumeric `<vX.X.X>` and the browser `<Chrome|Firefox>` version `<YY>` on `<Linux>`,
2. I used the options <{ zzzz: tttt }>, and 
3. Initialized my AutoNumeric object with the call `<new AutoNumeric(domElement, { options })>`,
4. <Then my computer exploded, for real.>

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
<Providing a live example of your problem that reproduce what you are experiencing usually means we'll be able to fix your issue *much more quickly* than if you don't.>
<Also, when creating an extract of your problem, you are likely to find the cause of it, and fix it yourself, :tada: ;)>

Thanks for reporting a bug or giving us great ideas with your feature request!

**Comment by AlexandreBonneau** [comment]
Hello @Sandeepindore, you win the prize for creating an issue with the *least* effort given:
- 4 words title
- Did not even cleared the issue template after not following it

Here it is ; 🥇 

;)

However the Github issue management is not used for questions.
As you can see on the [documentation](https://github.com/autoNumeric/autoNumeric#questions), *The issue list of this repository is **exclusively** for bug reports and feature requests.*.
