### ISSUE TITLE
JavaScript function doesnt work when I add Jquery function to the page

### ISSUE THREAD

**Issue by Markowitz1** [autoNumeric/autoNumeric#552]
I need your help. 

https://stackoverflow.com/questions/48762543/javascript-function-doesnt-work-when-i-add-jquery-function-to-the-page?noredirect=1#comment84525636_48762543

**Comment by AlexandreBonneau** [comment]
For the sake of having a coherent and searchable issue base, that would help other identify and find similar problem you have, you need to explain your problem here, without relying on third party website which could close anytime.

I'm closing this issue since I answered you on Stackoverflow.
