### ISSUE TITLE
Webpack bundles the already compiled library when imported in another project

### ISSUE THREAD

**Issue by akarelas-pt** [autoNumeric/autoNumeric#561]
### Current behavior
When using webpack, if we import the library like this: `import AutoNumeric from 'autonumeric'` then build size increases by 1.6MB. To avoid this problem, an increase build size by only ~160kB, we must write `import AutoNumeric from 'autonumeric/src/main.js'`. This is unintuitive, out of the ordinary, and most users will not "guess" that they have to write all this to avoid huge build size. This makes our code uglier.

### Expected behavior
We should only have to write `import AutoNumeric from 'autonumeric'`

### Solution
This can be fixed by simply adding this line to package.json of autonumeric:

`    "module": "src/main.js",`

**Comment by akarelas-pt** [comment]
This trick would help rollup as well, according to this here link: https://rollupjs.org/guide/en#compatibility

**Comment by AlexandreBonneau** [comment]
Some context on the Webpack configuration choices: https://github.com/autoNumeric/autoNumeric/issues/388.

If the goal is to import the smallest library, would it be possible to use the compressed version instead (which is less than 39kB)?

If you plan to build your project with Webpack, the production mode (see Webpack 4 config) will tree-shake, minify and generate a compressed version of your bundle, nullifying the need to import the minified version of AutoNumeric in the first place, or am I missing something?

**Comment by akarelas-pt** [comment]
I didn't understand much in #388.

My goal is not to import the smallest library, but for the output of webpack called "vendor.js" file to be as small as possible. I am not importing the minified version of AutoNumeric as I believe you suggested, but rather src/main.js which is not minified. This still produces quite a small vendor.js file (and minified). But I didn't import a minified file.

Also, I cannot import the .gz file as you suggested, it does not work:

```
import AutoNumeric from 'autonumeric/dist/autoNumeric.min.js.gz';
```

gives me:

```
ERROR in ./node_modules/autonumeric/dist/autoNumeric.min.js.gz
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
```

But in any case, it's not importing a small file that I want, but the size of webpack's output to be small.

PS I use vue-cli with all the default settings, and like many I'd like to keep all its webpack configuration files intact. I found that adding "module": "src/main.js" to autonumeric's config does the trick, and from what I read on the web, it's not something that will only work with vue-cli's webpack, but will work with all webpacks.

**Comment by akarelas-pt** [comment]
PS If you can find a way to further reduce the size of vendor.js file (ie the output of webpack) I'd be happy to try it.

**Comment by akarelas-pt** [comment]
Also, I'm not using Webpack 4 (is that what you asked?) - vue-cli uses Webpack 3 still. I dont' know what would happen with Webpack 4.

**Comment by akarelas-pt** [comment]
i think Webpack 4 is not released yet, isn't that right?

**Comment by AlexandreBonneau** [comment]
The test case for this is the following:
```sh
$ vue init webpack autonum
$ cd autonum
$ yarn add autonumeric
```

Then modify the `HelloWorld.vue` file to this:
```html
<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    <input type="text" id="an" value="111222.45">
  </div>
</template>

<script>
import AutoNumeric from 'autonumeric';

export default {
  name: 'HelloWorld',

  data () {
    return {
      msg: `I'm using AutoNumeric version ${AutoNumeric.version()}`,
      anElement: null,
    };
  },

  mounted() {
    this.anElement = new AutoNumeric('#an', 'euro');
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
```

The run `yarn build`, and instead of seeing:
```
                                   Asset       Size  Chunks                    Chunk Names
static/js/vendor.7b668f9cf4eb33479e01.js    1.66 MB       0  [emitted]  [big]  vendor
```
you'll see that the size is indeed smaller:
```
                                   Asset       Size  Chunks             Chunk Names
static/js/vendor.f0dc8db69b8ead9badde.js     247 kB       0  [emitted]  vendor
```

Lastly you can check that the import works correctly by running `yarn dev`.

Thanks for pointing the problem *and* the solution @akarelas-pt :+1:

**Comment by akarelas-pt** [comment]
Importing 'autonumeric' (or 'autonumeric/src/main.js') doesn't work with Mac Safari 10.1 when building with 'npm run build' in a vue-cli app. It displays blank page, and the console log shows some errors (which I don't remember right now, as I'm not a mac user, but there were two errors, one of which was about 'let'-ting the same variable twice). Importing 'autonumeric/dist/whatever/blabla.min.js) however, works fine, just as importing 'autonumeric/dist/blabla.js' (though that outputs a huge build size) does. Also when the site is run with '`npm run dev`', then again it works fine. It's just `npm run build` that causes problems.

Firefox and Chrome on Mac see the built site perfectly in all cases, though. It's just safari that brings the error.

Question: do you have access to a Mac to try this out? Or should I ask my mac-using friend to take screenshots? Maybe I should create a new issue here on github for this. I think I'll create a minimal case in the evening, post HelloWorld.vue on github like you did, and ask two or three of my mac-using friends to post images and comments.

**Comment by AlexandreBonneau** [comment]
I do not have access to a Mac, so cannot test anything on it yet (I need to [setup browserstack](https://github.com/autoNumeric/autoNumeric/issues/435) one day..).

You can blame Apple for not releasing there browser on other OSes; even Microsoft gives away VMs so you can test on IE/Edge! (As a Linux-only user, that's a plus for AutoNumeric support on that platform)

You can indeed create a new issue since it's a different problem, and post the screenshots there. Let's hope just seeing the error messages will be enough to 'fix' the problem without being able to test the fixes interactively.

A minimal testcase is indeed the way to go, thanks!

**Comment by akarelas-pt** [comment]
Ok, the problem appeared only on some Safari 10 versions (like Safari 10.1). It's due to a bug of Safari, where this line produces an error:

`let e = e => { console.log(e); for (let e of [1, 2, 3]) console.log(e); }`

but in reality there's nothing wrong with this line, so it works fine on all other browsers, and on Safari 11 as well.

I used your component here: https://codesandbox.io/s/mqw84m1qr9

which I published (in minified form) here: https://csb-mqw84m1qr9-fzxnrcdmoa.now.sh/

It's the minified form that doesn't work with Safari 10.1.

Safari's bug was solved here, on May 2017: https://webkit.org/blog/7622/release-notes-for-safari-technology-preview-31/

Our minified projects can support Safari 10.1 by configuring the Uglifier libraries appropriately, as described here: https://github.com/mishoo/UglifyJS2/issues/1753#issuecomment-324814782

I wil try this solution when in the evening. Maybe you want to include this configuration option when you yourself minify autonumeric, so that the resulting dist directory is Safari-10.1 safe? dist currently works with Safari, but it possible it could break in the future.

Anyway, it's not your library's fault after all. I'll write an update in the evening, when I try out all of this.

**Comment by akarelas** [comment]
Adding this to vue-cli's webpack's uglify's config solved the problem: (just like the link above said it would):

mangle: {safari10: true}

That was indeed the problem. I'm repeating the link that shows the problem: https://github.com/mishoo/UglifyJS2/issues/1753#issuecomment-324814782

**Comment by AlexandreBonneau** [comment]
The questions here are:
- What exactly does adding the `mangle: {safari10: true}` option does to the bundle? Does it affects its size/compatibility for other platforms?
- If yes, then do we want to support Safari 10.1 (since apparently it's an old version that has a pretty [small](https://data.apteligent.com/ios/) [marketshare](https://clicky.com/marketshare/global/web-browsers/safari/) as of now; [0.34% according to caniuse](https://caniuse.com/usage-table))
- Does Safari has a self-update like other main browsers (Firefox / Chrome), which will make that problem go away by itself? You were mentioning Safari 11 is not usable on old mac?

**Comment by akarelas** [comment]
I don't know how to answer your questions. I'm trying to recompile my project with & without the mangle: safari10: true option, but it's not changing anything in the dist folder. I don't have a mac to test. Sorry, can't help anymore.

**Comment by akarelas** [comment]
From what I understand by reading a couple of articles on the web, all Sarari 10.x browsers have the problem. Only Safari 11 solves it. There is a verion of OS X that only supports up to Safari 10.x.
