### ISSUE TITLE
The `import AutoNumeric from 'AutoNumeric'` line in the readme does not work on case sensitive OS (like Linux)

### ISSUE THREAD

**Issue by avatxus** [autoNumeric/autoNumeric#563]
### Current behavior
<Please describe here what faulty behavior you are experiencing>

`import AutoNumeric from 'AutoNumeric'` doesn't work in Linux systems, which are case sensitive.
using @angular-cli : error TS2307: Cannot find module 'AutoNumeric'.

It works fine in Windows / Mac as they are case insensitive. The node_modules folder is 'autonumeric',
so in Linux this is broken, since AutoNumeric does not exist.

### Expected behavior

Update the docs to say:
`import AutoNumeric from 'autonumeric'` . This will work in all OS.

**Comment by AlexandreBonneau** [comment]
Whoops my bad, I should know I'm a Linux user :penguin:.

I forgot to change that since in my webpack configuration I'm using an alias:
```js
module.exports = {
    resolve: {
        extensions: ['.js', '.vue', '.json'],
        alias     : {
            '~'          : resolve('node_modules'),
            '@'          : resolve('src'),
            'AutoNumeric': resolve('node_modules/autonumeric/dist/autoNumeric.min'),
        },
    },
   // ...
};
```
