### ISSUE TITLE
Using brackets for negative numbers in AutoNumeric.format returns "undefined"

### ISSUE THREAD

**Issue by maximeromano** [autoNumeric/autoNumeric#568]
### Current behavior
`AutoNumeric.format` returns incorrect results for a negative value when brackets are defined.

For instance, `AutoNumeric.format(-20, AutoNumeric.predefinedOptions.dollarNegBrackets)` should return `($20.00)`, but instead returns `undefined$20.00undefined`.

Both Firefox 60 and Chrome 65 have this behaviour.

### Expected behavior
`AutoNumeric.format(-20, AutoNumeric.predefinedOptions.dollarNegBrackets)` should return `($20.00)`.

### Steps to reproduce the problem
1. Use autoNumeric version `v4.2.8`
2. In the browser `Chrome 65 or Firefox 60` 
3. On the `Windows` operating system
4. Open devel console in any tab that has AutoNumeric loaded.
5. Run `AutoNumeric.format(-20, AutoNumeric.predefinedOptions.dollarNegBrackets)` 

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
[https://codepen.io/anon/pen/XEzJVK](https://codepen.io/anon/pen/XEzJVK)

**Comment by AlexandreBonneau** [comment]
Thanks for reporting that issue @maximeromano.
This is fixed in `v4.2.9`!
