### ISSUE TITLE
Initializing and setting a value on a bunch of fields?

### ISSUE THREAD

**Issue by alexturpin** [autoNumeric/autoNumeric#569]
I'm converting some old AutoNumeric v2 code to v4. The old code looked like this:

```js
$('.lots-of-fields').autoNumeric('init', {...}).autoNumeric('set', 0);
```

So it initializes a bunch of fields and then sets their value to 0. I was trying to figure out if there was a canonical way to do this with AutoNumeric v4. I tried the following

```js
AutoNumeric.multiple('.lots-of-fields').set(0); // Doesn't work because multiple returns an array

AutoNumeric.multiple('.lots-of-fields').global.set(0); // Only sets the first one because multiple doesn't create an init list

AutoNumeric.multiple('.lots-of-fields');
AutoNumeric.set('.lots-of-fields', 0); // Only sets the first one
```

I've resorted to just using a `forEach` to loop through but was wondering, is there any better way to do this in v4? If not, perhaps `multiple` should create an init list?

Cheers

**Comment by alexturpin** [comment]
While I'm at it, I think a static version to get an AutoNumeric object from a DOM element / selector would be highly useful in the case where a static method isn't available. For example, to set options, we could do `AutoNumeric.getDOMElement('#foo').update(...)`.

**Comment by AlexandreBonneau** [comment]
About getting the AutoNumeric object from a DOM element/selector, the [static function](https://github.com/autoNumeric/autoNumeric#static-methods) `getAutoNumericElement()` already exists!

**Comment by AlexandreBonneau** [comment]
As you do not need to set the value *after* having initialized the elements, you can initialize *and* set their value in the same call:
```js
AutoNumeric.multiple('.lots-of-fields', 0);
```

**Comment by alexturpin** [comment]
Thanks so much for the prompt reply as usual Alex. Clearly I need to RTFM better :D

**Comment by AlexandreBonneau** [comment]
No problem Alex ;)
