### ISSUE TITLE
The minified version of AutoNumeric does not expose some of its static functions (ie. `AutoNumeric.getNumber()`)

### ISSUE THREAD

**Issue by alexturpin** [autoNumeric/autoNumeric#570]
The following code:

```
new AutoNumeric('#test');

console.log(AutoNumeric.getNumber('#test'));
```

Works with the latest version of the library through unpkg, but not jsdelivr:
 - unpkg: https://codepen.io/anon/pen/NYLgoJ
 - jsdelivr: https://codepen.io/anon/pen/zWJzbB

With the jsdelivr version, the following error is thrown:

```
Uncaught TypeError: this.getAutoNumericElement(...)[t] is not a function
```

This is in Chrome 65 on Windows 10 x64.

I'm 99% the issue is related to the minification process, seeing as the jsdelivr code is minified and the unpkg code isn't. I am not using a CDN myself as I have my own branch with some changes, but I attempted to use the CDNs to see if it was an issue with my branch and found this weird discrepancy.

**Comment by MartinKolarik** [comment]
The minified version from unpkg doesn't work either, so this is most likely not related to the CDN at all. It's a problem with `dist/autoNumeric.min.js` which comes in the npm package.

**Comment by AlexandreBonneau** [comment]
Indeed @MartinKolarik, it seems the problem arise in the minified version (see the updated codepen [here (unpkg)](https://codepen.io/AnotherLinuxUser/pen/VXGyLQ) and [here (jsdelivr)](https://codepen.io/AnotherLinuxUser/pen/QmVabe)).

**Comment by AlexandreBonneau** [comment]
The problem indeed comes from the minification in those functions:
```js
static _get(domElementOrSelector, getFunction, callback = null) {
    const domElement = AutoNumericHelper.domElement(domElementOrSelector);

    if (!this.isManagedByAutoNumeric(domElement)) {
        AutoNumericHelper.throwError(`Impossible to find an AutoNumeric object for the given DOM element or selector.`);
    }

    return this.getAutoNumericElement(domElement)[getFunction](callback);
}

static getNumber(domElementOrSelector, callback = null) {
    return this._get(domElementOrSelector, AutoNumeric.getNumber.name, callback);
}
```

The `mangle` option does mangle the function name, with `AutoNumeric.getNumber.name` returning `t` in this case.

The solution is to define the `mangle` exception (see [here](https://github.com/mishoo/UglifyJS2/issues/671).

**Comment by alexturpin** [comment]
Note also that the use of `Function.name` breaks in IE. I've updated the three calls to `this._get` to just use the string directly in my fork, e.g.:

```
static getNumber(domElementOrSelector, callback = null) {
    return this._get(domElementOrSelector, 'getNumber', callback);
}
```

**Comment by isherwood** [comment]
This problem seems to still exist. I'm loading 4.5.10 from the CDN. 

> Uncaught TypeError: Cannot read property 'set' of null

This occurs on this line:

`AutoNumeric.getAutoNumericElement(reportEl).set(inputVal);`
