### ISSUE TITLE
format issue with vmax :999999999999 and mDec:9

### ISSUE THREAD

**Issue by puneetshukla** [autoNumeric/autoNumeric#577]
Hello Team,
I am using autonumeric.js 1.9.43 version. I am setting vMax to 12 digit(999999999999) and mDec to 8.
when i am entering the value in the textfield on focus out it roundsoff the value to 5 digit after decimal

For eg: input : 123,456,789,012.12345678 
           output: 123,456,789,012.12346

thanks in advance

**Comment by puneetshukla** [comment]
Hey @AlexandreBonneau , 

thanks for the suggestion, v1.9.43 has been used on big scale in my project  and changing it now would be huge risk. If you could quickly have a look at this version would be a big help

**Comment by AlexandreBonneau** [comment]
Could you not try with `v2.0.13` since this version still uses the old jQuery notation?
This should be transparent in your project (and you can always check your end-to-end tests ;P).

**Comment by AlexandreBonneau** [comment]
What do you mean exactly by 'disabling the rounding'?

If you use `anElement.set(123456789012.12345678)`, and have a `decimalPlaces` set to `5`, you would want to keep in the `rawValue` `123456789012.12345` instead of the current `123456789012.12346` value is that right?

**Comment by AlexandreBonneau** [comment]
Due to inactivity, this issue has been marked for deletion and will be closed in the next few days.
Please give us more information if you feel the problem still affects you.

**Comment by AlexandreBonneau** [comment]
Due to inactivity, I'm closing this issue considering it resolved.
If that's not the case, feel free to re-open it!
