### ISSUE TITLE
Where is the autoNumeric.min.js File

### ISSUE THREAD

**Issue by JacoFourie** [autoNumeric/autoNumeric#581]
Hi. I can only see autoNumeric.js where is the autoNumeric.min.js file ?

**Comment by AlexandreBonneau** [comment]
Hi, we [recommend](https://github.com/autoNumeric/autoNumeric#questions) using our [Gitter chat](https://gitter.im/autoNumeric/autoNumeric) for asking questions.
The Github issue tracker is for bugs and feature requests *only*.

**Comment by JacoFourie** [comment]
@AlexandreBonneau thanks for the info.
