### ISSUE TITLE
Get value with id

### ISSUE THREAD

**Issue by arafsan** [autoNumeric/autoNumeric#586]
Hi,
I have a page where more than one value is entered. Sometimes I have to choose an area in particular. So I have all of the id's in the values, but I did not understand how to get the value of a field with id because I started the automeric with "class". Can you help me ? (Versiyon : 4.1.0)

`var anum = new AutoNumeric.multiple('.money', { currencySymbol : '$' });`

```
<input type="text" id="field1" class="money">
<input type="text" id="field2" class="money">
<input type="text" id="field3" class="money">
```

How do I get the value of the field named "field2"?

Thanks in advance.

**Comment by AlexandreBonneau** [comment]
Hi, thanks for your interest in AutoNumeric, however we [recommend](https://github.com/autoNumeric/autoNumeric#questions) using our [Gitter chat](https://gitter.im/autoNumeric/autoNumeric) for asking questions.
The Github issue tracker is for bugs and feature requests *only*.

**Comment by AlexandreBonneau** [comment]
You can retrieve the value of your second form field using either:
```js
AutoNumeric.getAutoNumericElement('#field2').getNumericString();
```

Or, since you kept a reference to the generated AutoNumeric object, you can use:
```js
anum[1].getNumericString();
```
