### ISSUE TITLE
Option unFormatOnSubmit not works when submitting form from javascript

### ISSUE THREAD

**Issue by minhdanh** [autoNumeric/autoNumeric#588]
### Current behavior
Value not unformatted when submitting form using Javascript. For example:

Script:
```
  //...
  button.click(function(e){
    e.preventDefault();
    form_id = $(this).closest("form").attr('id');
    $('#' + form_id).submit();
    // do other things
  }
```
When I entered the value "100000" in an input, autoNumeric changed it to "100 000". Then I clicked the submit button, I expected the value changed to "100000".

### Expected behavior
The value should be changed to "100000".

### Steps to reproduce the problem
1. Use autoNumeric version `4.2.14`
2. In the browser `Chrome` version `66.0.3359.181`
3. On the `macOS` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
  autoNumericElements = AutoNumeric.multiple('.number-format', {
      allowDecimalPadding: false,
      caretPositionOnFocus: "start",
      createLocalList: false,
      digitGroupSeparator: " ",
      emptyInputBehavior: "null",
      maximumValue: "9999999999999",
      minimumValue: "0",
      unformatOnSubmit: true
  });
```
5.  Then use the following script to submit a form:
```
button.click(function(e){
    e.preventDefault();
    $('#form_1').submit();
    // do other things
  }
```
### Link to live example (ie. [Codepen](http://codepen.io/pen/))

https://codepen.io/mrandersonthomas/pen/eKZvGw

**Comment by AlexandreBonneau** [comment]
The `unformatOnSubmit` option works as expected ; Starting from your codepen, I used only pure JS (no jQuery) and clicking on the 'submit' button [works as expected](https://codepen.io/AnotherLinuxUser/pen/dKMvjv) by unformatting the form inputs before submitting.

I recommend not using jQuery which [does not](https://github.com/autoNumeric/autoNumeric/issues/520) [play well](https://github.com/autoNumeric/autoNumeric/issues/292) [with the](https://github.com/autoNumeric/autoNumeric/issues/247#issuecomment-260171632) [web lately](https://github.com/autoNumeric/autoNumeric/issues/217).

So to solve your problem, I'd recommend [not using jQuery](http://youmightnotneedjquery.com/)!

Feel free to reopen that issue if you think we missed something here.

**Comment by minhdanh** [comment]
I think in my case, `﻿e.preventDefault();` prevents the function `unformatOnSubmit` to work properly although I manually trigger form submission with `$('#form_1').submit();`.

If you're against using jQuery then I think there's nothing to fix here.

**Comment by AlexandreBonneau** [comment]
I'm sorry I was not clear enough: although I think jQuery as less and less reasons to exist anymore with browsers standard support being far better than a few years back, I'm saying the bug you are encountering comes from jQuery, since when you use vanilla Javascript, AutoNumeric `unformatOnSubmit` option works as expected.

I do not have the time to analyze what exactly jQuery does differently with its `submit()` method, but if you want to take a look and provide a 'fix', I'll consider it if that does not complexify our codebase too much.

You can check the `_onFormSubmit()` function [here](https://github.com/autoNumeric/autoNumeric/blob/32502270e285bb89fa689f583b829812025704de/src/AutoNumeric.js#L7199).

**Comment by wesleyi23** [comment]
I know this is closed, but I encountered the same problem.  When calling the submit function of the form, either through vanilla JavaScript or through jQuery, it would not strip out the dollar signs from my numeric form fields.  I was able to get it to work by clicking a hidden submit button as shown in AlexandreBonneau's code pen.

**Comment by Zhigalin** [comment]
@AlexandreBonneau this is not a jquery problem, submit a form (not by clicking but by submitting) with JS and it will fail
