### ISSUE TITLE
Feature request: add an option to use a space character between value and currency symbol

### ISSUE THREAD

**Issue by RomeroMsk** [autoNumeric/autoNumeric#590]
In some locales (e.g. `ru`, `fr`, `he`) the currency format pattern contains a space between the value and the currency symbol. For example: `10 €`. You can use the `Intl.NumberFormat` for checking:

```js
console.log(new Intl.NumberFormat('ru', {style: 'currency', currency: 'EUR'}).format(1111.22));
// Output: 1 111,22 €
```

Would you please implement an option to add a space character (non-breaking space, to be precise) before the currency symbol (or after, when `currencySymbolPlacement` = `'p'`)?

**Comment by AlexandreBonneau** [comment]
Hey @RomeroMsk, you can already do that by either using the [predefined](https://github.com/autoNumeric/autoNumeric#predefined-common-options) [option](http://autonumeric.org/examples) `'euro'`:
```js
new AutoNumeric('#urElement', 'euro');
```

...or customize the [currency symbol](http://autonumeric.org/guide#currencySymbol) by using whichever characters you need in that currency symbol (you are *not* limited to a single character there).

*For info, the `'euro'` predefined option uses `'\u202f€'` [as of now](https://github.com/autoNumeric/autoNumeric/blob/32502270e285bb89fa689f583b829812025704de/src/AutoNumericPredefinedOptions.js#L37).*

**Comment by AlexandreBonneau** [comment]
Also, check the options where the narrow non breaking space and 'normal' non breaking space are [defined](https://github.com/autoNumeric/autoNumeric/blob/32502270e285bb89fa689f583b829812025704de/src/AutoNumericOptions.js#L250).
