### ISSUE TITLE
Mouse click to leave autonumeric field sometime could not fire jquery change event

### ISSUE THREAD

**Issue by marcusy3k** [autoNumeric/autoNumeric#591]
### Current behavior
After editing value on an autoNumeric field, if using **mouse** to click on other place, sometimes it could not fire the **jquery change event** of the input field, I can repeat the same problem in about 1 out of 20 times.

However, it is ok to fire the jquery change event if using keyboard TAB key to leave the field.

I have tried using jQuery v3.2.1 and the latest v3.3.1, the same problem exists.

### Expected behavior
jquery change event is expected to be fired after changing value on an autoNumeric field then leaving the field by clicking other place

### Steps to reproduce the problem
1. Use autoNumeric version `<4.2.15>`
2. In the browser `<Firefox>` version `<60.0.2>` , and `<Chrome>` version `<67.0.3396.87>`
3. On the `<Windows 10>` operating system
4. Then instantiate the autoNumeric object with the following options:
new AutoNumeric(domElement, { options });
5. As in live example below

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://codepen.io/mars2018/pen/xzYXJV

In the example. let's input value 1 and value 2 first, then start testing by changing the value 1, it will calculate value 3 when value 1 is changed.

After editing the value 1, if I use mouse to click the value 2 field (or other places), sometimes it could not fire the jquery change event so the value 3 is unchanged. Please note that it is not happened very time, it happens in about 1 out of 20 times.

While using keyborad TAB to move focus to "value 2 field" after changing "value 1 field", it is always ok.

**Comment by AlexandreBonneau** [comment]
I tried to reproduce the bug you mentioned using Firefox `62.0b3`, and after a hundred try or so, could not see the described behavior.
I was changing the value in input 1, then clicking on the background to blur that input.
Every single time the value in input 3 was correctly updated.

Is this happening with the Codepen or with your 'real' code?

Perhaps it's due to the fact that I'm using Linux and not Windows.

**Comment by marcusy3k** [comment]
Yes, it happens in my real code and the Codepen too, and I just tried it again with the Codepen example, I could still repeat that..., I use Windows and Firefox to test it this time. I know it is quite hard to repeat it because sometime it happens within 10 times, but sometime it won't happens after trying 30 times...

Firstly I put the value 10 in the input 1, and put 1000 in the input 2, then change the input 1 value and use the mouse to click anywhere outside the input-box to leave the input-box focus, then change the input 1 value again.... it seems it is easier to repeat it if I put 2 digits (10, 20, 30, 40, ...) everytime instead of single digit.

btw, I am using the autonumeric ver. 2 so far because it seems it don't have the case, but I still wish the latest one is ok too.

**Comment by AlexandreBonneau** [comment]
I'd be curious if anybody else can reproduce that behavior consitently

**Comment by AlexandreBonneau** [comment]
Well, I changed the code to ditch jQuery and so far it works perfectly as intended (see the [updated codepen](https://codepen.io/AnotherLinuxUser/pen/xzMjwJ?editors=1010)).

I feel like I'm repeating myself, but jQuery events are bugged and cannot be relied on correctly.
This is [not](https://github.com/autoNumeric/autoNumeric/issues/520#issuecomment-338779405) [the](https://github.com/autoNumeric/autoNumeric/issues/292) [first](https://github.com/autoNumeric/autoNumeric/issues/247#issuecomment-260171632) [time](https://github.com/autoNumeric/autoNumeric/issues/217) it happens, and anyway [you might not need jQuery](http://youmightnotneedjquery.com/) :)

For the time being I'll close that issue. Feel free to reopen it if you think this might also affect users that do not use jQuery.

**Comment by marcusy3k** [comment]
Thanks, AlexandreBonneau, I have tried your updated codepen, it works perfectly, I don't find it happen again, yes, I would use your way to handle the data changes.

**Comment by MatiasBordoy** [comment]
Hi, its happening to me the same thing.

I have discovered that it's happening when you select(higlight) the value in the input, and then CLICK outside the input. If you do that, the change event is not firing.

If i dont select the value and click outside it works well.
If you press tab, it always work well.

**Comment by AlexandreBonneau** [comment]
@MatiasBordoy Using the codepen I mentioned in my last comment, I cannot reproduce what you are describing.
Could you please describe *precisely* how you get which error?

**Comment by MatiasBordoy** [comment]
Hi Alexandre, i updated my autonumerics.js to the last version and the error was gone.
I thought i had the last version.

Thanks for your response.
