### ISSUE TITLE
Currency at wrong position for empty fields with euro/french preset after typing minus sign

### ISSUE THREAD

**Issue by sbusch** [autoNumeric/autoNumeric#594]
### Current behavior

When toggling the sign in an empty autoNumeric `<input>` using a preset similar to french() (aka. euro()) via typing - (minus char), the currency is displayed on the wrong side = not as a suffix:

`_€-|` 

Notes: `_` denotes the space char before the euro sign, `|` denotes the cursor position.

The order is correct for empty field when initially focused, and after the first digit had been entered.

### Expected behavior

`-|_€`

### Steps to reproduce the problem

See [live example on CodeSandbox](https://codesandbox.io/s/k5030xl085)

**Comment by AlexandreBonneau** [comment]
Fixed in `v4.3.7`.

While the fix is only a few lines of code, I'm ashamed to say I spent quite a lot of time finding where that sneaky bug was lurking!

**Comment by AlexandreBonneau** [comment]
Also, I just saw that I already self-reported that issue in March in issue #565 !
Well, two for one then ;P
