### ISSUE TITLE
Issue working with onChange/onInput

### ISSUE THREAD

**Issue by nanomag** [autoNumeric/autoNumeric#595]
Hi everyone,

Right now, I'm trying to trigger an event when the first valid char of the input (with autonumeric) is entered. onBlur only allows me to trigger it after I focus out the input and onChange/onInput does not work.

Is there a way to listen when each char that's entered in the input?

Thanks!

**Comment by AlexandreBonneau** [comment]
Hi, we [recommend](https://github.com/autoNumeric/autoNumeric#questions) using our [Gitter chat](https://gitter.im/autoNumeric/autoNumeric) for asking questions.
The Github issue tracker is for bugs and feature requests *only*.

**Comment by AlexandreBonneau** [comment]
For info, check the [events](https://github.com/autoNumeric/autoNumeric#event-lifecycle) chapter in the documentation.
You can use `input` or `autoNumeric:rawValueModified` if you want to only react when the `rawValue` is effectively modified.
