### ISSUE TITLE
Option unFormatOnSubmit not works when submitting form  with ajax

### ISSUE THREAD

**Issue by rihabbs** [autoNumeric/autoNumeric#597]
Value not unformatted when submitting form using Ajax. 
 example:
`  $.ajax({
                    type: 'POST',
                    url: '/assets/add',
                    data: $('#addForm').serialize(),
                    success: function (response) {
                                     },
                    error: function (response) {
                    },
                }) `
When I entered the value "500000" in an input, autoNumeric changed it to "500.000€". Then I clicked the submit button, I expected the value changed to  500000.
### Current behavior
<Please describe here what faulty behavior you are experiencing>

### Expected behavior
<Please describe here the expected behavior>

### Steps to reproduce the problem
1. Use autoNumeric version 4.1.0
2. In the browser `<Chrome>` version `< 50.0.2661.102 (64-bit)>`
3. On the `<Linux>` operating system
4. Then instantiate the autoNumeric object with the following options:
`  $('.inputCurency1').each(function(){
        new AutoNumeric($(this).get(0)).french({
            currencySymbol : '€',
            unformatOnSubmit:true,
            formatOnPageLoad:true

        });
    }); `
5. <Then my computer exploded, for real.>
`  $.ajax({
                    type: 'POST',
                    url: '/assets/add',
                    data: $('#addForm').serialize(),
                    success: function (response) {
                                     },
                    error: function (response) {
                    },
                }) `

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this issue, however with the few information you gave us, we are not able to correctly reproduce it.
Could you please create a [reproducible test case](https://codepen.io/pen/) so we can fix your bug?

**Comment by AlexandreBonneau** [comment]
Also, could you try using the latest AutoNumeric version?
I'm betting this is due to a jQuery problem ; please try submitting your form using pure JS too.

**Comment by AlexandreBonneau** [comment]
Due to inactivity, this issue has been marked for deletion and will be closed in the next few days.
Please give us more information if you feel the problem still affects you.

**Comment by AlexandreBonneau** [comment]
Due to inactivity, I'm closing this issue considering it resolved.
If that's not the case, feel free to re-open it!
