### ISSUE TITLE
The `unformatOnHover` config value isn't used when set to `false`

### ISSUE THREAD

**Issue by abejfehr** [autoNumeric/autoNumeric#598]
### Current behavior
In Firefox Nightly (currently 63.0a1) I'm not able to use the `unformatOnHover: false` option, I have no idea if this is not browser specific.

### Expected behavior
I expect that when I press the `alt` key with that setting enabled that the number doesn't unformat.

### Steps to reproduce the problem
1. Use autoNumeric version that's used on autonumeric.org
2. In the browser `Firefox` version `63.0a1`
3. On the `Mac OS` operating system `10.12.6`
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric(domElement, { unformatOnHover: false });
```
5. Text is not unformatted when `alt` is pressed while hovering over the input.

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
I have a recording of it happening in the autonumeric.org site:
![kapture 2018-08-13 at 17 49 06](https://user-images.githubusercontent.com/3917428/44060143-a9b4dec2-9f21-11e8-8c4b-7ca617434df7.gif)

**Comment by AlexandreBonneau** [comment]
This is also happening on Firefox 62.0b16 and Chromium 67.

**Comment by AlexandreBonneau** [comment]
Fixed in `v4.4.3`
