### ISSUE TITLE
Symbol always shows on mouseover

### ISSUE THREAD

**Issue by abejfehr** [autoNumeric/autoNumeric#601]
It may be intentional that this can't be disabled via config, but I _really thought_ `symbolWhenUnfocused: ''` would hide the symbol on mouseover as well.

### Current behavior
With `symbolWhenUnfocused: ''`, the `currencySymbol` shows up when mousing over the element.

### Expected behavior
I would like the option (presumably the config option tested) to disable that behaviour.

### Steps to reproduce the problem
1. Use autoNumeric version from the website
2. In the browser `Chrome` version `68.0.3440.106`
3. On the `macOS` operating system version `10.12.6`
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric(domElement, {
  currencySymbol: '$',
  symbolWhenUnfocused: '',
});
```
5. The currency symbol ($) shows on mouseover.

### Demo of issue

![kapture 2018-08-29 at 4 03 58](https://user-images.githubusercontent.com/3917428/44747882-575c6480-aadc-11e8-9b5b-91f2b6f14970.gif)

**Comment by AlexandreBonneau** [comment]
The option name is 'symbol when *unfocused*'.
A focused element is when the caret appears in it if you will. The event your are sending here are `mouseover`, not `focus`.

Moreover, this option does not manage showing/hiding the `currencySymbol`, but another additional symbol.
You can test this using those options:
```js
{
    currencySymbol: "$",
    symbolWhenUnfocused: "%",
}
```
and typing the value `42` in the input element.
Then if you mouseover that element, you'll see the '%' appear/disappear as intended.

If you want to display no currency symbol on hover, check the `emptyInputBehavior` option like so:
```js
{
    currencySymbol: "₢",
    emptyInputBehavior: "press",
}
```
