### ISSUE TITLE
Module file contains ES6 syntax that breaks in IE11

### ISSUE THREAD

**Issue by alexturpin** [autoNumeric/autoNumeric#604]
When importing AutoNumeric in conjunction with a module bundler with the import syntax, like so

```
import AutoNumeric from 'autonumeric'
```

The file that ends up being imported is the one specified by `main` in package.json. In this case, it's `dist/autoNumeric.js`. That file, however, contains ES6 syntax not supported by IE11 (notably, the arrow function `=>`).

Most people choose to not run Babel on `node_modules` contents as this severely slows down builds and can even cause problems. As such, it has become common practice to transpile to ES5 compatible code the module file that will be included. [One such discussion on StackOverflow](https://stackoverflow.com/questions/29738381/how-to-publish-a-module-written-in-es6-to-npm).

An alternate solution in the meantime is to instead do:

```
import AutoNumeric from 'autonumeric/dist/autoNumeric.min';
```

To import the minified version which seems to be generated using only ES5 code.

I'm using the latest AutoNumeric version, 4.4.0.

**Comment by AlexandreBonneau** [comment]
All files in `dist/` should be in ES5 as they are both compiled with Babel, one being minified.
I do see the `=>` characters in the un-minified version, however just to be sure I ran [es-check](https://www.npmjs.com/package/es-check#get-started):

```sh
npm i es-check --save-dev
./node_modules/.bin/es-check es5 dist/*.js
```
and it returns `ES-Check: there were no ES version matching errors!  🎉`

This is confusing.

What error exactly are you seeing under IE11?

**Comment by AlexandreBonneau** [comment]
I'm not sure why it wouldn't transpile the dev version (`autoNumeric.js`) into es5 while it would correctly transpile the prod version (`autoNumeric.min.js`).

If you check the webpack dev configuration https://github.com/autoNumeric/autoNumeric/blob/423f7c03ab73096c249a84e285f53305e0e05734/config/webpack.config.dev.js#L8
You can see that it include the webpack base configuration (exactly like the [prod version does](https://github.com/autoNumeric/autoNumeric/blob/423f7c03ab73096c249a84e285f53305e0e05734/config/webpack.config.prd.js#L14)), which in turn activate babel:
https://github.com/autoNumeric/autoNumeric/blob/423f7c03ab73096c249a84e285f53305e0e05734/config/webpack.config.base.js#L17

Both the dev and prod version should be transpiled in es5.

**Comment by AlexandreBonneau** [comment]
Ok so I triple checked, and the `=>` characters you see in `autoNumeric.js` are only ever used in comments (which are stripped in the minified version).

So it appears `es-check` is correct ; What error message(s) exactly are you seeing under IE11?

**Comment by alexturpin** [comment]
Thanks for checking Alex!

I didn't know about `es-check`, cool tool! I'm getting the same results as you when I run it.


However, if I check manually, I can see arrow functions being used outside of comments. One such example is at line 92, column 96228

**Comment by alexturpin** [comment]
Thanks for taking the time to check. I didn't know about `es-check`, neat tool. I'm getting the same results as you; my bad, I had assumed seeing the arrow functions that they were the problem but they do indeed seem to all be commented out.

IE11 doesn't give a very useful error unfortunately; it looks like that:

> SCRIPT1002: Syntax error
> app.bundle.js (210,1)

And line 210 of app.bundle.js is the Webpack `eval` for `src/AutoNumeric.js`:

```
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"default...
```

It seems as if IE11 doesn't indicate a character where the error is happening for `eval`. I tried extracting the code out of the `eval` but can't get it to have a syntax error in that context. I will keep digging, sorry about that.

**Comment by alexturpin** [comment]
I did some more digging, and I apologize, it turns out I was 100% wrong about pretty much everything I said.

Files in `dist` are in fact all ES5. I was however actually getting ES6 AutoNumeric files in my bundle. That's due to Webpack's [`resolve.mainFields`](https://webpack.js.org/configuration/resolve/#resolve-mainfields) defaulting to `['browser', 'module', 'main']`. AutoNumeric has no `browser` field but it does have a `module` one, which correctly points to the original ES6 code. I changed my `mainFields` config to instead be `['browser', 'module', 'main']` and all my problems are solved.

I would make the recommendation that `browser` be used instead of `main`. As per [npm's `browser` docs](https://docs.npmjs.com/files/package.json#browser):

> If your module is meant to be used client-side the browser field should be used instead of the main field. This is helpful to hint users that it might rely on primitives that aren't available in Node.js modules. (e.g. window)

Thanks again for your help and sorry for the false alarm!

**Comment by AlexandreBonneau** [comment]
No problem @alexturpin, I've discovered `es-check` myself yesterday while trying to check the validity of the Babel build, so reporting issues, even invalid ones can help too :)

Also, thanks for the `mainFields` documentation, I missed that `browser` subtlety.

**Comment by AlexandreBonneau** [comment]
For info, the latest `v4.4.1` uses `browser` instead of `main` now.
