### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by DanielRuf** [autoNumeric/autoNumeric#606]
### Current behavior
<Please describe here what faulty behavior you are experiencing>
Currently the repo is about 6MB in size as there are some files in the history which should not have been there.

```
fg --strip-blobs-bigger-than 1M autoNumeric  

Using repo : /Users/druf/projects/autoNumeric/.git

Scanning packfile for large blobs: 4016
Scanning packfile for large blobs completed in 77 ms.
Found 10 blob ids for large blobs - biggest=1713492 smallest=1398212
Total size (unpacked)=15512126
Found 38 objects to protect
Found 10 tag-pointing refs : refs/tags/1.9.46, refs/tags/v1.9.31, refs/tags/v1.9.32, ...
Found 166 commit-pointing refs : HEAD, refs/heads/next, refs/heads/tests/test-nodejs-10, ...

Protected commits
-----------------

These are your protected commits, and so their contents will NOT be altered:

 * commit aaf4b3a1 (protected by 'HEAD')

Cleaning
--------

Found 807 commits
Cleaning commits:       100% (807/807)
Cleaning commits completed in 519 ms.

Updating 39 Refs
----------------

	Ref                                        Before     After   
	--------------------------------------------------------------
	refs/heads/next                          | 423f7c03 | fbcf14e7
	refs/heads/tests/test-nodejs-10          | aaf4b3a1 | fe348e6f
	refs/remotes/origin/autoNumeric-567      | 55301c12 | b581b9e9
	refs/remotes/origin/master               | 239062f4 | d02d8fc6
	refs/remotes/origin/next                 | 423f7c03 | fbcf14e7
	refs/remotes/origin/tests/test-nodejs-10 | aaf4b3a1 | fe348e6f
	refs/tags/v4.0.0                         | 58ac36ac | 1c3739aa
	refs/tags/v4.0.1                         | 99de3c16 | b4ec1c3b
	refs/tags/v4.0.2                         | 9fef99db | a7a40273
	refs/tags/v4.0.3                         | ff48f13e | 7186de04
	refs/tags/v4.1.0                         | 5fb2496f | cffcf62b
	refs/tags/v4.1.1                         | 4f3e5578 | c30d83bc
	refs/tags/v4.1.2                         | 65f369c1 | 61eba00d
	refs/tags/v4.1.3                         | 393fcc9b | e755093b
	refs/tags/v4.2.0                         | 239062f4 | d02d8fc6
	...

Updating references:    100% (39/39)
...Ref update completed in 50 ms.

Commit Tree-Dirt History
------------------------

	Earliest                                              Latest
	|                                                          |
	..............................................DDDD..DDDDDmmm

	D = dirty commits (file tree fixed)
	m = modified commits (commit message or parents changed)
	. = clean commits (no changes to file tree)

	                        Before     After   
	-------------------------------------------
	First modified commit | 58ac36ac | 1c3739aa
	Last dirty commit     | af245233 | 71fbb1e4

Deleted files
-------------

	Filename                 Git id                                   
	------------------------------------------------------------------
	autoNumeric.js         | e2ceb867 (1,6 MB), d69539a9 (1,6 MB), ...
	autoNumeric.min.js.map | 9dc7018e (1,3 MB), 79cf70e4 (1,4 MB), ...


In total, 201 object ids were changed. Full details are logged here:

	/Users/druf/projects/autoNumeric.bfg-report/2018-09-13/08-30-01

BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive

```

deleted files:
```
3ec8b735a4803c57f924c5d01d2213374b9c49cc 1568645 autoNumeric.js
d69539a98c17abcd3e64dfb8ee8886231cb1a912 1706974 autoNumeric.js
6efa06a1e9669254db56f8cf9635e83eff15a79c 1709944 autoNumeric.js
e2ceb867d1ef92d5a13f5867e3c4c94b62068f57 1713492 autoNumeric.js
1d4a0776987c71933d1e700fcb93956be6bc9381 1713388 autoNumeric.js
79cf70e44cbf47a013cdc90637db0461320b43d1 1494031 autoNumeric.min.js.map
6fe7b2fc7b76c66cba3fd9d45a8755b491202c04 1403362 autoNumeric.min.js.map
9dc7018e255576e4d2fb32901fc219d46bc3f95c 1398212 autoNumeric.min.js.map
37cd6091e329957bb8e871c6dfeeb289da7c195a 1400640 autoNumeric.min.js.map
016e36f774fb318cccaf353199d658c9eac129bd 1403438 autoNumeric.min.js.map
```

**Comment by AlexandreBonneau** [comment]
Well this is interesting!

Since [last February](https://github.com/autoNumeric/autoNumeric/commit/cb4a5ad09edac2b757584f45309dcc4f6f5c81e2), we decided to not add any generated files (from `dist/`) into the repository anymore, since those are automatically generated by the CI server.

Although it's tempting to clear all previously saved `dist/*` files (and not only the `.js` and `.js.map` ones), I'm having doubts about changing the repository history.
Do you guys think it would be ok to 'lose' that information?

Moreover, is it possible with `bfg` to remove all `dist/*` files, and not only the bigger files?

**Comment by DanielRuf** [comment]
> Well this is interesting!
> 
> Since [last February](https://github.com/autoNumeric/autoNumeric/commit/cb4a5ad09edac2b757584f45309dcc4f6f5c81e2), we decided to not add any generated files (from `dist/`) into the repository anymore, since those are automatically generated by the CI server.

Well, what once was in the history stays in the history (you can travel back with git checkout). So without rewriting commits (push -f) and without a clean new branch we can not "fix" this.

**Comment by DanielRuf** [comment]
In general we can not do this on the current branches without rebasing all related PRs and possibly forks which have to pull (-f) the new and changed history.

**Comment by AlexandreBonneau** [comment]
[Bfg](https://rtyley.github.io/bfg-repo-cleaner/) or [git-filter-branch](https://git-scm.com/docs/git-filter-branch) both looks to have a pretty heavy impact on the repository, changing all the commit hashes for instance (and what about all those gpg-signed ones?), making any previously cloned repo invalid, which could lead to weird errors if those having such repo forgot to delete it before pushing changes.

I'm not sure the benefit outweigh the cost or rewriting history.
So, would you agree to put this on hold until more people voice their opinion about that here?

**Comment by DanielRuf** [comment]
This is what git rebase or a change in history always does, rewrite the commits / history after the changed commit, so this is expected and correct and how Git works.

**Comment by DanielRuf** [comment]
Let's put it on hold for now.
