### ISSUE TITLE
Uncaught Error: Cannot find module 'autonumeric' on v4.4.1

### ISSUE THREAD

**Issue by g3rrydanc3** [autoNumeric/autoNumeric#609]
### Current behavior
Uncaught Error: Cannot find module 'autonumeric' on v4.4.1
**It doesn't break on v4.4.0**

### Steps to reproduce the problem
1. Use autoNumeric version `<v4.4.1>`
2. In the electron version `<2.0.9>`
3. On the `<Windows>` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
const AutoNumeric = require( 'autonumeric' );
```
5. 
```js
<Uncaught Error: Cannot find module 'autonumeric'
    at Module._resolveFilename (module.js:543)
    at Function.Module._resolveFilename (D:\Github\tirta-jaya\pembukuan\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35)
    at Function.Module._load (module.js:473)
    at Module.require (module.js:586)
    at require (internal/module.js:11)
    at render.js:16
```

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this @g3rrydanc3.

I was a bit worried changing the `main` to `browser` info in the package.json could not be correctly supported by third party tools, I unfortunately I was right.

Oh well, I'll revert https://github.com/autoNumeric/autoNumeric/commit/59f4057dc0a858c51af7c266fdac39e1fc5d4f12 ([sorry](https://github.com/autoNumeric/autoNumeric/issues/604#issuecomment-420921293) @alexturpin ;P)

**Comment by AlexandreBonneau** [comment]
This should be fixed in `4.4.2`

**Comment by alexturpin** [comment]
@AlexandreBonneau in this case I would recommend we include both `main` and `browser` if you want to support browsers _and_ Node.js, after which it should work properly for both. Reverting https://github.com/autoNumeric/autoNumeric/commit/59f4057dc0a858c51af7c266fdac39e1fc5d4f12 and removing `browser` will include original ES6 code for people who haven't configured Webpack or other properly.

**Comment by AlexandreBonneau** [comment]
@g3rrydanc3 could you please try the temporary `v4.4.3` version (not pushed to npm yet) on that branch : https://github.com/autoNumeric/autoNumeric/tree/fix_packagejson_browser_main

I'd like to be sure adding the `browser` field alongside the `package.json`'s `main` one does not break your setup.

**Comment by AlexandreBonneau** [comment]
@g3rrydanc3 my bad, when I wrote my comment about trying the `v4.4.3`, there was only the temporary `v4.4.3` created into the `fix_packagejson_browser_main` branch.

But soon after, I fixed another issue and uploaded the *real* `v4.4.3` (which has nothing to do with the current issue).

Could you please tell me if you tested with the `fix_packagejson_browser_main` branch?
Thank you and sorry for the inconvenience

**Comment by AlexandreBonneau** [comment]
@g3rrydanc3 ping! :sunglasses:

**Comment by g3rrydanc3** [comment]
**Step to test**
> git clone -b fix_packagejson_browser_main https://github.com/autoNumeric/autoNumeric.git
> cd autoNumeric
> yarn install
> yarn build

Copy `package.json` and `dist/autoNumeric.js` from autoNumeric project
to `node_modules/autonumeric` in my electron project

![capture](https://user-images.githubusercontent.com/1871841/46408714-3b805a00-c73d-11e8-90c8-f7890b8afe41.PNG)

Is this correct?

**Comment by AlexandreBonneau** [comment]
Those steps are ok if your project uses the unminified `autoNumeric.js` file.
However if it were using the minified one, you ought to copy `autoNumeric.min.js` as well.

**Comment by AlexandreBonneau** [comment]
If that's ok with you @g3rrydanc3, I'll merge the change into `next`.

**Comment by g3rrydanc3** [comment]
Yes, it works as expected.

**Comment by AlexandreBonneau** [comment]
Thanks!

**Comment by AlexandreBonneau** [comment]
This is pushed in `v4.5.0`
