### ISSUE TITLE
Would the set() method trigger the change event?

### ISSUE THREAD

**Issue by marcusy3k** [autoNumeric/autoNumeric#613]
Would the set() method trigger the change event? if not, how could I ask the set() to trigger the according change event?

Thanks

**Comment by AlexandreBonneau** [comment]
Hi, we [recommend](https://github.com/autoNumeric/autoNumeric#questions) using our [Gitter chat](https://gitter.im/autoNumeric/autoNumeric) for asking questions.
The Github issue tracker is for bugs and feature requests *only*.

**Comment by AlexandreBonneau** [comment]
Do note that using `set()` will indeed dispatch the `change` event...[IF](https://github.com/autoNumeric/autoNumeric/blob/3860e2036e3c99256ef714920f70f7a415d30d61/src/AutoNumeric.js#L6355) the `rawValue` is modified.
