### ISSUE TITLE
Auto Numeric support for Hours HH:mm (basic hours and mins)

### ISSUE THREAD

**Issue by papyr** [autoNumeric/autoNumeric#616]
Hello, hours and mins are no diff than currency, it would be nice to have this also apply to hours and mins. for e.g. inside a timesheet where people are entering the hours/ time they worked

**Comment by AlexandreBonneau** [comment]
Hello @papyr, thanks for your contribution.
I feel that this feature request is out of scope of AutoNumeric, in regards that the library's goal is to manage entering numbers and currencies *(and that AutoNumeric is pretty thorough as of now)*.

With this we would stray far from that goal, by having to manage another set of *complex* data ; implementing this behavior would seem pretty easy (only ever accepts numeric characters with a simple enough mask), however you'd have to take into accound value constraints (do you accept hours > 24? 12? What if a user enter 78 minutes? Do you add to the hours?).

I think this feature would be better implemented by the dev who would better know its needs, or in a specific library.

I'll set aside this feature request for now, and if @BobKnothe wants to chip in, perhaps we could discuss it further.
