### ISSUE TITLE
Update value of element [to close]

### ISSUE THREAD

**Issue by vince83110** [autoNumeric/autoNumeric#617]
### Current behavior
I use AutoNumeric with a global call : 

```js
    // set autonumeric
    AutoNumeric.multiple('.autonumeric', AutoNumericConfig);
    AutoNumeric.multiple('.autonumeric-number', AutoNumericConfigDecimal);
    AutoNumeric.multiple('.autonumeric-integer', AutoNumeric.getPredefinedOptions().integerPos);
```

It works, but I load some data through Ajax, and I need to set the value to the AutoNumeric elements. Since I don't have variable (because I use multiple selectors), I tried to initialize again after Ajax response : 

```js
$.getJSON(urlProduct, function(data) {
                    // fetch form
                    $.each(data.product, function(key, value) {
                        var ctrl = $('[name='+ key +']', $form);
                        switch(key) {
                            case 'price_portion':
                            case 'price_reference':
                                var element = new AutoNumeric(ctrl[0], AutoNumericConfig);
                                element.set(value);
                                break;
                            case 'portion':
                                var element = new AutoNumeric(ctrl[0], AutoNumericConfigDecimal);
                                element.set(value);
                                break;
                         ....
```

The problem is : it doubles numbers when I write in input. If I press "2", I have "22" in my input.
I just want to be sure it's possible before moving to another plugin.

### Expected behavior
I just want to set a value with multiple selectors, I don't want to define a variable for each of my input.

_To be simple, can I use AutoNumeric functions using only the DOM element ? and not the variable you get after Initialization ?_

### Steps to reproduce the problem
1. autoNumeric version `<v4.4.1>`

### EDIT

Ok, I missed `getAutoNumericElement` in doc, sorry !

**Comment by AlexandreBonneau** [comment]
Hi @vince83110, there are a few points to review here.

First, when you use `AutoNumeric.multiple()`, you **can** retrieve references to the generated AutoNumeric elements (see [the related chapter in the doc](https://github.com/autoNumeric/autoNumeric/#initialize-multiple-autonumeric-objects-at-once)) : `AutoNumeric.multiple()` returns an array of the generated AutoNumeric objects.

Given that you can keep a reference to the generated elements, you will then be able to modify your script to use `anElement.set(theNewValue)` to update your elements value.

Secondly, if you want to be able to set the value of an input which has been initialized by AutoNumeric, but you did not keep the reference to the AutoNumeric object, you can as you mentioned either use:
```js
AutoNumeric.getAutoNumericElement(domElement).set(newValue);
```
...or just set the value directly with the static function:
```js
AutoNumeric.set(domElement, newValue); // or AutoNumeric.set('#theInput', 42)
```


Lastly, you've raised a interesting concern ; currently AutoNumeric allows you to initialize the same DOM element multiple times, while it should not. We should test if the given DOM element already has an AutoNumeric object attached to it, and just reset its states (history, default format and value, etc.) when initializing it a second time. That, or raise a meaningful error message ie `The DOM element is already initialized`.

**Comment by pms07** [comment]
@vince83110 
Hey,
Can you share how you used particular **`getAutoNumericElement`** It will be super helpful.
I am stuck with the same problem. 

I am able to init the autonumeric to multiple fields with class selector, but When dynamically table row is added I am getting same issue for doubling the input fields.

I am adding new table row by copying existing table row. and used Autonumeric.multiple(...) with class selection.

#770  - here i have provided more details of the occurance.
