### ISSUE TITLE
ShowWarnings option is not working

### ISSUE THREAD

**Issue by varunet** [autoNumeric/autoNumeric#619]
### Current behavior
`showWarnings` when set to `false`, still shows errors. 

### Expected behavior
`showWarnings` when set to `false` should hide all errors from AutoNumeric and should not throw errors. 
errors are not required for production. 

### Steps to reproduce the problem
1. Use autoNumeric version `4.5.1`
2. In the browser `Chrome` version `64`
3. On the `windows` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
options = {
    minimumValue: 100,
    maximumValue: 2000,
    decimalPlaces: 0,
    showWarnings: false
 };
new AutoNumeric(domElement, { options });
```
5. Copy paste amount not within the range. i.e. Copy paste `5000` into the text input. 

### Link to live example 
https://stackblitz.com/edit/angular-itx6qp

**Comment by AlexandreBonneau** [comment]
The `showWarnings` option disables warnings, not errors.

There is currently no way to hide errors, and some warnings are always displayed (the ones which are pretty important for being able to use AutoNumeric correctly, for instance when the init fails: `No valid DOM elements were given hence no AutoNumeric object were instantiated.`).

Should we add a `disableAllWarningsAndErrors` option for production mode? I'm not sure.
Wouldn't you want your tech savvy users that browse your website with the console open to spot why some actions are not working as they are supposed to?

**Comment by varunet** [comment]
it seems fine for DOM element instantiation. But for values being outside the range surely falls into low priority error, maybe there is a level of errors and you could use that to control the production environment.

**Comment by AlexandreBonneau** [comment]
We currently have 100+ matches for `throwError(` in the code.
Adding an error level would need to review each of those error and weigh them. This seems like an overkill solution.

Have you checked the [`onInvalidPaste`](http://autonumeric.org/guide#onInvalidPaste) option?
In your context, could you use the `ignore` value that *fails silently without outputting any error/warning in the console* ?

**Comment by AlexandreBonneau** [comment]
Due to inactivity, I'm closing this issue considering it resolved.
If that's not the case, feel free to re-open it!
