### ISSUE TITLE
How to dynamically print the raw value of the input ?

### ISSUE THREAD

**Issue by alicinci** [autoNumeric/autoNumeric#620]
AutoNumeric is not working correctly when i try to dynamically print the raw value in the AutoNumeric's input like in the AutoNumeric's web page. I use pure javascript or jQuery. How can i do this right way ? Hope you can help me.

**Comment by AlexandreBonneau** [comment]
@alicinci For info, a reproducible test case is a must if you want to get a quick and accurate answer.
Also, if it "works" on the official webpage, but not on your side, it usually means your code is at fault ;P
