### ISSUE TITLE
Autonumeric after insert/append elements

### ISSUE THREAD

**Issue by anhnt9996** [autoNumeric/autoNumeric#624]
### Steps to reproduce the problem
AutoNumeric version `<v4.1.0>`

### Issue
After i insert an elements, autonumeric not work with these elements. How can i solved this problem?

Sorry for my English

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this issue, however with the few information you gave us, we are not able to correctly reproduce it.
Could you please create a [reproducible test case](https://codepen.io/pen/) so we can fix your bug?

**Comment by anhnt9996** [comment]
[Codepen](https://codepen.io/dominonta/pen/JwZOPz). This is an exemple of my problem, cloned input cant use AutoNumeric @AlexandreBonneau

**Comment by AlexandreBonneau** [comment]
Well, you need to initialize your new input the same way you initialized the first one, using:
```js
new AutoNumeric('.newInput');
```
