### ISSUE TITLE
Hi, I am working on angular (6.0) based website and there is a calculator calculations with some input fields. It is fully mobile responsive as well.  In Android devices i am unable to enter . (point) from the numeric keyward. For example if i am entering 0.01 then it immediately returned value to 50 (after pressing .(point).  In IOS devices it is working perfectly.

### ISSUE THREAD

**Issue by Antier12** [autoNumeric/autoNumeric#628]
### Current behavior
<Please describe here what faulty behavior you are experiencing>

### Expected behavior
<Please describe here the expected behavior>

### Steps to reproduce the problem
1. Use autoNumeric version `<vX.X.X>`
2. In the browser `<Chrome|Firefox>` version `<YY>`
3. On the `<Linux>` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric(domElement, { options });
```
5. <Then my computer exploded, for real.>

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
<Providing a live example of your problem that reproduce what you are experiencing usually means we'll be able to fix your issue *much more quickly* than if you don't.>

<Also, when creating an extract of your problem, you are likely to find the cause of it, and fix it yourself, :tada: ;)>

<Thanks for reporting a bug or giving us great ideas with your feature request!>

**Comment by AlexandreBonneau** [comment]
Due to inactivity, and given we do not have enough information on our side to resolve the issue, it has been marked and will be closed in the next few days.
Please give us more information if you feel the problem still affects you.

**Comment by AlexandreBonneau** [comment]
Due to inactivity, I'm closing this issue considering it resolved.
If that's not the case, feel free to re-open it!
