### ISSUE TITLE
How to get value raw Value on modified ?

### ISSUE THREAD

**Issue by PetroGromovo** [autoNumeric/autoNumeric#632]
Hi,
I use autoNumeric(@4.1.0) in my laravel 5.7/ blade / jQuery v3.3.1 / Bootstrap v4.1.2 app
inited with options no decimals:

```
        new AutoNumeric('#count', {
            maximumValue: '999999',
            minimumValue : 0,
            decimalPlaces : 0,
            showOnlyNumbersOnFocus : true
});
```

and I use laraval validation https://github.com/proengsoft/laravel-jsvalidation library, 
which trigger when field is changed (not only whem Submit is clicked)
so I got validation error 

 but I failed validate as with thousand separator I got value with “.” char,
 
Reading doc https://github.com/autoNumeric/autoNumeric  I found rawValue with callback mentioned: 
```
 const options = {
    styleRules : {
        userDefined: [
            // 1) If 'classes' is a string, set it if `true`, remove it if `false`
            { callback: rawValue => { return true; }, classes: 'thisIsTrue' },
            // 2) If 'classes' is an array with only 2 elements, set the first class if `true`, the second if `false`
            { callback: rawValue => rawValue % 2 === 0, classes: ['autoNumeric-even', 'autoNumeric-odd'] },
            // 3) Return only one index to use on the `classes` array (here, 'class3')
            { callback: rawValue => { return 2; }, classes: ['class1', 'class2', 'class3'] },
            // 4) Return an array of indexes to use on the `classes` array (here, 'class1' and 'class3')
            { callback: rawValue => { return [0, 2]; }, classes: ['class1', 'class2', 'class3'] },
            // 5) If 'classes' is `undefined` or `null`, then the callback is called with the AutoNumeric object passed as a parameter
            { callback: anElement => { return anElement.getFormatted(); } },
        ],
    },
}
```
So I need when field is modified and focus is out to callback rawValue and get raw ineteger value to put it into other hidden input for submitting.

But I did not find how tro use it. Could you please provide a sample how to make it?

Thanks!

**Comment by AlexandreBonneau** [comment]
Hi, we [recommend](https://github.com/autoNumeric/autoNumeric#questions) using our [Gitter chat](https://gitter.im/autoNumeric/autoNumeric) for asking questions.
The Github issue tracker is for bugs and feature requests *only*.

That said, you can access the raw value of any AutoNumeric-managed input element using:
```js
const an = new AutoNumeric('#count', yourOptions);
console.log(an.rawValue); // Get the raw value
```
(see this [example](https://codepen.io/AnotherLinuxUser/pen/LqdbOy))

If you need to know when the value is changing, then listen to the [AutoNumeric event](https://github.com/autoNumeric/autoNumeric#autonumeric-custom-events-details) `'autoNumeric:rawValueModified'` which is triggered everytime the raw value is...modified.

Please continue this thread on Gitter, and keep the issue tracked for issue about the library.
