### ISSUE TITLE
No dist-Folder in release

### ISSUE THREAD

**Issue by mbaas2** [autoNumeric/autoNumeric#646]
Hello, I'm a AN-newbie - please be patient ;-)

### Current behavior
Download 4.5.4 from the [release-page(https://github.com/autoNumeric/autoNumeric/releases).

### Expected behavior
I tried the naive approach and directly referenced `src/AutoNumeric.js` in my HTML, but that failed.  I then found a reference on [GitHub](https://stackoverflow.com/questions/44610941/jquery-3-2-1-autonumeric-plugin-latest-uncaught-syntaxerror-unexpected-toke) which suggested to use `dist/autoNumeric.min.js`. However, there is no `dist`-folder in the downloaded archive,

### Steps to reproduce the problem
As described. I finally solved it be using NPM. If AN is really stand-alone, it would be nice if it was easily accessible w/o requiring that NPM-step...

**Comment by AlexandreBonneau** [comment]
Hi, we do not bundle generated files in the release, since adding this in git is not the best practice.

If you want a ready to go solution, you can include the generated files from the [cdns](https://github.com/autoNumeric/autoNumeric#in-the-browser).
