### ISSUE TITLE
Is there an option for the symbol to always be displayed, even if the input is empty?

### ISSUE THREAD

**Issue by electrotype** [autoNumeric/autoNumeric#650]
Is there an option for the symbol to always be displayed, even if the input is empty?

Currently, when the input is empty, the symbol only appears on mouse over or if the input has focus. I'd like it to *always* be displayed.

Is there an option for that I didn't see?

**Comment by ducman** [comment]
Look at the documentation for 'emptyInputBehavior'.

**Comment by AlexandreBonneau** [comment]
Indeed @electrotype , you should use the [emptyInputBehavior](http://autonumeric.org/guide#emptyInputBehavior) option with the `'always'` setting.
