### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by ducman** [autoNumeric/autoNumeric#651]
How do you configure autoNumeric that has a minimum value of 1 but also allow the value to be empty?

I went to the configurator generator site and had it set up with a  minimum value of 1; type in 20; delete 20 so the input is empty, on focus out, 20 re-appear.  

I'm dealing with a nullable integer with a min value of 1. So it can be null/empty or greater than 0.

**Comment by AlexandreBonneau** [comment]
This is unfortunately one of the most requested feature lately (see https://github.com/autoNumeric/autoNumeric/issues/543).

Currently AutoNumeric strives to only accept valid values at any moment (but somehow still allows you to delete the content of the input, which it should not if we were following that idea completely).
