### ISSUE TITLE
Destroy multiple autonumeric

### ISSUE THREAD

**Issue by ltrtuan** [autoNumeric/autoNumeric#654]
### Current behavior
iptAmountTransaction = new AutoNumeric.multiple('.ipt-amount-transaction',{ 
                                allowDecimalPadding : 'floats',                               
                                maximumValue: $('#txt-total-amount-project').text()
                            });

### Expected behavior
- Update maximumvalue for multiple selector when change value select
OR
- Destroy multiple Autonumeric and Re-init

**Comment by AlexandreBonneau** [comment]
Hey @ltrtuan , `new AutoNumeric.multiple()` creates new AutoNumeric objects, that's it.
If you have elements that are already initialized by AutoNumeric, you'll get a warning in the console.

If you want to update AutoNumeric objets that were already created, you should use their references and the `anElement.update(newOptions)` function.

As stated in the [documentation](https://github.com/autoNumeric/autoNumeric#initialize-multiple-autonumeric-objects-at-once), `AutoNumeric.multiple()` returns an array.
You can then update each element separatedly using `.update(newOptions)`.

**Comment by ltrtuan** [comment]
I want to update multiple AutoNumeric object. How can i do this
- First, initializing 
new AutoNumeric.multiple('.ipt-amount-transaction',{
allowDecimalPadding : 'floats',
maximumValue: $('#txt-total-amount-project').text()
});
- Update multiple
$('.ipt-amount-transaction').update({'max' : 100}); => doesn't work

**Comment by AlexandreBonneau** [comment]
As I said in the previous comment:
> If you want to update AutoNumeric objets that were already created, you should use their references and the `anElement.update(newOptions)` function.
> 
> As stated in the [documentation](https://github.com/autoNumeric/autoNumeric#initialize-multiple-autonumeric-objects-at-once), `AutoNumeric.multiple()` returns an array.
You can then update each element separatedly using `.update(newOptions)`.

So, in your specific case, you should do something like:
```js
const anArray  = new AutoNumeric.multiple('.ipt-amount-transaction', yourOptions, yourValue);
anArray.forEach(a => a.update({'max' : 100}));
```
