### ISSUE TITLE
ajax double initialize

### ISSUE THREAD

**Issue by medspec** [autoNumeric/autoNumeric#655]
i created a function to initialize;

`        function initDomListeners(){
          if($('input.format_number').length){  
            new AutoNumeric('input.format_number', {
              alwaysAllowDecimalCharacter: true,
              decimalCharacter: ",",
              digitGroupSeparator: "."
            });
          }
 };`

i call this method on load and on ajaxComplete
but the later one results in double digit
press a number and  that number ands in show twice.
What is the best practice to prevent this. 

Destroy everything? and reinitialize?

**Comment by AlexandreBonneau** [comment]
If you check the console, you'll likely see a warning message talking about how you are trying to initialize an AutoNumeric elements that is already initialized.

I don't know your code or what you are trying to do, but perhaps you should initialize all your static inputs once on load, then treat the ajax calls separately.
