### ISSUE TITLE
digitGroupSeparator not reconize '&#xA0;'

### ISSUE THREAD

**Issue by alphafoxtrotmike** [autoNumeric/autoNumeric#662]
Hi,

I face a problem using autonumeric in an asp.net core multilingual application.
I use .net @System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberGroupSeparator for getting the digitGroup separator according to the current language.

            const autoNumericOptions = {
                digitGroupSeparator: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberGroupSeparator',
                decimalCharacter: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator',
                decimalCharacterAlternative : "."
            };

            jQuery(function ($) {
                new AutoNumeric('#OverallLength', autoNumericOptions);
            });

it produce this code

```
<script src="https://cdn.jsdelivr.net/npm/autonumeric@4.5.10/dist/autoNumeric.js" type="text/javascript"></script>
<script type="text/javascript">

            // The options are...optional :)
            const autoNumericOptions = {
                digitGroupSeparator: '&#xA0;',
                decimalCharacter: ',',
                decimalCharacterAlternative : "."
            };


            jQuery(function ($) {
                new AutoNumeric('#OverallLength', autoNumericOptions);
            });
        });
</script>
```

It works when using english or spain language.
When i select french language i get this message

```
jquery.js:3827 Uncaught Error: The thousand separator character option 'digitGroupSeparator' is invalid ; it should be ',', '.', '٬', '˙', "'", '', ' ', ' ', ' ', ' ' or empty (''), [&#xA0;] given.
    at Function.throwError (AutoNumericHelper.js:935)
    at Function.validate (AutoNumeric.js:7916)
    at AutoNumeric._setSettings (AutoNumeric.js:6443)
    at new AutoNumeric (AutoNumeric.js:148)
    at HTMLDocument.<anonymous> (1:1162)
    at mightThrow (jquery.js:3534)
    at process (jquery.js:3602)
```

i use latest version of autonumeric  4.5.10

Thanks for your help.

**Comment by AlexandreBonneau** [comment]
`&#xA0;` is the "[No-Break Space](https://www.codetable.net/hex/a0)", and you can already use that for the `digitGroupSeparator` option.

Check : https://github.com/autoNumeric/autoNumeric/blob/28e5e4ed7185c9bdc7168d181316c7c2c74f3801/src/AutoNumeric.js#L3844

What you want is to use `'\u00a0'`.
