### ISSUE TITLE
'formulaMode: true' - not working

### ISSUE THREAD

**Issue by vietmeta** [autoNumeric/autoNumeric#665]
'formulaMode: true' - not working
Tested at http://autonumeric.org/configurator

**Comment by AlexandreBonneau** [comment]
Well, when used in a 'normal' code, it works as expected (see that [codepen](https://codepen.io/AnotherLinuxUser/pen/vYYoKXq?editors=1010)).
Apparently the bug is in the autonumeric website. Could you please create an issue on that repository ? Thanks !
