### ISSUE TITLE
full-width numbers cause strange behavior

### ISSUE THREAD

**Issue by MartinP7r** [autoNumeric/autoNumeric#673]
### Current behavior
trying to input full-width numbers (like in Japanse IME) will result in buggy behavior, numbers duplicating on windows or disappearing on MacOSX.

### Expected behavior
either correctly insert (or be able to transform) numbers or prevent full-width input in the first place.

### Steps to reproduce the problem
1. Use autoNumeric version `v4.5.10`
2. In the browser `Chrome` version `79`
3. On the `OSX` and `Windows` operating system
4. Then instantiate the autoNumeric object with the following options:
any

**Comment by ghost** [comment]
Any update?

**Comment by melloware** [comment]
Just reported at PrimeFaces as well: https://github.com/primefaces/primefaces/issues/12427

**Comment by AlexandreBonneau** [comment]
I am open to pull requests on this one, since I'm strapped for time lately, and also do not have a MacOSX nor a Windows computer to test this unfortunately.

**Comment by AlexandreBonneau** [comment]
Thanks to @maruTA-bis5 for the pull request!
This should fix the Japanese characters issue, but since I cannot test this myself for now, could you please confirm this bug is indeed closed?
Thanks again for the PR.

**Comment by melloware** [comment]
@AlexandreBonneau  @maruTA-bis5 

I think this fixes #717 as well?

**Comment by melloware** [comment]
Also #681 ??

**Comment by blutorange** [comment]
Any chance of getting the fix released? As melloware mentioned this should fix some issues. Over at PrimeFaces, we used to copy the code and modify it in-place. Now we've switched to using the NPM dependencies directly and need to apply a [patch](https://yarnpkg.com/cli/patch) to the autonumeric package.

**Comment by melloware** [comment]
+1 @AlexandreBonneau any chance we could get a release?

**Comment by AlexandreBonneau** [comment]
Version 4.10.8 is pushed to npm

**Comment by blutorange** [comment]
Awesome, thank you very much!
