### ISSUE TITLE
The caret position is wrongly positionned when setting the raw value to zero on numbers with a prefix currency symbol

### ISSUE THREAD

**Issue by joepetrakovich** [autoNumeric/autoNumeric#675]
### Current behavior
When the user tries to delete the first digit on a number with 5 or more digits, the cursor jumps to the end.  It did not do this in prior versions. 

### Expected behavior
The cursor should stay put.  If the user is trying to for example change 50,000 to 60,000, they should just have to delete the '5' and then enter '6'.  This bug jumps the cursor to the end and requires them to either delete the whole number or click back to the front.

### Steps to reproduce the problem
1. Open the demo codepen: https://codepen.io/AnotherLinuxUser/pen/JyBGpz
2. Type `55,000.00` into the input box.
3. Click to the position on the right side of the '5' and click delete.
4. Notice how the cursor jumps to the end.
6. Try using version 4.5.8 and it doesn't happen, so it must have been introduced in 4.5.9.

**Comment by AlexandreBonneau** [comment]
I was able to reproduce the behavior.
If you have the value `80,000.00`, then put the caret on `8|0,000.00` and hit `backspace`, then you get the usual value , but with the caret set at the end `0,000.00|`.

**Comment by AlexandreBonneau** [comment]
This is fixed in `4.5.13`.

**Comment by joepetrakovich** [comment]
Thank you for fixing it so quickly! :)
