### ISSUE TITLE
Set min value, clear input display min value but change event not fire

### ISSUE THREAD

**Issue by namnguyen2091** [autoNumeric/autoNumeric#679]
### Current behavior
<Please describe here what faulty behavior you are experiencing>
I set min value in config and then clear value in input, it displays min value but I can not see change event is fired. I set emptyInputBehavior: 'null' but it can not display blank. I using reactjs.

### Expected behavior
<Please describe here the expected behavior>
- Blank input when clear input and change event is always fire, every input change

### Steps to reproduce the problem
1. Use autoNumeric version 4.5.13
2. In the browser `<Chrome>` version `<YY>`
3. On the `Ubuntu 19.10` operating system
4. Then instantiate the autoNumeric object with the following options:
``
let params = {
            currencySymbol : '',
            onInvalidPaste: 'truncate',
            emptyInputBehavior: 'null'
        };
``
this.numeric = new AutoNumeric(this.input, params);
5. And in render method
```
<input
    type="text"
    ref={ref => this.input = ref}
    className="bp3-input"
    onChange={this.onChange.bind(this)}
    value={this.state.value}
    onBlur={e => console.log(this.input)}
/>
```

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this issue.
Could you please create a [reproducible test case](https://codepen.io/pen/) to speed up the management of this issue?
Does it happens in other browsers/versions?

**Comment by namnguyen2091** [comment]
Sorry for my missing infomation and for I dont know how to use codepen, I''l describle again:
1. Use autoNumeric version 4.5.13
2. In the browser <Chrome> version 80.0.3987.132
3. On the Ubuntu 19.10 and Windows 10 operating system

I set min value is 9, in very first time I enter 999 and press ctr+A and delete. This time, value from input is empty it's ok (I show log in console onChange), onChange worked but number display 9, value for input get from state is empty too.

And then, I press ctr+a again and press delete button. Min value is 9 is display again, onChange event does'nt work.
**Set min value, clear input display min value but change event not fire**

I dont know this is bug or not, so if not please tell me how to do **"setting has min value but when clear value, instead of display min value show empty and onChange event is fired and then I can set new state value for empty"**

I attach my code here, sorry for inconvenience.
**import React from "react";
import AutoNumeric from "autonumeric";

export class Numeric extends React.Component {
    constructor(props) {
        super(props);
        this.state = {value: ''};
    }

    componentDidMount() {
        let {propNumeric} = this.props;
        let params = {
            currencySymbol : '',
            onInvalidPaste: 'truncate',
            emptyInputBehavior: 'null'
        };
        if (typeof propNumeric === 'object') {
            params = Object.assign(propNumeric, params);
        }

        this.numeric = new AutoNumeric(this.input, params);
    }

    componentWillUnmount() {
        this.numeric.remove();
    }

    getDerivedStateFromProps(nextProps, prevState) {
        console.log(nextProps);
        console.log(prevState);
    }

    onChange(e) {
        console.log(e.target.value);
        this.setState({value: e.target.value});
    }

    render() {
        return (
            <input
                id="mynumeric"
                type="text"
                ref={ref => this.input = ref}
                className="bp3-input"
                onChange={this.onChange.bind(this)}
                value={this.state.value}
                // onBlur={e => console.log(this.input)}
            />
        );
    }
}

Numeric.defaultProps = {
    type: "text",
    outputFormat: "number",
    preDefined: {},
    className: "asdf",
};

<Numeric propNumeric={{minimumValue: 9}} />**

**Comment by AlexandreBonneau** [comment]
Thanks for taking the time to explain more your problem.
However a working reproducible test case is a must have in order for me to see the bug, and eventually fix it.
If setting up a codepen is too complex due to your react dependencies, you can use any other live code website, for instance [codesandbox](https://codesandbox.io/), which include out-of-the-box new react projects.

**Comment by namnguyen2091** [comment]
Please keep this ticket till this weekend, I will add my code to codesandbox

**Comment by AlexandreBonneau** [comment]
Due to inactivity, and given we do not have enough information on our side to resolve the issue, it has been marked and will be closed in the next few days.
Please give us more information if you feel the problem still affects you.
