### ISSUE TITLE
How to start at cents?

### ISSUE THREAD

**Issue by muriloinflue** [autoNumeric/autoNumeric#680]
### Current behavior
Right now, if I type "1", the plugin assumes I mean "one unit of currency" formats it as 1.00 when I blur.
If I type "250", it formats it as 250.00 when I blur.
If I type "1500" it formats it to 1,500 as I type/blur.

### Expected behavior
If I type "1", the plugin should assume I mean "one cent of currency" format it as 0.01 as I type/blur.
If I type "250", it should format it as 2.50 as I type/blur.
If I type "1500", it should format as 15.00.

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
I'm using default configurations so don't think a live example would help. I do have an example of what I'm expecting, tho, and you can find it here (https://www.cssscript.com/demo/money-mask-library-vanilla-javascript/). I assume one of autoNumeric's options may do what I'm searching for, but I can't see to find it.

Thanks!

**Comment by muriloinflue** [comment]
Ok, looks like what I'm asking is exactly what this issue is asking as well (and with a much better title) https://github.com/autoNumeric/autoNumeric/issues/571 , so I'm closing this issue. I just hope the example I provided could help you achieve it :)

**Comment by AlexandreBonneau** [comment]
The issue you are referring as no relation with your request ; it's about shifting numbers.

What you want to use is the [`divisorWhenUnfocused`](http://autonumeric.org/guide#divisorWhenUnfocused) option set to `100` (see the [live example](https://codepen.io/AnotherLinuxUser/pen/abvRXWB?editors=1010)).
Then you'll get the behavior your are looking for!

**Comment by marbuser** [comment]
@AlexandreBonneau 
`divisorWhenUnfocused` works great but there are a few issues with this.

In the example you provided hovering/focusing the input causes the formatting to break and go from `9.99` to `999.00`

There is also another issue I noticed. If you type in `999` it will become `9.99`. However, if you literally type in `9,99` or `9.99` it will become `0.10`.

Any idea about how to get around those issues?
