### ISSUE TITLE
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/autoNumeric.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by AdeSupriyadi** [autoNumeric/autoNumeric#683]
get warning:
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/autoNumeric.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

![image](https://user-images.githubusercontent.com/14267724/82857948-a7c85680-9f3c-11ea-857f-8a9188bf8681.png)

is it normal?
how to solve it

OS: ubuntu 20.04
Browser: Chrome Latest

**Comment by AlexandreBonneau** [comment]
The error 404 tells us that your link is wrong.
Please browse [the files here](https://www.jsdelivr.com/package/npm/autonumeric), and the [map here](https://cdn.jsdelivr.net/npm/autonumeric@4.6.0/dist/autoNumeric.min.js.map).

Most CDN provides those files correctly, like [unpkg](https://unpkg.com/autonumeric) (see the [map here](https://unpkg.com/autonumeric/dist/autoNumeric.min.js.map))

For info, jsdelivr (and other CDN) generate the files automatically whenever a tag is created on the AutoNumeric repo.
