### ISSUE TITLE
Deletion of Decimal Unexpected Behavior

### ISSUE THREAD

**Issue by jroozee** [autoNumeric/autoNumeric#685]
### Current behavior
If user enters "$123.45" then places cursor to right of decimal (e.g. "$123.|45"), presses Backspace to delete the the decimal, the value changes to "$12,345"

### Expected behavior
A user unlikely is trying to change "$123.45" to "$12,345". The user most likely placed their cursor in the wrong position, or meant to delete the "3" in this example not the decimal. 

1. If cursor is to **right** of decimal and selection length is 0, and user presses **backspace**, the decimal should remain. i.e., the keystroke should be cancelled.
2. If cursor is to **left** of decimal and selection length is 0, and user presses **delete**, the decimal should remain. i.e., the keystroke should be cancelled.
3. If user partially selects text that includes or overlaps the decimal, the selection should automatically adjust either to the right or left of the decimal. Left or right should be determined based on number of characters selected before or after the decimal. For example for a value of "$123.45":

- If user selects "3.45" portion, the selection should auto-adjust to just the "45" portion. 
- If user selects "123.4" portion, the selection should auto-adjust to just the "123" portion.
- If user selects "3.4" portion, the selection should auto-adjust to just the "4" or "3" portion, or selection should be removed entirely.
-User should not be allowed to highlight just the decimal. 

To summarize:
User should not be able to delete the decimal if selection length is 0 and cursor is to the right or left of the decimal.  And the selection of text should auto-adjust when their is a partial selection to prevent user from overwriting the decimal.  These two desired behaviors are independent of each other.  The latter is less of a priority.

### Steps to reproduce the problem
1. Use autoNumeric version 4.6.0
2. In the browser Chrome version 81 and 83.
3. On the Windows operating system
4. Then instantiate the autoNumeric object with the following options:
```js
CurrencySymbol: "$",
    decimalCharacterAlternative: ",",
    decimalPlacesRawValue: 2,
    decimalPlacesShownOnBlur: 2,
    decimalPlacesShownOnFocus: 2,
    emptyInputBehavior: "always",
    historySize: 5,
    maximumValue: "999999",
    minimumValue: "0",
    negativePositiveSignPlacement: "p",
    onInvalidPaste: "clamp",
    unformatOnSubmit: true,
    emptyInputBehavior: "zero",
    modifyValueOnWheel: false
```

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://www.quantumpayments.com/sandbox/Practice/autoNumericExample.html

**Comment by AlexandreBonneau** [comment]
Thanks for the report and detailed explanation of your feature request.
However, this is the intended behavior.
What you are proposing is essentially preventing the user to remove the decimal character (which is a pretty important feature when typing numbers!).
This is a too specific use case to integrate that in AutoNumeric, sorry.
