### ISSUE TITLE
Work well localy but not in production 

### ISSUE THREAD

**Issue by v2lrf** [autoNumeric/autoNumeric#690]
### Expected behavior
The lib is just run perfectly locally, but nothing happen in production 
The lib is used and called through webpack, 

### Steps to reproduce the problem
1. Use autoNumeric version "autonumeric": "^4.6.0",
2. In the browser `Version 83.0.4103.106 `
4. Then instantiate the autoNumeric object with the following options:

```js
import AutoNumeric from 'autonumeric';
const initAutoNumeric = () => {
  const setAutoNumericInput = () => {
    var currency_inputs = document.querySelectorAll('.currency_input');
    console.log(currency_inputs);
    currency_inputs.forEach((currency_input) => {
      new AutoNumeric(currency_input).french();
    });
  };

  var buttons = document.querySelectorAll('.triger_modalCreateSeasonPrice');
  if (buttons) {
    buttons.forEach((button) => {
      button.addEventListener('click', () => {
        setTimeout(setAutoNumericInput.bind(null), 200);
      });
    });
  }
};

export { initAutoNumeric };
```
I think that there is a trick about the production issue but can't figure what yet

**Comment by v2lrf** [comment]
.... sometime setTimeout need to be more generous => put that to 400 and it s fine

**Comment by AlexandreBonneau** [comment]
I'm glad you solved your problem.

For info, instead of using a `forEach`, you could directly use:
```js
const anElements = AutoNumeric.multiple('.currency_input', 'French');
```

Also, depending of the underlying technology you use, relying on `setTimeout` is a bad practices, since it's not really deterministic.
Most framework (ie. Vue) have a way to catch an event when a given dom element has been rendered. Perhaps you could check that out?

**Comment by v2lrf** [comment]
> Also, depending of the underlying technology you use, relying on `setTimeout` is a bad practice, since it's not really deterministic.
> Most framework (ie. Vue) have a way to catch an event when a given dom element has been rendered. Perhaps you could check that out?

hi @AlexandreBonneau I have Two different way to solve that you are absolutely right even with my tec . In My case React could be an option, but the fasted implementation is through stimulus reflex. 

Thanks for your answer and for the ```multiple ```option
