### ISSUE TITLE
Currency can be deleted

### ISSUE THREAD

**Issue by Sector14** [autoNumeric/autoNumeric#697]
### Current behavior

When currency symbol is more than a single character, eg "US$" or "CN¥", pressing backspace to delete numbers will continue to delete the last character of the currency too.

### Expected behavior

Either all characters should be deleted at once or none of them. Ideally currency symbol should be possible to make  read only to prevent any character other than the numeric being deleted.

### Steps to reproduce the problem

To recreate, visit http://autonumeric.org/guide#currencySymbol and scroll down to the custom currency box. Enter "US$" in the custom value. You are unable to delete the $ sign initially, but if you delete each value of the number then press delete once more, you can remove the "$"

The moment you enter any numbers the currency will correct itself and go from "US" back to "US$".

### Link to live 

See reproduction link

**Comment by zelucena** [comment]
I've had this same issue with `AutoNumeric.getPredefinedOptions().Brazilian`. Also I should point out there should be a space between the currency symbol and the actual value but there is not.

**Comment by AlexandreBonneau** [comment]
@zelucena Thanks for reporting the problem with the Brazilian real. This is fixed in [this commit](https://github.com/autoNumeric/autoNumeric/commit/1afbda95f24b882e88906f11ee124cbca403affc).

@Sector14 could you please close this issue if you think @LothaireLaeuffer 's PR fixed it?

**Comment by Sector14** [comment]
I'll take a look (hopefully) next week and let you know.

**Comment by Sector14** [comment]
I've had a look, this does not fix the underlying issue. 

The patch looks to only append a space to the display name of the Brazilian real. The issue impacts more currencies than just the Brazilian. For example US and CN.

The space is a hacky workaround we used as a temporary fix, it does not feel like it should be employed as an actual solution as the currency symbols themselves shouldn't really have spaces.

The underlying issue is that you can press delete/backspace and cause the symbol to be deleted. That shouldn't be possible.

**Comment by Sector14** [comment]
> @Sector14 could you please close this issue if you think @LothaireLaeuffer 's PR fixed it?

Tested with USD currency and it does appear to resolve the problem. Thanks.
