### ISSUE TITLE
`AutoNumeric.multiple()` fail on IE11 'Symbol' is undefined

### ISSUE THREAD

**Issue by belchev** [autoNumeric/autoNumeric#698]
### Current behavior
Version: 4.6.0
Error in IE 11 console states ```"Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."```

### Expected behavior
The .multiple() call works fine in all other browsers I've tested except IE 11.

### Steps to reproduce the problem
1. Set up more than one input field with a given class, e.g. "money-input".
2. Call
```js
AutoNumeric.multiple('.money-input', {currencySymbol : '$',
    minimumValue: '0',
    decimalPlaces: '0',
    modifyValueOnWheel: false,
    readOnly: true,
    emptyInputBehavior: 'null'}
);
```

### Link to live example
https://jsbin.com/guxumayari/edit?html,js,output

Similarity with issue https://github.com/autoNumeric/autoNumeric/issues/495

**Comment by AlexandreBonneau** [comment]
This looks like this [babel issue](https://github.com/babel/babel/issues/11195).

**Comment by AlexandreBonneau** [comment]
IE11 support has been dropped as of `4.10.0`.
