### ISSUE TITLE
Autonumeric in ES5 version? 

### ISSUE THREAD

**Issue by bohoirup** [autoNumeric/autoNumeric#705]
### Current behavior
I am trying to use autonumeric with a pdf rendering tool, but the tool only supports ES5 and below. Is there a version of Autonumeric in ES5 or? 

### Expected behavior
<Please describe here the expected behavior>

### Steps to reproduce the problem
1. Use autoNumeric version `<v4.5.0>`
2. In the browser `<Chrome>` version `<YY>`
3. On the `<Linux>` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric(domElement, { options });
```
5. <Then my computer exploded, for real.>

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
<Providing a live example of your problem that reproduce what you are experiencing usually means we'll be able to fix your issue *much more quickly* than if you don't.>

<Also, when creating an extract of your problem, you are likely to find the cause of it, and fix it yourself, :tada: ;)>

<Thanks for reporting a bug or giving us great ideas with your feature request!>

**Comment by AlexandreBonneau** [comment]
Hi, we [recommend](https://github.com/autoNumeric/autoNumeric#questions) using our [Gitter chat](https://gitter.im/autoNumeric/autoNumeric) for asking questions.
The Github issue tracker is for bugs and feature requests *only*.

The generated library in the `dist/` folder is in es5 (via babel). Perhaps you could try using that ?

**Comment by bohoirup** [comment]
Hi Alexandre

Thanks for your reply.
Can  you please elaborate on where i find the dist folder with the ES5
version og the script?

I am already using the autonumeric.min.js ind the node_modules/dist folder
in my project.

Best regards
Bo
