### ISSUE TITLE
Github: latest stable release confusion

### ISSUE THREAD

**Issue by MircoBabin** [autoNumeric/autoNumeric#711]
Visiting the page https://github.com/autoNumeric/autoNumeric I'm confused what the latest release for production is. What is the latest stable release ?

1) The sidebar shows 4.1.0 as latest version:

![image](https://user-images.githubusercontent.com/8981285/112469952-5d855100-8d6a-11eb-98db-975e9d311560.png)

2) Looking at [releases](https://github.com/autoNumeric/autoNumeric/releases) shows 4.6.0 as latest version.

3) https://github.com/autoNumeric/autoNumeric/blob/next/README.md says:

> The latest stable branch is always on master. Currently this is version 4.2.*.

**Comment by AlexandreBonneau** [comment]
At one point the `next` branch was updated very often, hence we decided to use the `master` branch as the 'stable' one, where we merged `next` tags from time to time.
However I've been swamped at work for a few months now and the `next` branch as de facto been the 'stable' branch.

I have a task to merge `next` into `master` in my calendar, but I don't know when I'll be able to do that.
In the mean time, I recommend you use the latest release from `next` which is `4.6.0` as of now.
