### ISSUE TITLE
How with autoNumeric to fill lat/lng value without withhout truncating value?

### ISSUE THREAD

**Issue by sergeynilov** [autoNumeric/autoNumeric#713]
Hello,
I added autoNumeric v4.5.8 into my laravel 8 / AlpineJs 2.8 project for lat/lng coordinates 
filling with inputs defined :
```
                        <input class="editor_form_input" value="64.00" id="numeric_lat" name="numeric_lat" type="text" maxlength="12" autocomplete="off"  >
                        <input type="text" id="lat" name="lat" value="64.00" RRstyle="visibility: hidden; width: 1px; height:1px">
```
and autoNumeric definition, when on Value Modified unformatted value is written into hidden field:
```
                    new AutoNumeric('#numeric_lat', {    // implementation of decimal value editor from https://github.com/autoNumeric/autoNumeric
                        currencySymbolPlacement: current_currency_position,
                        currencySymbol: '',
                        decimalPlaces: 7,
                        maximumValue: 90.0,
                        minimumValue : -90.00
                    });
                    const latAutoNumeric = document.querySelector('#numeric_lat');
                    latAutoNumeric.addEventListener('autoNumeric:rawValueModified', e => {
                        if ( typeof e.detail.newRawValue != "undefined") {
                            document.getElementById('lat').value = e.detail.newRawValue
                        }
                    });

```                    
and it works ok, except I enter value like “-98.0187000” into hidden field value “-98.0187”
is wriiten. I did not find any option to write raw cvalue withhout truncating.

Has it any ?

Thanks!

**Comment by AlexandreBonneau** [comment]
AutoNumeric differentiate what is shown on the front-end, what data is stored, and what data you can retrieve.
On the front-end part, you can use:
```js
{
    // allowDecimalPadding: "always", // This is the default
    decimalPlaces: "8"
}
```
If you enter `-98.0187000` on the front-end, the `rawValue` will be the number `-98.0187`.
From there you can decide how to retrieve the element value ; as a string, as a formatted string, or as a number.

If you have `-98.0187000` shown in you element and want to retrieve this a a string, use `myANElement.getFormatted()`.
