### ISSUE TITLE
When `emptyInputBehavior` is set to `null`, then `getNumber()` returns `0` when no value has been set before

### ISSUE THREAD

**Issue by mshimokura** [autoNumeric/autoNumeric#718]
### Current behavior
<Please describe here what faulty behavior you are experiencing>

Using the option `{emptyInputBehavior: "null"}` does not provide the correct getNumber() value when there has been no change to the input / `set()` not called.

```js
const autonumeric = new AutoNumeric(document.createElement("input"), null, {emptyInputBehavior: "null"});
console.log(autonumeric.getNumber()); // 0
autonumeric.set(null);
console.log(autonumeric.getNumber()); // null
```

### Expected behavior
<Please describe here the expected behavior>

`getNumber()` should return the same value each time - `null`

### Steps to reproduce the problem
1. Use autoNumeric version `v4.6.0`
2. In the browser `Chrome` version `91`
3. On the `macOS` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric(domElement, null, {emptyInputBehavior: "null"});
```
5. Then `getNumber()` returns 0, not null as I was expecting.

**Comment by AlexandreBonneau** [comment]
So this behavior was intended as you can see in the [unit](https://github.com/autoNumeric/autoNumeric/blob/fba618d1b5892de5695a193255f20109a351ed97/test/unit/autoNumeric.spec.js#L1177) [tests](https://github.com/autoNumeric/autoNumeric/blob/fba618d1b5892de5695a193255f20109a351ed97/test/unit/autoNumeric.spec.js#L1197), however upon reflexion it seems logical to allow having a default `null` value on initialization if the value is undefined, and `emptyInputBehavior: "null"`.
