### ISSUE TITLE
Feature request: Up and down arrow keys behavior matching standard number input

### ISSUE THREAD

**Issue by h-guliyev** [autoNumeric/autoNumeric#719]
This is a feature request, not a bug report. Current behavior is fine for many uses, but another behavior would also be useful. This feature will go along/complement with exisitng wheel scrolling feature. 

### Current behavior
Currently up and down arrow keys take you to the end or beginning of the field respectively.

### Expected behavior
In standard [input control](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) with `type="number"` pressing up and down increases/decreases number. I suggest to add another mode and configure it similarly to wheel scroll (progressive/fixed increment). 
  UpDownArrowKey: standard/numeric

* standard would be current behavior
* numeric would be similar to type="number" i.e. would increase/decrease value on up/down keys

### Link to live example (ie. [Codepen](http://codepen.io/pen/))
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by melloware** [comment]
+1 reported at PrimeFaces as well: https://github.com/primefaces/primefaces/issues/9514

**Comment by beratbayram** [comment]
+1

**Comment by AlexandreBonneau** [comment]
You can now in `4.7.0` use two new options `modifyValueOnUpDownArrow` and `upDownStep` which acts similarly than `modifyValueOnWheel` and `wheelStep`.
By default the up and down arrow behavior is now activated.
