### ISSUE TITLE
AutoNumeric.set() breaks internal state when string-value has leading or trailing whitespace

### ISSUE THREAD

**Issue by metaxmx** [autoNumeric/autoNumeric#721]
### Current behavior
When I call the `set()` function of an AutoNumeric with a String-value which contains a leading or trailing whitespace (but is otherwise a valid number), then the value including the whitespaces is used as raw value and not trimmed in the process.

Examples:
- `set('3 ')`
- `set('  5')`
- `set('  11  ')`

This has some effects:

- when I call `getNumericString()` afterwards, then the whitespaces will also be included in the result, which is a problem when I want to use this number string for further processing in my application
- the max-check seems to work on the individual characters of the String, so trailing whitespaces break the check algorithm because the number seems longer than it is. E.g when I have a max-Value of `"30"` and enter a number `"4 "` via `set()`, then an error is raised, that the value is out of the [min, max] bounds.
- When the number has leading whitespaces, then the displayed number shows an additional `"0"` in the input. And also, when `getNumericString()` is called in this case, the additional Zero at the beginning, as well as the whitespaces will be returned.  E.g. when I call `set('       3        ').getNumericString()` then I get `"0       3        "` which totally breaks any number parsing after this point.

I could only reproduce this behaviour, when the given value is a valid number, ergo when `Number(stringValue)` returns a valid Number (which is not NaN). In cases where I have a Unit attached or when there is a locale-specific decimal point in place (e.g. "," in German locale) the number parsing seems to already return the trimmed value.

I believe, a simple fix for this problem would be if the `_toNumericValue()` function (and therefore also the `scientificToDecimal()` function) would return the trimmed input string, in case that it is already a valid number and no further parsing of a scientific number is required.

### Expected behavior
The AutoNumeric should trim the leading and trailing whitespaces from the value, before setting it as raw value. The Max-Check should work on the "real" given value, and `getNumericString()` should always return a valid number as string.

### Steps to reproduce the problem
See following CodePen:
https://codepen.io/metaxmx/pen/rNzLwKL

AutoNumeric Version: 4.6

I have show first the problematic parsing of normal number, where the whitespace problem exists.
```js
  var an = new AutoNumeric('#test');
  var value;

  value = "3 ";
  an.set(value);
  out.value += '\n' + "Set Value: '" + value + "'";
  out.value += '\n' + "Formatted Value: '" + an.getNumericString() + "'";
  
  value = "3.5 ";
  an.set(value);
  out.value += '\n' + "Set Value: '" + value + "'";
  out.value += '\n' + "Formatted Value: '" + an.getNumericString() + "'";
  
  value = "    7";
  an.set(value);
  out.value += '\n' + "Set Value: '" + value + "'";
  out.value += '\n' + "Formatted Value: '" + an.getNumericString() + "'";
```
Output:
```
Set Value: '3 '
Formatted Value: '3 '
Set Value: '3.5 '
Formatted Value: '3.5 '
Set Value: '    7'
Formatted Value: '0    7'
```

Then for constrast I have shown how the number parsing (correctly) works, if a unit is given and/or a localized decimal point:
```js
  var an2 = new AutoNumeric('#test2', {
    currencySymbol: "€",
    currencySymbolPlacement: "s",
    decimalCharacter: ",",
    decimalPlaces: 3,
    digitGroupSeparator: "."
  });
  
  value = "3€ ";
  an2.set(value);
  out.value += '\n' + "Set Value: '" + value + "'";
  out.value += '\n' + "Formatted Value: '" + an2.getNumericString() + "'";
  
  value = "3,5€ ";
  an2.set(value);
  out.value += '\n' + "Set Value: '" + value + "'";
  out.value += '\n' + "Formatted Value: '" + an2.getNumericString() + "'";
  
  value = "    7,5€";
  an2.set(value);
  out.value += '\n' + "Set Value: '" + value + "'";
  out.value += '\n' + "Formatted Value: '" + an2.getNumericString() + "'";
```
Output:
```
Set Value: '3€ '
Formatted Value: '3'
Set Value: '3,5€ '
Formatted Value: '3.5'
Set Value: '    7,5€'
Formatted Value: '7.5'
```

### Link to live example
https://codepen.io/metaxmx/pen/rNzLwKL

### Background
Some libraries that use AutoNumeric will call the `set()` function on `blur` of the corresponding input in order to circumvent some browser glitches.
E.g. PrimeFaces does this, which causes a consecutive NumberFormatException when the `currencySymbol = ' '`.

**Comment by AlexandreBonneau** [comment]
Thanks again @metaxmx, this should be fixed in `4.6.3`!
