### ISSUE TITLE
Fire the change event twice when creating a onchange event in jquery

### ISSUE THREAD

**Issue by Fantablup** [autoNumeric/autoNumeric#722]
$("#INVOICE_EXP_FEE_DB").change(async function(event){
 
});
### Current behavior
The change event is executing twice when it is initialized with AutoNumeric, and you press tab.

### Expected behavior
It should fire only once.

### Steps to reproduce the problem
1. Use autoNumeric version `<v4.1.0>`
2. In the browser `<Chrome>` version `<96.0.4664.45>`
3. On the `<windows 10>` operating system

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this issue.
Could you please create a [reproducible test case](https://codepen.io/pen/) so we can reproduce that bug?

**Comment by Fantablup** [comment]
> Thanks for reporting this issue. Could you please create a [reproducible test case](https://codepen.io/pen/) so we can reproduce that bug?

Of course :)
[https://codepen.io/fantablup/pen/dyVMPgR](url)
It actually fired change twice on the tab key pressed too.

It is the 4.10 version. I tested the newest version as you suggested, and it is fixed.
So, the bug is gone.

Thanks Alexandre :)
