### ISSUE TITLE
Fix for #684 merged but never released

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [autoNumeric/autoNumeric#724]
Sorry to create an issue for this - I left a couple messages on other relevant items in October and never heard back.

I see that a fix #684 was merged into the codebase on July 7. However, it does not seem that a release has been cut with this fix. Would you happen to have an ETA for when a release might happen for this fix? Thanks for any info! 😄

**Comment by Blackbaud-TrevorBurch** [comment]
@AlexandreBonneau any update on this? Thanks!

**Comment by JoshKasap** [comment]
I need this functionality added would really like to see it officially released.

**Comment by AlexandreBonneau** [comment]
This is part of version `4.6.1` onward.
