### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by stsrki** [autoNumeric/autoNumeric#726]
Hello, first of all, I would like to say you guys have a really good project here.

---

I'm trying to add autoNumeric into my Blazorise component library, but it seems it will not be so easy as I first thought. Based on the sentence in your readme 

> autoNumeric is a standalone Javascript library

I would assume autoNumeric uses vanilla JS and does not require any dependency like jQuery. Turns out it isn't exactly true. It even has `require("jquery")` in the `autoNumeric.js`. Also based on this #244 I would also assume jquery was already removed a long time ago.

---

What I want to accomplish is to import autoNumeric as a regular ES6 module. But unless I also use JQuery it will not be possible. Do you guys have any plans to remove it from the dependency?

**Comment by AlexandreBonneau** [comment]
Hi @stsrki, are you using the latest version of AutoNumeric, in the `next` branch?

Indeed, the jQuery dependency has been removed almost 5 years ago.

**Comment by stsrki** [comment]
You're right. I probably fetched some older versions without realizing it. If I build from the `next` branch jQuery is not found. Thanks.
