### ISSUE TITLE
Unable to group by 2 using digital group spacing options

### ISSUE THREAD

**Issue by titamrtn** [autoNumeric/autoNumeric#728]
### Current behavior
I've instantiate AutoNumeric like the doc said 
```js
AutoNumeric('#formelement', {
    allowDecimalPadding : false,
    digitGroupSeparator : ' ',
    digitalGroupSpacing : '2',
});
```

When i type : 3359893660 
the output is : 3 35 98 93 660

### Expected behavior
Since Group spacing is '2' i've expected that the output shoud be  33 59 89 36 60

Version used: v4.5.4

**Comment by AlexandreBonneau** [comment]
Indeed, this is a bug.
The faulty behavior is shown in [this example](https://codepen.io/AnotherLinuxUser/pen/rNGbVEX?editors=1010) with version `4.6.0`.

**Comment by AlexandreBonneau** [comment]
Ok this is not a bug, but the way numbers are grouped for India's Lakh.
However as said [here](https://github.com/autoNumeric/autoNumeric/pull/749#issuecomment-1386823529) it's better to use `2` to group by 2, and `2t` to group by 2 and 3 groups.
