### ISSUE TITLE
Incorrect change event fired on focus

### ISSUE THREAD

**Issue by melloware** [autoNumeric/autoNumeric#734]
### Current behavior
We discovered this bug testing your component use in PrimeFaces. 
Original Ticket: https://github.com/primefaces/primefaces/issues/8610

### Expected behavior
<Please describe here the expected behavior>

### Steps to reproduce the problem
1. focus val2
2.change the value, focus val1 via shift-tab
3. val2 will send a AJAX request and update @form (thats all correct!)
4. now val1 already has the focus
5. leave focus of val1
6. val1 fires change event because - but the value has not been changed; trigger is autonumeric.js ln 6004.  It is because `3000" != "3000.0"`. It is comparing the Strings and not the numerical values.

**Current Code:**
```js
      if (this.rawValue !== this.rawValueOnFocus) {
        this._triggerEvent(AutoNumeric.events["native"].change, e.target);
      }
```

**Fixed Code:**
```js
      if (Number(this.rawValue) !== Number(this.rawValueOnFocus)) {
        this._triggerEvent(AutoNumeric.events["native"].change, e.target);
      }
```

Submitting a PR.

**Comment by AlexandreBonneau** [comment]
Hello @melloware, thanks for pointing this out.

However while `Number()` should be enough for most use case, it's still limited to `2^53 -1`.
Perhaps this could be modified to take into account bigger numbers?

**Comment by melloware** [comment]
Interesting.  Does AutoNumeric handle numbers larger than that? Also I sent you a note on Gitter chat!

**Comment by AlexandreBonneau** [comment]
It's supposed to!
The part that manages those really big number has been written by @BobKnothe a decade ago, I'm do not remember if I created unit tests on this feature though..

**Comment by melloware** [comment]
OK you are right I found a better fix!  

This still compares the full string values but it just trims padded 0's before comparing which is really the use case we are hitting.

**Comment by mhombach** [comment]
@melloware is this issue solved for you? If so, please close it :)

**Comment by melloware** [comment]
@mhombach No its not I updated my PR to fix the issue to fix it a better way as @AlexandreBonneau suggested.

**Comment by mhombach** [comment]
Ah, thx for linking the PR :)
