### ISSUE TITLE
HTML5 Data Attributes

### ISSUE THREAD

**Issue by vincentwansink** [autoNumeric/autoNumeric#740]
Where can I find a list of valid HTML5 data attributes for autonumeric?

So far I've only found an example that uses the following:

- data-a-sign
- data-a-dec
- data-a-sep

Surely there are others.

**Comment by AlexandreBonneau** [comment]
Those `data-a-sign`, `data-a-dec` and `data-a-sep` example are obsolete and applies only to the 1.9.* version of AutoNumeric, which is almost a decade old (see the [doc](https://docs.autonumeric.org/Old%20documentation/v1.9%20documentation/)).

While Html5 data attributes for *all* the configuration options still work in the current version (`4.6.2`), it's *highly* recommended to use a configuration object to initialize your elements.
