### ISSUE TITLE
maximumValue is only appy to input event only

### ISSUE THREAD

**Issue by phuhd-0935** [autoNumeric/autoNumeric#743]
### Current behavior
maximumValue option is apply for input event & set event

### Expected behavior
maximumValue option is apply for only input event

### Steps to reproduce the problem
1. Use autoNumeric version `4.6.0`
2. In the browser `Chrome` version `94`
3. On the `<MacOS>` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric(domElement, {
    decimalPlaces: 1,
    maximumValue: 999
});
```
5. <Then my computer exploded, for real.>

### Link to live example (ie. [Codepen](https://codepen.io/JinnHuynh/pen/ExQBKge?editors=1011))
Currently i am developing currency conversion feature. There are 2 data input fields, usd and jpy, they automatically calculate the following amount back and forth, both must be limited to 999, however when i enter usd like 123, the calculated jpy number is greater than 999 for so it cannot be displayed. Is it possible to apply maximumValue to the only event input

**Comment by AlexandreBonneau** [comment]
The `maximumValue` option is per AutoNumeric elements, which means you'll have to use 2 differents options for your 2 different inputs.
Then you can just add an event listener to those to set the value of the other one on `change`.
