### ISSUE TITLE
Undo and Backspace issue

### ISSUE THREAD

**Issue by phuhd-0935** [autoNumeric/autoNumeric#744]
### Current behavior
Step by step:
- Input the input with value "9,099,990"
- Press the "Backspace" key on the keyboard to delete any number
- Press the Ctrl + Z to Undo
- Press the "Backspace" key on the keyboard again
- Verify: 909,90.0

### Expected behavior
- Expect: 90,990.0

### Steps to reproduce the problem
1. Use autoNumeric version `<v4.6.0>`
2. In the browser `<Chrome>` version `<94>`
3. On the `<Mac OS>` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric(domElement, {
  decimalPlaces: 1,
  maximumValue: 999999999999
});
```
5. <Then my computer exploded, for real.>

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this.
I've updated the [live example](https://codepen.io/AnotherLinuxUser/pen/jOvLvNK?editors=1010).
This is the same error reported in https://github.com/autoNumeric/autoNumeric/issues/761, and this is fixed and will be pushed very soon.
