### ISSUE TITLE
European percentage with 2 decimal places not working

### ISSUE THREAD

**Issue by ravipara72** [autoNumeric/autoNumeric#748]
Dear All,

I am trying to implement the 'percentageEU2dec' by using 'AutoNumeric' plug-in.

in my case this is not working.

Here is my code:
  $("#"+strDivin).val("23"); //setting value
  new AutoNumeric('#cmp-rate", "percentageEU2dec"); //Applied the plug-in on that element.

   Result : 2.300,00 %

  Expected result  : 23,00 %

can you please tell me what i am missing here. why i am not getting the Expected result  as "23,00 %".

Thank you for your help.

Regards,
Ravi

**Comment by AlexandreBonneau** [comment]
This is not a bug. 23 = 2300%.
If you want to see `23%`, you need to set the value accordingly; in that case `0.23`.

See the reproducible test case [here](https://codepen.io/AnotherLinuxUser/pen/zYWJWMw?editors=1010).
