### ISSUE TITLE
Jquery selector updating from v.1.9 to 4

### ISSUE THREAD

**Issue by manuTro** [autoNumeric/autoNumeric#754]
Hi, 

i'm updating autonumeric at the new version. with autonumeric 1.9 I was able to use the jquery selector, for example `$(this).autonumeric.get()`. 
How I can do the same with the new version?

Thx

**Comment by AlexandreBonneau** [comment]
Please take a look at the [documentation](https://docs.autonumeric.org/Developer%20guide/how%20to%20upgrade%20to%20v4/#method-calls).
