### ISSUE TITLE
Converted scientific numbers returns NaN when using `formArrayNumericString()`

### ISSUE THREAD

**Issue by sitenzo** [autoNumeric/autoNumeric#757]
### Current behavior
When using Autonumeric with 8 decimal numbers and only the last 1 or 2 are filled it returns "NaN"

### Expected behavior
Returning the number.

### Steps to reproduce the problem
See Js Fiddle

### Link to live example
[jsfiddle](https://jsfiddle.net/73qnorhd/)

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this.

I've updated the reproducible test case [here](https://codepen.io/AnotherLinuxUser/pen/eYLEybN?editors=1011), and narrowed down the reason this is happening.

The `formArrayNumericString()` function calls the `_serialize()` one, which in turns calls the `unformat()` one.
In this one, a call to `_convertToNumericString()` is done an return a number understood by Javascript, but in a scientific notation (i.e. `2e-8`).
This notation is then incorrectly interpreted by the following regex.
