### ISSUE TITLE
Certain Minimum/Maximum Values do not work as expected

### ISSUE THREAD

**Issue by tuerker** [autoNumeric/autoNumeric#759]
### Current behavior
The maximumValue as well as minimumValue does not always behave as expected!

I did several tests on http://autonumeric.org/examples to verify this:

While the following (minimumValue=1 maximumValue=100) worked as it should be:

![Screenshot from 2023-01-26 12-29-21](https://user-images.githubusercontent.com/10051373/214825799-c27ba9ef-71aa-4964-8977-b8d279ef53e4.png)

The following (minimumValue=-100 maximumValue=-1") did not work (cannot enter anything):

![Screenshot from 2023-01-26 12-30-44](https://user-images.githubusercontent.com/10051373/214825801-cdf1c438-6174-4703-bf8f-db912ac4794b.png)

The following two cases worked as expected:

![Screenshot from 2023-01-26 12-41-10](https://user-images.githubusercontent.com/10051373/214827345-5d5d3089-d948-4b62-8131-5a6f6c5c1fb6.png)

![Screenshot from 2023-01-26 12-42-57](https://user-images.githubusercontent.com/10051373/214827346-2b10de80-78c3-47de-8394-95949661b0d7.png)

The following one (minimumValue=10 maximumValue=120) which similar to the first example in constrast did not work  (cannot enter anything):

![Screenshot from 2023-01-26 12-31-50](https://user-images.githubusercontent.com/10051373/214825755-caf8dc3c-76a2-461a-9766-22378742d823.png)

Same problem for (minimumValue=20 maximumValue=150)

![Screenshot from 2023-01-26 13-02-52](https://user-images.githubusercontent.com/10051373/214830870-924458c6-6aac-4eaf-98c6-654c9774411d.png)

I am totally confused by the observations above. It looks like there is serious bug. Would be great if somebody could have a quick look on this issue. Many thanks in advance.

**Comment by melloware** [comment]
I think its why this setting exists:
![image](https://user-images.githubusercontent.com/4399574/214843317-dbf63c58-c625-46a0-ad25-c04c7527737f.png)

**Comment by tuerker** [comment]
I want the minimum and maximum values respected BUT this should be checked when i am done with entering the entire number!

The problem seems to be that after each entering of a digit, the validation is performed.

For instance, in case of 

```
{
    maximumValue: "300",
    minimumValue: "5"
}
```

it will not allow you to start with the digits 0 to 4. so far so good.

however, in case of 

```
{
    maximumValue: "300",
    minimumValue: "10"
}
```

you will not be able to satisfy the minimumValue after the first digit. thus, you cannot enter anything here.

I think that that overideMinMaxLimits makes only sense for use cases where you want to dynamically switch one/off the minimum and maximum value, respectively.

**Comment by tuerker** [comment]
The problem is that the minimum and maximum value validation checks can only be done after the entering of the entire number is completed (e.g. after no key has been pressed for a time interval, e.g., of two seconds).

**Comment by AlexandreBonneau** [comment]
> I think its why this setting exists: ![image](https://user-images.githubusercontent.com/4399574/214843317-dbf63c58-c625-46a0-ad25-c04c7527737f.png)

You are right @melloware, this is the setting you are looking for @tuerker. However this page of the AutoNumeric.org website is not up-to-date unfortunately (sorry), since it lacks the `invalid` option that solves the problem you mention (see issue https://github.com/autoNumeric/autoNumeric/issues/543).

You can get an explanation of how it works in the changelog [here](https://docs.autonumeric.org/Changelog/CHANGELOG/#460).
