### ISSUE TITLE
Copyright banner in the minimized distribution file is undefined

### ISSUE THREAD

**Issue by tagliala** [autoNumeric/autoNumeric#763]
Regression introduced in 4.8.0, and 4.7.0 reported a wrong version in the copyright banner

### Current behavior
```js
/**
 * AutoNumeric.js v4.8.0
 * © 2016-2023 undefined
 * © 2009-2016 undefined
 * Released under the MIT License.
 * See https://docs.autonumeric.org
 */
```

### Expected behavior
```js
/**
 * AutoNumeric.js v4.8.0
 * © 2016-2023 some copyright
 * © 2009-2016 some copyright
 * Released under the MIT License.
 * See https://docs.autonumeric.org
 */
```

### Steps to reproduce the problem
1. Go to https://cdnjs.cloudflare.com/ajax/libs/autonumeric/4.8.0/autoNumeric.min.js

**Comment by AlexandreBonneau** [comment]
Whoops ;x
Thanks for spotting this
