### ISSUE TITLE
autoNumeric and IE11 compatibility

### ISSUE THREAD

**Issue by slolo2000** [autoNumeric/autoNumeric#764]
### Current behavior
I would like to know if the last version of autoNumeric is still compatible with IE11?
If not, what is the last compatible version please?

By the past, there was a folder named "dist" in the package and I am not able to find it anymore.
So that's why I ask for this question.

EDIT:
After some tests, the compatibility seems to be broken after 4.6.0 branch (see third screenshot)

For the v4.6.0 there is also a problem for IE11 (see screenshot 4 and 5)
As you can see, the problem seems to be due to initialization with multiple elements like this:
```js
AutoNumeric.multiple('.numericInput', {
	watchExternalChanges: true
});
```

If you have a look to the sixth screenshot, "NodeList" is not supported in the "_unsupportedIterableToArray" function.
Perhaps there is a correction to do in that function.

Thanks in advance for your help and have a nice day.

### Expected behavior
Work with IE11 like before.

### Steps to reproduce the problem
1. Use autoNumeric version `<v4.8.1>`
2. In the browser `<Internet Explorer>` version `<11>`
3. On the `<Windows 7>` operating system
4. Then simply add autoNumeric to your web page:
```js
<script type="text/javascript" src="plugins/autoNumeric/4.8.1/autoNumeric.min.js"></script>
```
5. Then IE11 crash...

### Screenshots
![pb1](https://user-images.githubusercontent.com/10075509/229743513-aa9d8054-69c0-4ff1-a154-0658feb76754.jpg)
![pb2](https://user-images.githubusercontent.com/10075509/229743518-a30de9b8-03c3-49c8-bada-4ee5634eb147.jpg)
![pb3](https://user-images.githubusercontent.com/10075509/229743520-7e13976e-e053-46c7-9bff-918f86550cc0.jpg)
![pb4](https://user-images.githubusercontent.com/10075509/229748009-28a44681-1781-43ef-aef4-04b637975e6a.jpg)
![pb5](https://user-images.githubusercontent.com/10075509/229748015-31fe405b-1247-4ade-99e9-b8910dd6297d.jpg)
![pb6](https://user-images.githubusercontent.com/10075509/229756850-a9020b66-14f4-4c20-940d-3a4791edf3a2.jpg)

**Comment by AlexandreBonneau** [comment]
First, the `dist` files are not included in the repository anymore for a few versions now, since you can either use the source file directly as a module, build it yourself with one command, or use a CDN (since those will have the dist files which are published on NPM).

Second, the `_unsupportedIterableToArray()` function is not part of AutoNumeric, but likely generated by babel which is supposed to polyfill the functions that the obsolete IE11 browser do not support.

As I don't have a windows machine, could you please confirm that this was working as expected in the version prior to `4.6.0` ? Better yet, could you please do a dichotomy to find out which commit generated the IE11 error?

**Comment by slolo2000** [comment]
Hi,

Thanks for your answer.

The 2 first screenshots are from v4.8.1 of autoNumeric.
The next 3 are from v4.6.0, this is why I was able to debug the code (from autoNumeric.js)

And I got the source from:
"npm install autonumeric@4.6.0" and "npm install autonumeric@4.8.1"

So, v4.6.0 does not work with IE11.

By the past, I have used for a long time the v2.0.13 of autoNumeric and it works perfectly.
The v4.6.0 was the first occurence of v4.x I have used and I haven't seen that it was not compatible with IE11.

And for information, v4.1.0 works well on IE11

Source code from 4.1.0 to 4.6.0 is to different to find the reason.

But as you can see, _nonIterableSpread, _iterableToArray, ... do not exist in v4.1.0

![pb7](https://user-images.githubusercontent.com/10075509/229784621-13a8da64-4c83-4771-b34a-93db5fdab337.jpg)

Perhaps it is due to webpack v4 (see screenshot below)

![pb8](https://user-images.githubusercontent.com/10075509/229879153-f3112a74-935a-4898-a259-5645e0f14eaa.jpg)

**Comment by slolo2000** [comment]
I haven't seen but there is an issue that looks like #698

It is dated Jul 29, 2020, I suppose that IE11 compatibility is probably definitively dead, isn't it?

**Comment by AlexandreBonneau** [comment]
Well not necessarily; I'm not to fond supporting very (very) old browsers, and not using Windows on my end clearly does not help resolve the problem, however if the fixes are quick and easy enough, and does not affect too much the performance for other users, then why not apply those!

As you saw in #698, I asked the OP to test a polyfill from babel, but haven't heard from them.
Perhaps it means that they do not need IE11 support anymore, which would be logical given that very old technology usage is dwindling.
Also, this here is the second issue about IE11 usage, in 3 years, so I'm guessing this is a very niche use case nowadays.

I'm willing to integrate the fixes for this...IF somebody can create a comprehensive PR (with unit and end-to-end tests), since I cannot test that easily on my end.

Feel free to ping me on [Gitter](https://app.gitter.im/#/room/#autoNumeric_autoNumeric:gitter.im) for any help setting up the AutoNumeric environment, if needed.

Last question: do you really need to support IE11 on your end?

**Comment by slolo2000** [comment]
Hi,

Thanks for your answer.

> Last question: do you really need to support IE11 on your end?

In reality, not really. But if I can, it's still better for compatibility.

And for the challenge and the technical aspect (I don't know Yarn nor Babel) I will try to add the polyfill.

As you can see, building original project works perfectly.

![build460](https://user-images.githubusercontent.com/10075509/230001977-a2b43e8f-6278-496b-a9e9-c9a4a32aaf23.jpg)

But when adding the polyfill, I got an error.
I will try to investigate it.

![build460polyfill](https://user-images.githubusercontent.com/10075509/230002655-b1558384-3fb6-4c3c-8c34-d982ec1bfdda.jpg)

![build460error](https://user-images.githubusercontent.com/10075509/230002647-c8ebbabe-cc8a-42cc-9799-61d045e81390.jpg)

**Comment by slolo2000** [comment]
After modifying some pieces of code:

```js
function iterator() {
	const selfThis = this;
	let index = 0;
	let done;

	function Iterator() {}

	Iterator.prototype.next = function() {
		if (index > selfThis.length - 1) {
			done = true;
		}
		if (done) {
			return { value: undefined, done: true };
		}
		return { value: [index, selfThis[index++]], done: false };
	};

	// Many small polyfills leave out this method which Babel requires and otherwise throws the above error
	Iterator.prototype[Symbol.iterator] = function() {
		return this;
	};

	return new Iterator();
}

// Needed for: IE 11
if (!Array.prototype.entries) {
	Array.prototype.entries = iterator;
}

// Needed for: IE 11
if (!Array.prototype[Symbol.iterator]) {
	Array.prototype[Symbol.iterator] = iterator;
}
```

I only get the following error:

![build460error2](https://user-images.githubusercontent.com/10075509/230006136-696c6ad6-eef8-40ff-b948-f2bb1253e8cb.jpg)

**Comment by slolo2000** [comment]
I have done a test in commenting the following piece of code in .eslintrc.js file:

`        //'no-invalid-this': 'error',`

Build is OK but there is always a problem with IE11 because JavaScript built-in: Symbol is not supported by IE11 (see [caniuse](https://caniuse.com/?search=Symbol))

![pbsymbol](https://user-images.githubusercontent.com/10075509/230013235-51e5329d-5ccb-418f-821c-e1beeebf2427.jpg)

Any idea?

I will try to find a polyfill that works.

**Comment by AlexandreBonneau** [comment]
You can get a no error build using this snippet of code:
```js
CustomEvent.prototype = window.Event.prototype;
window.CustomEvent = CustomEvent;

// Needed for IE 11
function iterator() {
    // eslint-disable-next-line no-invalid-this
    const selfThis = this;
    let index = 0;
    let done;

    function Iterator() {}

    Iterator.prototype.next = function() {
        if (index > selfThis.length - 1) {
            done = true;
        }
        if (done) {
            return { value: undefined, done: true };
        }
        return { value: [index, selfThis[index++]], done: false };
    };

    // Many small polyfills leave out this method which Babel requires and otherwise throws the above error
    Iterator.prototype[Symbol.iterator] = function() {
        return this;
    };

    return new Iterator();
}

if (!Array.prototype.entries) {
    Array.prototype.entries = iterator;
}

if (!Array.prototype[Symbol.iterator]) {
    Array.prototype[Symbol.iterator] = iterator;
}
})();
```

Also, try adding `import 'core-js/es/symbol';` to the imports in the `AutoNumeric.js` file; does that fix your problem?

**Comment by slolo2000** [comment]
This instruction works well to build the package
`// eslint-disable-next-line no-invalid-this`

I also had the line below like you told me and add the package "core-js" to the project with "yarn add core-js"

```
//TODO Prevent having to enter relative path in the js files (ie. using `./AutoNumericHelper` instead of just `AutoNumericHelper`) (cf. http://moduscreate.com/es6-es2015-import-no-relative-path-webpack/)
import AutoNumericHelper from './AutoNumericHelper';
import AutoNumericEnum   from './AutoNumericEnum';
import Evaluator         from './maths/Evaluator';
import Parser            from './maths/Parser';
import 'core-js/es/symbol';
```

But now my own code does not work anymore.
In a simple loop like:
```
var aFoo = ['a', 'b', 'c'];
for (var a in aFoo) {
   console.log(a); // display 'a', then 'b', then 'c' and then 'entries' ???
}
```

Iterating an array does not work like expected in ES5.

**Comment by melloware** [comment]
I would vote for dropping IE support. Microsoft has given that guidance to everyone so any code that can be removed from libraries that has IE hacks in it should be ripped out. 

Just my two cents.

**Comment by AlexandreBonneau** [comment]
@melloware would you have a link where they officially states this?

**Comment by slolo2000** [comment]
[IE 11 end of life](https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/)

I am agree with @melloware, the special or hack code for IE11 (if exists) should be remove now.

**Comment by AlexandreBonneau** [comment]
There are plenty of hacks for IE11 in AutoNumeric codebase, unfortunately ; I'll drop support for it, and am in the process of removing all those hacks.

**Comment by melloware** [comment]
Yep and thanks for posting the link.  

Death to IE!!

**Comment by AlexandreBonneau** [comment]
IE11 support has been dropped in `4.10.0` (see this [commit](https://github.com/autoNumeric/autoNumeric/commit/30546cb0ece56213c2d0dd4c8eb17c723a4948f7) and [release](https://github.com/autoNumeric/autoNumeric/releases/tag/v4.10.0)).
Good riddance :)

**Comment by melloware** [comment]
@AlexandreBonneau I don't see this in NPM or CDN yet?

**Comment by AlexandreBonneau** [comment]
> @AlexandreBonneau I don't see this in NPM or CDN yet?

My bad, I forgot to publish it on npm ;x
I just pushed it now
