### ISSUE TITLE
`change` event is not triggered when dragging value into a text input

### ISSUE THREAD

**Issue by hukadev** [autoNumeric/autoNumeric#765]
### Current behavior
When I drag a value into an input, the value is format but the `change` event is not triggered.

### Expected behavior
The `change` event should be triggered.

### Steps to reproduce the problem
autoNumeric 4.8.1
lastest Chrome.

I've created an example here: https://jsfiddle.net/pso6jhbu/
1. Drag the value `123456789` into Input A, then lose focus. There is no alert.
2. Drag the value `123456789` into Input B, then lose focus. There is an alert.

I think we can modify the `_onDrop` function by adding this snippet:
```
// omitted
var event = new Event("change");
e.target.dispatchEvent(event);

this.isDropEvent = false;
```

**Comment by AlexandreBonneau** [comment]
Well, thanks for pointing that out.
Here we have differing behaviors between Firefox and Chrome, when the latter emits a 'change' event, while the former does not (see the example [here](https://codepen.io/AnotherLinuxUser/pen/oNaXRYX?editors=1011)).

From my experience when both browsers are doing things differently, Chrome is usually the bad player.
But for this matter, it sounds logical to emit a 'change' event if the content of the input is indeed, changed.
