### ISSUE TITLE
Autonumeric.multiple() called on Dynamically added table fields/rows (Multiplying the user input)

### ISSUE THREAD

**Issue by pms07** [autoNumeric/autoNumeric#770]
### Current behavior
Hello Everyone, 
I am new to Autonumeric,  It is great for number formatting.
Trying to find the solution from past 2 days.
I am using Autonumeric `<v4.9.0>` on `<Chrome|Microsoft Edge`> With `Windows` operating system.
I have form page with table and more than 15+ numeric fields with which are used in multiple js functions for calcualtions with 3 different autonumeric configurations.
I have used `Autonumeric.multiple(...) `with class selector for applying the particular configurations 
Its working perfectly fine.
With above I have functionality to add new table row dynamically via user input in which i am copying exisiting table row and appending the table with few inits. such as text as - and number as 0 
In which as soon as user inputs the number it gets doubled. as 
Input as 3. it will make it 33
If I add 2nd row dynamically, and input as 33 to 2nd row field it will make 3333 

I think its getting re-init due to again using Autonumeric.multiple(...)

My Sample code. 

On Page Init. -> 
Table is loaded with one row as default.
and following init is done for formatting.
```js
format_global_input_fields_two = AutoNumeric.multiple('.format_num_custom_two' , format_number_global_options);
format_global_input_fields_two.forEach(a => a.update({ decimalPlaces: 2, decimalPlacesRawValue : 2 }));
```

On Add new row to table -> 
```js
function addRow(tableID)
{
  var table = document.getElementById(tableID);
  var rowCount = table.rows.length;
  x = rowCount;

    var row = table.insertRow(rowCount);
    var colCount = table.rows[0].cells.length;
    for(var i = 0; i < colCount; i++)   
    { 
      var newcell       = row.insertCell(i);  
      if(i == 1)
        newcell.innerHTML = (rowCount)
      else
        newcell.innerHTML = table.rows[1].cells[i].innerHTML;

      switch(newcell.childNodes[0].type) 
      {
          case "checkbox":
                  newcell.childNodes[0].checked = false;
                  break;
          case "select-one":
                  newcell.childNodes[0].selectedIndex = 0;
                  break;
          case "number":
                  newcell.childNodes[0].value = "0";
                  break;
          case "text":
                    newcell.childNodes[0].value = "";
                    break;
      }
    }
    update_format_global_input_fields(); //calling the autonumeric to re-init 
}
```
Re-Init for the number fields.

```js
function update_format_global_input_fields()
{
  const format_global_input_fields_two = AutoNumeric.multiple('.format_num_custom_two' , format_number_global_options);
  format_global_input_fields_two.forEach(a => a.update({ decimalPlaces: 2, decimalPlacesRawValue : 2 }));
}
```

I am getting the warning as - `"Warning: A reference to the DOM element you just initialized already exists in the global AutoNumeric element list. Please make sure to not initialize the same DOM element multiple times."`

I have refered multiple options to use as `getAutoNumericElement` but not able to use effectively.
How should I check as in `update_format_global_input_fields` function for the fields are already init. and skip them
or Should I globally remove the Autonumeric config for all fields of same class and re-apply them ?

**Comment by AlexandreBonneau** [comment]
Hello @pms07, and thanks for using AutoNumeric :)

Your issue here is not an AutoNumeric one, but one with your website, please use the [official chat](https://app.gitter.im/?updated=1.11.30#/room/#autoNumeric_autoNumeric:gitter.im) to ask such question, since other users would then be able to guide you.

That said, in your specific case, I would just make sure to not reinit the first row. To do this, perhaps use another class on that specific row (i.e. `.firstRow`), the use:
```js
format_global_input_fields_two = AutoNumeric.multiple('.firstRow' , format_number_global_options);
```
