### ISSUE TITLE
error with decimal and min/max value

### ISSUE THREAD

**Issue by chatis** [autoNumeric/autoNumeric#771]
Hello,

I have created this code : https://codepen.io/pluginch/pen/gOQKoOW?editors=1010

but has you can see, I put a range between 6.50 and 11.25 with step of 0.05

But this is impossible to write 6.75 or any greater value than 9.99

How can I fix it ?

Thank you

**Comment by AlexandreBonneau** [comment]
You can now use the `overrideMinMaxLimits: 'invalid'` option to temporarily allow invalid values (in your case '6.' when you use the Delete key to remove the '50' part to enter '75' instead).

See [here](https://codepen.io/AnotherLinuxUser/pen/WNYyWGJ?editors=1010) and #543.
