### ISSUE TITLE
Typescript types in index.d.ts missing/wrong

### ISSUE THREAD

**Issue by Martino-Martinez** [autoNumeric/autoNumeric#773]
### Current behavior
I am using autoNumeric in Typescript. Some types are missing / are wrong in index.d.ts

### Expected behavior
Missing types should be added; errors should be corrected

### Steps to reproduce the problem

- https://docs.autonumeric.org/Documentation/updating%20options/#resetting-options

![image](https://github.com/autoNumeric/autoNumeric/assets/103148068/2e403b9c-fc0d-4ab5-9a5b-c120672531ae)

- anElement.options is missing in index.d.ts

![image](https://github.com/autoNumeric/autoNumeric/assets/103148068/6ae0e299-6481-4619-a754-1f66e2682348)

- https://docs.autonumeric.org/Documentation/static%20methods/#tests-and-miscellaneous

![image](https://github.com/autoNumeric/autoNumeric/assets/103148068/796ce7f1-9153-46b8-93bc-6ce09050be6e)

- Function signature in index.d.ts is wrong

![image](https://github.com/autoNumeric/autoNumeric/assets/103148068/8059b984-824a-46b8-be2d-b3e52cd7e821)

![image](https://github.com/autoNumeric/autoNumeric/assets/103148068/b0e8e604-7586-4b7e-9a57-4add0887f239)

**Comment by Martino-Martinez** [comment]
Here's me temporary solution to get rid of typescript warnings. Yes, it's a hack...

![image](https://github.com/autoNumeric/autoNumeric/assets/103148068/16fbe4a8-2ee0-4962-8fd4-6e25b73bea53)

![image](https://github.com/autoNumeric/autoNumeric/assets/103148068/5c6f57ed-95a7-4bfa-a471-c711cd192a0e)

**Comment by Martino-Martinez** [comment]
I believe this should be the correct type for Autonumeric.mergeOptions (according to the description in https://docs.autonumeric.org/Documentation/static%20methods/#tests-and-miscellaneous)

> static mergeOptions(options: **(string | Options)[]**): Options;

**Comment by AlexandreBonneau** [comment]
Hello @Martino-Martinez, could you please create a PR since you seem to have a working solution for the ts problem?
