### ISSUE TITLE
Issue with `autonumeric.org` certificate

### ISSUE THREAD

**Issue by tagliala** [autoNumeric/autoNumeric#775]
Hello, there is a certificate issue when trying to access autonumeric.org

![image](https://github.com/autoNumeric/autoNumeric/assets/556268/53b0af40-aecc-48dd-a2e0-b8011e67355f)

**Comment by AlexandreBonneau** [comment]
Yes, because the website is http only (due to the original github constraints).
If you know how to fix that, please create a PR in the [appropriate repo](https://github.com/autoNumeric/autonumeric.org), thanks!
