### ISSUE TITLE
Impossible write some decimal number when minimum and maximum values are set

### ISSUE THREAD

**Issue by mandzd** [autoNumeric/autoNumeric#784]
### Current behavior
I have this html code:
input type="text" class="numeric" data-minimum-value="0.5" data-maximum-value="5" data-decimal-places="1" lang="cs" value="1,5"
Then I tried edit number, for example to 0,7, but it was impossible.
Besides, it's difficult to rewrite other numbers.

### Expected behavior
Possibility to write number between 0,6 to 0,9.

### Steps to reproduce the problem
1. Use autoNumeric version `<v4.10.5>`
2. In the browser `<Chrome|Firefox>` version `<122.0.6261.129>`
3. On the `Windows` operating system
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric('input.numeric',{decimalCharacter : ',',digitGroupSeparator : ' '});
```

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this issue, however with the few information you gave us, we are not able to correctly reproduce it.
Could you please create a [reproducible test case](https://codepen.io/pen/) so we can fix your bug?

**Comment by mandzd** [comment]
Hi,
I created test case here: https://codepen.io/mandzd/pen/ZEZeVYK
Thank you for fixing bug.
Zdenek

**Comment by AlexandreBonneau** [comment]
I've reproduced your code [here](https://codepen.io/AnotherLinuxUser/pen/jORmbqR), and as you can see, everything works as expected.

On your test case, you need to add 'decimalPlaces: 2,' as an option so that you can see more decimal places.

Also, as you can see in the console, there is a warning message that is pretty self explicit:
```
Warning: You've set a `minimumValue` or a `maximumValue` excluding the value `0`. AutoNumeric will force the users to always have a valid value in the input, hence preventing them to clear the field. If you want to allow for temporary invalid values (i.e. out-of-range), you should use the 'invalid' option for the 'overrideMinMaxLimits' setting.
```

You can check issue https://github.com/autoNumeric/autoNumeric/issues/543 if you want more info.

**Comment by mandzd** [comment]
Hi,
thank you for your answer. Unfortunately it still doesn't work for me:

1) I need only one decimal place in my use case (I need prevent insert e.
g. value 1,75; valid is 1,7 or 1,8).
2) your code doesn't work on my desktop computer (Win 11) - i tried it in
Chrome (122.0.6261.131), Firefox (124), Edge... it is still impossible
(re)write on keyboard e. g. value 0,7

I also tried the 'invalid' option for the 'overrideMinMaxLimits', but then
the user can write e.g. value 0,2 ... I expect 0 to be in the range 0.5 to 5

Thank you, Zdenek
