### ISSUE TITLE
Change event is triggered while value does not change

### ISSUE THREAD

**Issue by SjorsVV** [autoNumeric/autoNumeric#785]
We use the autoNumeric library in APEX23 applications to disable the unwanted use of decimal numbers. 

### Current behavior
We have a problem with an change event trigger when the focus is set out of a numberfield even if the value of that field is not changed. 

### Expected behavior
If the value of a field is not changed it is expected that the change event is not triggered when you focus out of the field.

### Steps to reproduce the problem
1. Use autoNumeric version v4.5.9 or v4.6.2 or or v.4.10.5 (all three are tested)
2. In the browser Chrome version 123.0.6312.106
3. On the windows operating system
4. Then instantiate the autoNumeric object with the following options:
```js
new AutoNumeric($('input.number_mask')[index], {
                decimalPlaces: decimals,
                minimumValue: minValue,
                maximumValue: maxValue,
                digitGroupSeparator: groupSeparator,
                decimalCharacter: ',',
                decimalCharacterAlternative: '.',
                watchExternalChanges: true,
                modifyValueOnWheel: false,
                formatOnPageLoad: false,
                eventBubbles: false
            });
```
5. Then, when I focus into a numberfield and focus out of it (with my keyboard or a mouseclick) the onBlur is fired but the values this.rawValue and this.rawValueOnFocus are not equal because this.rawValueOnFocus is undefined. because of this the change event is fired.

![image](https://github.com/autoNumeric/autoNumeric/assets/167288715/16740ff7-3a30-44e7-a4b8-a7f2adecdb8e)
![image](https://github.com/autoNumeric/autoNumeric/assets/167288715/8d5b1777-6a93-4597-a155-b4aaf87c72da)
![image](https://github.com/autoNumeric/autoNumeric/assets/167288715/962ec61c-274a-4809-8fe3-12a874e338c6)

To fix the problem I added a line of code to set the value of this.rawValueOnFocus:

 ```
key: "_onFocusIn",
    value: function _onFocusIn(e) {
      this.rawValueOnFocus = this.rawValue; // THIS LINE IS ADDED
      if (this.settings.selectOnFocus) {
        // The whole input content is selected on focus (following the `selectOnFocus` and `selectNumberOnly` options)
        //XXX Firefox <47 does not respect this selection...Oh well.
        this.select();
      } else {
        // Or we decide where to put the caret using the `caretPositionOnFocus` option
        if (!_AutoNumericHelper__WEBPACK_IMPORTED_MODULE_0__["default"].isNull(this.settings.caretPositionOnFocus)) {
          _AutoNumericHelper__WEBPACK_IMPORTED_MODULE_0__["default"].setElementSelection(e.target, this._initialCaretPosition(_AutoNumericHelper__WEBPACK_IMPORTED_MODULE_0__["default"].getElementValue(this.domElement)));
        }
      }
    }
```

For the test that I did this solution works and I do not find any other problems, however I an not totally comfortable with the solution because I am not an extensive user of the AutoNumeric library and I do not know the impact on other parts of the library.

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this issue, however with the few information you gave us, we are not able to correctly reproduce it.
Could you please create a [reproducible test case](https://codepen.io/pen/) so we can fix your bug?

**Comment by SjorsVV** [comment]
Sorry for the inconvience but I found the source of the issue in our own code.
