### ISSUE TITLE
Predefined options: integerPos and integerNeg shouldn't allow zero

### ISSUE THREAD

**Issue by xuhdev** [autoNumeric/autoNumeric#789]
### Current behavior

Both options, `integerPos` and `integerNeg` permit zero:

https://github.com/autoNumeric/autoNumeric/blob/ea4a977c230c616fdcda6a5441c6009ce850d2c8/src/AutoNumericPredefinedOptions.js#L190-L196

### Expected behavior

Neither should include zero, based on the [doc](https://docs.autonumeric.org/Documentation/predefined%20options/#predefined-common-options).

> `integerPos`: Set the minimum and maximum value so that only a positive integer can be entered.

> `integerNeg`: Set the minimum and maximum value so that only a negative integer can be entered.

**Comment by AlexandreBonneau** [comment]
Well, this is as intended, since zero can be both considered positive and negative (see [here](https://en.wikipedia.org/wiki/0)):
> The number 0 can be regarded as neither positive nor negative or, alternatively, both positive and negative

We opted for the latter.

If you want to exclude 0 from the range, set `minimumValue` and `maximumValue` accordingly.

**Comment by xuhdev** [comment]
Thanks for the clarification. Could you clarify this in the doc?
