### ISSUE TITLE
users don't notice decimal dot is not entered and erroneously enter too large values

### ISSUE THREAD

**Issue by lukemim** [autoNumeric/autoNumeric#791]
When a field is configured to allow no decimal places the decimal dot is ignored when user types it in, however some users don't notice the dot wasn't entered and continue entering the decimal places, making the value too large. This is not a bug of autoNumeric per se, but it's a kind of UX issue. Is there any way around this while still keeping formatting existing values to zero decimal places?

**Comment by AlexandreBonneau** [comment]
Not that I can think of implemented in AutoNumeric. You could however try to listen to the input event and change the css class of the element for a visual cue, but that's outside of the scope of AutoNumeric.
