### ISSUE TITLE
Works on contenteditable=true?

### ISSUE THREAD

**Issue by JTorresConsulta** [autoNumeric/autoNumeric#794]
I want to use your amazing library over 

`<div contenteditable="true"> `

But it doesn't work.  :/

**Comment by AlexandreBonneau** [comment]
Thanks for reporting this issue, however with the few information you gave us, we are not able to correctly reproduce it.
Could you please create a [reproducible test case](https://codepen.io/pen/) so we can fix your bug?

**Comment by JTorresConsulta** [comment]
hi @AlexandreBonneau 

Excuse me, was my error. I dont know whats failed yesterday on my project. Works correctly now in a simple example. Please remove this issue.

Ex:  https://jsfiddle.net/uLmc6w1x/

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/autonumeric/4.10.5/autoNumeric.min.js" ></script>

<div id="inputCE" contenteditable="true">123456789</div>

<script>
  new AutoNumeric('#inputCE', 'NorthAmerican');
</script>
```
