### ISSUE TITLE
One minimized .js file

### ISSUE THREAD

**Issue by saidbakr** [autoNumeric/autoNumeric#801]
### Feature Request
Is there anyway that allows to have just one minimized .js file of the library? It is the old school idea via `<script>`

**Comment by AlexandreBonneau** [comment]
Hi, we [recommend](https://github.com/autoNumeric/autoNumeric#questions) using our [Gitter chat](https://gitter.im/autoNumeric/autoNumeric) for asking questions.
The Github issue tracker is for bugs and feature requests *only*.

**Comment by AlexandreBonneau** [comment]
It's [already the case](https://docs.autonumeric.org/Documentation/how%20to%20use/#in-the-browser) and can be found in the `/dist` dir.

**Comment by saidbakr** [comment]
In the repo,there is no dist folder!

**Comment by AlexandreBonneau** [comment]
@saidbakr please read the doc via the link I provided, and [this chapter](https://docs.autonumeric.org/Developer%20guide/how%20to%20contribute/#make-your-changes) as well.
In a nutshell, you never ever push generated files in a git repo; you need to either build it yourself, or using the ones from the CDN in the first link.
